// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reBuilding3Line = {
	"name": "building-3-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M10 10.1111V1L21 7V21H3V7L10 10.1111ZM12 4.36908V13.1886L5 10.0775V19H19V8.18727L12 4.36908Z\"/></g>"
} as const satisfies IconData;

export default reBuilding3Line;
export { reBuilding3Line };
export { reBuilding3Line as remixBuilding3Line };
