// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reClipboardLine = {
	"name": "clipboard-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M7 4V2H17V4H20.0066C20.5552 4 21 4.44495 21 4.9934V21.0066C21 21.5552 20.5551 22 20.0066 22H3.9934C3.44476 22 3 21.5551 3 21.0066V4.9934C3 4.44476 3.44495 4 3.9934 4H7ZM7 6H5V20H19V6H17V8H7V6ZM9 4V6H15V4H9Z\"/></g>"
} as const satisfies IconData;

export default reClipboardLine;
export { reClipboardLine };
export { reClipboardLine as remixClipboardLine };
