// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reCrossLine = {
	"name": "cross-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M9 2H15V7H20V13H15V22H9V13H4V7H9V2ZM11 4V9H6V11H11V20H13V11H18V9H13V4H11Z\"/></g>"
} as const satisfies IconData;

export default reCrossLine;
export { reCrossLine };
export { reCrossLine as remixCrossLine };
