// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reFlag2Line = {
	"name": "flag-2-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M21.1384 3C21.4146 3 21.6385 3.22386 21.6385 3.5C21.6385 3.58701 21.6157 3.67252 21.5725 3.74807L18 10L21.5725 16.2519C21.7095 16.4917 21.6262 16.7971 21.3865 16.9341C21.3109 16.9773 21.2254 17 21.1384 17H4V22H2V3H21.1384ZM18.5536 5H4V15H18.5536L15.6965 10L18.5536 5Z\"/></g>"
} as const satisfies IconData;

export default reFlag2Line;
export { reFlag2Line };
export { reFlag2Line as remixFlag2Line };
