// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reFlutterLine = {
	"name": "flutter-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M14.5979 10.6843H17.4264L11.7688 16.3419L17.4264 21.998H14.5979L8.94108 16.3412L14.5979 10.6843ZM14.4044 2.00439H17.2328L5.9191 13.3181L4.50488 11.9039L14.4044 2.00439Z\"/></g>"
} as const satisfies IconData;

export default reFlutterLine;
export { reFlutterLine };
export { reFlutterLine as remixFlutterLine };
