// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reLayoutBottomLine = {
	"name": "layout-bottom-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M21 3C21.5523 3 22 3.44772 22 4V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4C2 3.44772 2.44772 3 3 3H21ZM4 16V19H20V16H4ZM4 14H20V5H4V14Z\"/></g>"
} as const satisfies IconData;

export default reLayoutBottomLine;
export { reLayoutBottomLine };
export { reLayoutBottomLine as remixLayoutBottomLine };
