// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const reSkipDownLine = {
	"name": "skip-down-line",
	"set": "remix",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M12 10.0858L7.20712 5.29291L5.79291 6.70712L12 12.9142L18.2071 6.70712L16.7929 5.29291L12 10.0858ZM18 17L6.00001 17L6.00001 15L18 15V17Z\"/></g>"
} as const satisfies IconData;

export default reSkipDownLine;
export { reSkipDownLine };
export { reSkipDownLine as remixSkipDownLine };
