// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icfAlignHorizontalCenters = {
	"name": "align-horizontal-centers",
	"set": "iconoirfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M12 22L12 2\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M19 16H5C3.89543 16 3 15.1046 3 14L3 10C3 8.89543 3.89543 8 5 8H19C20.1046 8 21 8.89543 21 10V14C21 15.1046 20.1046 16 19 16Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\"/></g>"
} as const satisfies IconData;

export default icfAlignHorizontalCenters;
export { icfAlignHorizontalCenters };
export { icfAlignHorizontalCenters as iconoirfillAlignHorizontalCenters };
