// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icfNetworkLeft = {
	"name": "network-left",
	"set": "iconoirfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><rect x=\"2\" y=\"21\" width=\"7\" height=\"5\" rx=\"0.6\" transform=\"rotate(-90 2 21)\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<rect x=\"17\" y=\"15.5\" width=\"7\" height=\"5\" rx=\"0.6\" transform=\"rotate(-90 17 15.5)\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<rect x=\"2\" y=\"10\" width=\"7\" height=\"5\" rx=\"0.6\" transform=\"rotate(-90 2 10)\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M7 17.5H10.5C11.6046 17.5 12.5 16.6046 12.5 15.5V8.5C12.5 7.39543 11.6046 6.5 10.5 6.5H7\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M12.5 12H17\" stroke=\"currentColor\" stroke-width=\"1.5\"/></g>"
} as const satisfies IconData;

export default icfNetworkLeft;
export { icfNetworkLeft };
export { icfNetworkLeft as iconoirfillNetworkLeft };
