// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icfSkipNext = {
	"name": "skip-next",
	"set": "iconoirfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M18 7V17\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M6.97179 5.2672C6.57832 4.95657 6 5.23682 6 5.73813V18.2619C6 18.7632 6.57832 19.0434 6.97179 18.7328L14.9035 12.4709C15.2078 12.2307 15.2078 11.7693 14.9035 11.5291L6.97179 5.2672Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icfSkipNext;
export { icfSkipNext };
export { icfSkipNext as iconoirfillSkipNext };
