// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icfSpark = {
	"name": "spark",
	"set": "iconoirfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M3 12C9.26752 12 12 9.36306 12 3C12 9.36306 14.7134 12 21 12C14.7134 12 12 14.7134 12 21C12 14.7134 9.26752 12 3 12Z\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icfSpark;
export { icfSpark };
export { icfSpark as iconoirfillSpark };
