// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuArrowTop = {
	"name": "arrow-top",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M390.624 150.625 256 16 121.376 150.625l22.628 22.627 95.997-95.998v417.982h32V77.257l95.995 95.995z\"/>"
} as const satisfies IconData;

export default cuArrowTop;
export { cuArrowTop };
export { cuArrowTop as coreuiArrowTop };
