// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuBluetooth = {
	"name": "bluetooth",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M150.627 376 232 294.627V496h38.627l120-120-120-120 120-120-120-120H232v201.373L150.627 136h-45.254l120 120-120 120ZM264 54.627 345.373 136 264 217.373Zm0 240L345.373 376 264 457.373Z\"/>"
} as const satisfies IconData;

export default cuBluetooth;
export { cuBluetooth };
export { cuBluetooth as coreuiBluetooth };
