// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuChartLine = {
	"name": "chart-line",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M376 160v32h65.372L252 381.373l-72-72L76.686 412.686l22.628 22.628L180 354.627l72 72 212-211.999V280h32V160z\"/>\n  <path fill=\"currentColor\" d=\"M48 104H16v392h480v-32H48z\"/>"
} as const satisfies IconData;

export default cuChartLine;
export { cuChartLine };
export { cuChartLine as coreuiChartLine };
