// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuHighligt = {
	"name": "highligt",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"m104 305.5 88 48V480h128V353.5l88-48V160H104ZM136 192h240v94.5l-88 48V448h-64V334.5l-88-48ZM240 32h32v72h-32zM61.775 72.403l22.627-22.628 50.912 50.912-22.628 22.627zm314.91 28.281 50.912-50.911L450.224 72.4l-50.912 50.912z\"/>"
} as const satisfies IconData;

export default cuHighligt;
export { cuHighligt };
export { cuHighligt as coreuiHighligt };
