// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuStream = {
	"name": "stream",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M16 112h336v32H16zm144 128h336v32H160zM16 368h336v32H16z\"/>"
} as const satisfies IconData;

export default cuStream;
export { cuStream };
export { cuStream as coreuiStream };
