// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuToggleOn = {
	"name": "toggle-on",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M368 128H144a128 128 0 0 0 0 256h224a128 128 0 0 0 0-256m0 224H144a96 96 0 0 1 0-192h224a96 96 0 0 1 0 192\"/>\n  <path fill=\"currentColor\" d=\"M368 192a64 64 0 1 0 64 64 64.07 64.07 0 0 0-64-64m0 96a32 32 0 1 1 32-32 32.036 32.036 0 0 1-32 32\"/>"
} as const satisfies IconData;

export default cuToggleOn;
export { cuToggleOn };
export { cuToggleOn as coreuiToggleOn };
