// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuViewQuilt = {
	"name": "view-quilt",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M16 64v384h480V64Zm448 176H192V96h272Zm-272 32h120v144H192ZM48 96h112v320H48Zm296 320V272h120v144Z\"/>"
} as const satisfies IconData;

export default cuViewQuilt;
export { cuViewQuilt };
export { cuViewQuilt as coreuiViewQuilt };
