// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const cuVolumeLow = {
	"name": "volume-low",
	"set": "coreui",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M320 168v32a56 56 0 0 1 0 112v32a88 88 0 0 0 0-176m-174.627-48H16v272h129.373l104 104H288V16h-38.627ZM128 360H48V152h80Zm128 97.373-96-96V150.627l96-96Z\"/>"
} as const satisfies IconData;

export default cuVolumeLow;
export { cuVolumeLow };
export { cuVolumeLow as coreuiVolumeLow };
