// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ciClock2 = {
	"name": "clock_2",
	"set": "circum",
	"viewBox": "0 0 24 24",
	"body": "<g id=\"Clock_2\" data-name=\"Clock 2\">\n    <g>\n      <path d=\"M12,21.933A9.933,9.933,0,1,1,21.933,12,9.944,9.944,0,0,1,12,21.933ZM12,3.067A8.933,8.933,0,1,0,20.933,12,8.943,8.943,0,0,0,12,3.067Z\"/>\n      <path d=\"M18,12.5H12a.429.429,0,0,1-.34-.14c-.01,0-.01-.01-.02-.02A.429.429,0,0,1,11.5,12V6a.5.5,0,0,1,1,0v5.5H18A.5.5,0,0,1,18,12.5Z\"/>\n    </g>\n  </g>"
} as const satisfies IconData;

export default ciClock2;
export { ciClock2 };
export { ciClock2 as circumClock2 };
