// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ciSquareChevDown = {
	"name": "square_chev_down",
	"set": "circum",
	"viewBox": "0 0 24 24",
	"body": "<g id=\"Square_Chev_Down\" data-name=\"Square Chev Down\">\n    <g>\n      <path  d=\"M8.65,10.85a.495.495,0,0,1,.7-.7L12,12.79l2.65-2.64a.495.495,0,0,1,.7.7l-3,3a.492.492,0,0,1-.7,0Z\"/>\n      <path  d=\"M3.063,18.437V5.563a2.5,2.5,0,0,1,2.5-2.5H18.437a2.5,2.5,0,0,1,2.5,2.5V18.437a2.5,2.5,0,0,1-2.5,2.5H5.563A2.5,2.5,0,0,1,3.063,18.437ZM19.937,5.563a1.5,1.5,0,0,0-1.5-1.5H5.563a1.5,1.5,0,0,0-1.5,1.5V18.437a1.5,1.5,0,0,0,1.5,1.5H18.437a1.5,1.5,0,0,0,1.5-1.5Z\"/>\n    </g>\n  </g>"
} as const satisfies IconData;

export default ciSquareChevDown;
export { ciSquareChevDown };
export { ciSquareChevDown as circumSquareChevDown };
