// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const fas1 = {
	"name": "1",
	"set": "fontawesomesolid",
	"viewBox": "0 0 640 640",
	"body": "<path fill=\"currentColor\" d=\"M224 96C206.3 96 192 110.3 192 128C192 145.7 206.3 160 224 160L288 160L288 480L224 480C206.3 480 192 494.3 192 512C192 529.7 206.3 544 224 544L416 544C433.7 544 448 529.7 448 512C448 494.3 433.7 480 416 480L352 480L352 128C352 110.3 337.7 96 320 96L224 96z\"/>"
} as const satisfies IconData;

export default fas1;
export { fas1 };
export { fas1 as fontawesomesolid1 };
