// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfArrowArcLeftFill = {
	"name": "arrow-arc-left-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M232,184a8,8,0,0,1-16,0A88,88,0,0,0,67.47,120.16l26.19,26.18A8,8,0,0,1,88,160H24a8,8,0,0,1-8-8V88a8,8,0,0,1,13.66-5.66l26.48,26.48A104,104,0,0,1,232,184Z\"/>"
} as const satisfies IconData;

export default phfArrowArcLeftFill;
export { phfArrowArcLeftFill };
export { phfArrowArcLeftFill as phosphorfillArrowArcLeftFill };
