// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfBatteryVerticalEmptyFill = {
	"name": "battery-vertical-empty-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M88,8a8,8,0,0,1,8-8h64a8,8,0,0,1,0,16H96A8,8,0,0,1,88,8ZM200,56V224a24,24,0,0,1-24,24H80a24,24,0,0,1-24-24V56A24,24,0,0,1,80,32h96A24,24,0,0,1,200,56Zm-16,0a8,8,0,0,0-8-8H80a8,8,0,0,0-8,8V224a8,8,0,0,0,8,8h96a8,8,0,0,0,8-8Z\"/>"
} as const satisfies IconData;

export default phfBatteryVerticalEmptyFill;
export { phfBatteryVerticalEmptyFill };
export { phfBatteryVerticalEmptyFill as phosphorfillBatteryVerticalEmptyFill };
