// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfBluetoothFill = {
	"name": "bluetooth-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M200,176a8,8,0,0,1-3.2,6.4l-64,48A8,8,0,0,1,128,232a8,8,0,0,1-8-8V144L68.8,182.4a8,8,0,0,1-9.6-12.8L114.67,128,59.2,86.4a8,8,0,0,1,9.6-12.8L120,112V32a8,8,0,0,1,12.8-6.4l64,48a8,8,0,0,1,0,12.8L141.33,128l55.47,41.6A8,8,0,0,1,200,176Z\"/>"
} as const satisfies IconData;

export default phfBluetoothFill;
export { phfBluetoothFill };
export { phfBluetoothFill as phosphorfillBluetoothFill };
