// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfCaretLineRightFill = {
	"name": "caret-line-right-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M149.66,122.34a8,8,0,0,1,0,11.32l-80,80A8,8,0,0,1,56,208V48a8,8,0,0,1,13.66-5.66ZM184,40a8,8,0,0,0-8,8V208a8,8,0,0,0,16,0V48A8,8,0,0,0,184,40Z\"/>"
} as const satisfies IconData;

export default phfCaretLineRightFill;
export { phfCaretLineRightFill };
export { phfCaretLineRightFill as phosphorfillCaretLineRightFill };
