// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfCaretLineUpFill = {
	"name": "caret-line-up-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M213.66,186.34A8,8,0,0,1,208,200H48a8,8,0,0,1-5.66-13.66l80-80a8,8,0,0,1,11.32,0ZM48,80H208a8,8,0,0,0,0-16H48a8,8,0,0,0,0,16Z\"/>"
} as const satisfies IconData;

export default phfCaretLineUpFill;
export { phfCaretLineUpFill };
export { phfCaretLineUpFill as phosphorfillCaretLineUpFill };
