// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfCellSignalLowFill = {
	"name": "cell-signal-low-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M198.12,25.23a16,16,0,0,0-17.44,3.46l-160,160A16,16,0,0,0,32,216H192a16,16,0,0,0,16-16V40A15.94,15.94,0,0,0,198.12,25.23ZM192,200H88V144L192,40Z\"/>"
} as const satisfies IconData;

export default phfCellSignalLowFill;
export { phfCellSignalLowFill };
export { phfCellSignalLowFill as phosphorfillCellSignalLowFill };
