// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfCirclesThreeFill = {
	"name": "circles-three-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M128,120a44,44,0,1,1,44-44A44.05,44.05,0,0,1,128,120Zm60,8a44,44,0,1,0,44,44A44.05,44.05,0,0,0,188,128ZM68,128a44,44,0,1,0,44,44A44.05,44.05,0,0,0,68,128Z\"/>"
} as const satisfies IconData;

export default phfCirclesThreeFill;
export { phfCirclesThreeFill };
export { phfCirclesThreeFill as phosphorfillCirclesThreeFill };
