// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfDeviceTabletCameraFill = {
	"name": "device-tablet-camera-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M192,24H64A24,24,0,0,0,40,48V208a24,24,0,0,0,24,24H192a24,24,0,0,0,24-24V48A24,24,0,0,0,192,24ZM128,80a12,12,0,1,1,12-12A12,12,0,0,1,128,80Z\"/>"
} as const satisfies IconData;

export default phfDeviceTabletCameraFill;
export { phfDeviceTabletCameraFill };
export { phfDeviceTabletCameraFill as phosphorfillDeviceTabletCameraFill };
