// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfDeviceMobileSpeakerFill = {
	"name": "device-mobile-speaker-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M176,16H80A24,24,0,0,0,56,40V216a24,24,0,0,0,24,24h96a24,24,0,0,0,24-24V40A24,24,0,0,0,176,16ZM160,64H96a8,8,0,0,1,0-16h64a8,8,0,0,1,0,16Z\"/>"
} as const satisfies IconData;

export default phfDeviceMobileSpeakerFill;
export { phfDeviceMobileSpeakerFill };
export { phfDeviceMobileSpeakerFill as phosphorfillDeviceMobileSpeakerFill };
