// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfDotsThreeOutlineVerticalFill = {
	"name": "dots-three-outline-vertical-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M156,128a28,28,0,1,1-28-28A28,28,0,0,1,156,128ZM128,76a28,28,0,1,0-28-28A28,28,0,0,0,128,76Zm0,104a28,28,0,1,0,28,28A28,28,0,0,0,128,180Z\"/>"
} as const satisfies IconData;

export default phfDotsThreeOutlineVerticalFill;
export { phfDotsThreeOutlineVerticalFill };
export { phfDotsThreeOutlineVerticalFill as phosphorfillDotsThreeOutlineVerticalFill };
