// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfMinusCircleFill = {
	"name": "minus-circle-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm40,112H88a8,8,0,0,1,0-16h80a8,8,0,0,1,0,16Z\"/>"
} as const satisfies IconData;

export default phfMinusCircleFill;
export { phfMinusCircleFill };
export { phfMinusCircleFill as phosphorfillMinusCircleFill };
