// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfNotchesFill = {
	"name": "notches-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M200,40V192a8,8,0,0,1-8,8H40a8,8,0,0,1-5.66-13.66l152-152A8,8,0,0,1,200,40Z\"/>"
} as const satisfies IconData;

export default phfNotchesFill;
export { phfNotchesFill };
export { phfNotchesFill as phosphorfillNotchesFill };
