// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfSquareSplitVerticalFill = {
	"name": "square-split-vertical-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M216,56v60a4,4,0,0,1-4,4H44a4,4,0,0,1-4-4V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Zm-4,80H44a4,4,0,0,0-4,4v60a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V140A4,4,0,0,0,212,136Z\"/>"
} as const satisfies IconData;

export default phfSquareSplitVerticalFill;
export { phfSquareSplitVerticalFill };
export { phfSquareSplitVerticalFill as phosphorfillSquareSplitVerticalFill };
