// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfStopFill = {
	"name": "stop-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M216,56V200a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Z\"/>"
} as const satisfies IconData;

export default phfStopFill;
export { phfStopFill };
export { phfStopFill as phosphorfillStopFill };
