// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfSubtractSquareFill = {
	"name": "subtract-square-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M216,88H168V40a8,8,0,0,0-8-8H40a8,8,0,0,0-8,8V160a8,8,0,0,0,8,8H88v48a8,8,0,0,0,8,8H216a8,8,0,0,0,8-8V96A8,8,0,0,0,216,88ZM48,48H152V152H48Z\"/>"
} as const satisfies IconData;

export default phfSubtractSquareFill;
export { phfSubtractSquareFill };
export { phfSubtractSquareFill as phosphorfillSubtractSquareFill };
