// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phfToggleRightFill = {
	"name": "toggle-right-fill",
	"set": "phosphorfill",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M176,56H80a72,72,0,0,0,0,144h96a72,72,0,0,0,0-144Zm0,112a40,40,0,1,1,40-40A40,40,0,0,1,176,168Z\"/>"
} as const satisfies IconData;

export default phfToggleRightFill;
export { phfToggleRightFill };
export { phfToggleRightFill as phosphorfillToggleRightFill };
