// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icAngleTool = {
	"name": "angle-tool",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 21L3 3L9 3V15L21 15V21H3Z\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M13 19V21\" stroke=\"currentColor\" stroke-linecap=\"round\"/>\n<path d=\"M9 19V21\" stroke=\"currentColor\" stroke-linecap=\"round\"/>\n<path d=\"M3 7H5\" stroke=\"currentColor\" stroke-linecap=\"round\"/>\n<path d=\"M3 11H5\" stroke=\"currentColor\" stroke-linecap=\"round\"/>\n<path d=\"M3 15H5\" stroke=\"currentColor\" stroke-linecap=\"round\"/>\n<path d=\"M17 19V21\" stroke=\"currentColor\" stroke-linecap=\"round\"/></g>"
} as const satisfies IconData;

export default icAngleTool;
export { icAngleTool };
export { icAngleTool as iconoirAngleTool };
