// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icArrowRight = {
	"name": "arrow-right",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 12L21 12M21 12L12.5 3.5M21 12L12.5 20.5\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icArrowRight;
export { icArrowRight };
export { icArrowRight as iconoirArrowRight };
