// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icCell2x2 = {
	"name": "cell-2x2",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M21 3.6V12H12V3H20.4C20.7314 3 21 3.26863 21 3.6Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M21 20.4V12H12V21H20.4C20.7314 21 21 20.7314 21 20.4Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M3 12V3.6C3 3.26863 3.26863 3 3.6 3H12V12H3Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M3 12V20.4C3 20.7314 3.26863 21 3.6 21H12V12H3Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/></g>"
} as const satisfies IconData;

export default icCell2x2;
export { icCell2x2 };
export { icCell2x2 as iconoirCell2x2 };
