// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icFacebook = {
	"name": "facebook",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M17 2H14C12.6739 2 11.4021 2.52678 10.4645 3.46447C9.52678 4.40215 9 5.67392 9 7V10H6V14H9V22H13V14H16L17 10H13V7C13 6.73478 13.1054 6.48043 13.2929 6.29289C13.4804 6.10536 13.7348 6 14 6H17V2Z\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icFacebook;
export { icFacebook };
export { icFacebook as iconoirFacebook };
