// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icKanbanBoard = {
	"name": "kanban-board",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 3.6V20.4C3 20.7314 3.26863 21 3.6 21H20.4C20.7314 21 21 20.7314 21 20.4V3.6C21 3.26863 20.7314 3 20.4 3H3.6C3.26863 3 3 3.26863 3 3.6Z\" stroke=\"currentColor\"   stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M6 6L6 16\" stroke=\"currentColor\"   stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M10 6V9\" stroke=\"currentColor\"   stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M14 6V13\" stroke=\"currentColor\"   stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M18 6V11\" stroke=\"currentColor\"   stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icKanbanBoard;
export { icKanbanBoard };
export { icKanbanBoard as iconoirKanbanBoard };
