// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icMinusSquareDashed = {
	"name": "minus-square-dashed",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M7 4H4V7\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M8 12H12H16\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M4 11V13\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M11 4H13\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M11 20H13\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 11V13\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M17 4H20V7\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M7 20H4V17\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M17 20H20V17\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icMinusSquareDashed;
export { icMinusSquareDashed };
export { icMinusSquareDashed as iconoirMinusSquareDashed };
