// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icSimpleCart = {
	"name": "simple-cart",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 6H22L19 16H6L3 6ZM3 6L2.25 3.5\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M11 19.5C11 20.3284 10.3284 21 9.5 21C8.67157 21 8 20.3284 8 19.5\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M17 19.5C17 20.3284 16.3284 21 15.5 21C14.6716 21 14 20.3284 14 19.5\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icSimpleCart;
export { icSimpleCart };
export { icSimpleCart as iconoirSimpleCart };
