// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icTable2Columns = {
	"name": "table-2-columns",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 20.4V3.6C3 3.26863 3.26863 3 3.6 3H20.4C20.7314 3 21 3.26863 21 3.6V20.4C21 20.7314 20.7314 21 20.4 21H3.6C3.26863 21 3 20.7314 3 20.4Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M3 16.5H21\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M3 12H21\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M21 7.5H3\" stroke=\"currentColor\" stroke-width=\"1.5\"/>\n<path d=\"M12 21V3\" stroke=\"currentColor\" stroke-width=\"1.5\"/></g>"
} as const satisfies IconData;

export default icTable2Columns;
export { icTable2Columns };
export { icTable2Columns as iconoirTable2Columns };
