// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const icTournament = {
	"name": "tournament",
	"set": "iconoir",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke-width=\"1.5\"><path d=\"M3 3L8.00001 3L8.00001 9H3\" stroke=\"currentColor\"  stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M8 6L15 6L15 18H8\" stroke=\"currentColor\"  stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M15 12L22 12\" stroke=\"currentColor\"  stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M3 15L8.00001 15L8.00001 21H3\" stroke=\"currentColor\"  stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default icTournament;
export { icTournament };
export { icTournament as iconoirTournament };
