// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxAddressBook = {
	"name": "bx-address-book",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m19,2H5c-.55,0-1,.45-1,1v4h-2v2h2v2h-2v2h2v2h-2v2h2v4c0,.55.45,1,1,1h14c1.1,0,2-.9,2-2V4c0-1.1-.9-2-2-2Zm-13,2h8v16H6V4Zm13,16h-3v-2.5h3v2.5Zm0-4.5h-3v-2.5h3v2.5Zm0-4.5h-3v-2.5h3v2.5Zm0-4.5h-3v-2.5h3v2.5Z\"/>"
} as const satisfies IconData;

export default boBxAddressBook;
export { boBxAddressBook };
export { boBxAddressBook as boxiconsBxAddressBook };
