// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowInLeftSquareHalf = {
	"name": "bx-arrow-in-left-square-half",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M5 5h7V3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h7v-2H5z\"/><path d=\"m14 7-6 5 6 5v-4h7v-2h-7z\"/>"
} as const satisfies IconData;

export default boBxArrowInLeftSquareHalf;
export { boBxArrowInLeftSquareHalf };
export { boBxArrowInLeftSquareHalf as boxiconsBxArrowInLeftSquareHalf };
