// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowUpLeftCircle = {
	"name": "bx-arrow-up-left-circle",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10 10-4.49 10-10S17.51 2 12 2m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8\"/><path d=\"M15 9H9v6l2.29-2.29 3 3 1.42-1.42-3-3z\"/>"
} as const satisfies IconData;

export default boBxArrowUpLeftCircle;
export { boBxArrowUpLeftCircle };
export { boBxArrowUpLeftCircle as boxiconsBxArrowUpLeftCircle };
