// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowUpStrokeCircle = {
	"name": "bx-arrow-up-stroke-circle",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10 10-4.49 10-10S17.51 2 12 2m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8\"/><path d=\"m7.29 11.29 1.42 1.42 2.29-2.3V17h2v-6.59l2.29 2.3 1.42-1.42L12 6.59z\"/>"
} as const satisfies IconData;

export default boBxArrowUpStrokeCircle;
export { boBxArrowUpStrokeCircle };
export { boBxArrowUpStrokeCircle as boxiconsBxArrowUpStrokeCircle };
