// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowOutUpRightSquare = {
	"name": "bx-arrow-out-up-right-square",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12.71 12.71 18.21 7.21 21 10 21 3 14 3 16.79 5.79 11.29 11.29 12.71 12.71z\"/><path d=\"m11,5v-2h-6c-1.1,0-2,.9-2,2v14c0,1.1.9,2,2,2h14c1.1,0,2-.9,2-2v-6h-2v6H5V5h6Z\"/>"
} as const satisfies IconData;

export default boBxArrowOutUpRightSquare;
export { boBxArrowOutUpRightSquare };
export { boBxArrowOutUpRightSquare as boxiconsBxArrowOutUpRightSquare };
