// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowInLeftCircleHalf = {
	"name": "bx-arrow-in-left-circle-half",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M15 7 9 12 15 17 15 13 22 13 22 11 15 11 15 7z\"/><path d=\"m11,21v-2c-3.86,0-7-3.14-7-7s3.14-7,7-7v-2C6.04,3,2,7.04,2,12s4.04,9,9,9Z\"/>"
} as const satisfies IconData;

export default boBxArrowInLeftCircleHalf;
export { boBxArrowInLeftCircleHalf };
export { boBxArrowInLeftCircleHalf as boxiconsBxArrowInLeftCircleHalf };
