// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowOutLeftSquareHalf = {
	"name": "bx-arrow-out-left-square-half",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M9 13h7v-2H9V7l-6 5 6 5z\"/><path d=\"M19 3h-7v2h7v14h-7v2h7c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2\"/>"
} as const satisfies IconData;

export default boBxArrowOutLeftSquareHalf;
export { boBxArrowOutLeftSquareHalf };
export { boBxArrowOutLeftSquareHalf as boxiconsBxArrowOutLeftSquareHalf };
