// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowFromTopStroke = {
	"name": "bx-arrow-from-top-stroke",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M4 4H20V6H4z\"/><path d=\"M17.29 12.29 13 16.59 13 8 11 8 11 16.59 6.71 12.29 5.29 13.71 12 20.41 18.71 13.71 17.29 12.29z\"/>"
} as const satisfies IconData;

export default boBxArrowFromTopStroke;
export { boBxArrowFromTopStroke };
export { boBxArrowFromTopStroke as boxiconsBxArrowFromTopStroke };
