// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxArrowOutUpRightStrokeCircle = {
	"name": "bx-arrow-out-up-right-stroke-circle",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M14 4 18.59 4 11.29 11.29 12.71 12.71 20 5.41 20 10 22 10 22 2 14 2 14 4z\"/><path d=\"m17.66,17.66c-1.51,1.51-3.52,2.34-5.66,2.34s-4.15-.83-5.66-2.34c-1.51-1.51-2.34-3.52-2.34-5.66s.83-4.15,2.34-5.66c1.51-1.51,3.52-2.34,5.66-2.34v-2c-2.67,0-5.18,1.04-7.07,2.93-1.89,1.89-2.93,4.4-2.93,7.07s1.04,5.18,2.93,7.07c1.89,1.89,4.4,2.93,7.07,2.93s5.18-1.04,7.07-2.93c1.89-1.89,2.93-4.4,2.93-7.07h-2c0,2.14-.83,4.15-2.34,5.66Z\"/>"
} as const satisfies IconData;

export default boBxArrowOutUpRightStrokeCircle;
export { boBxArrowOutUpRightStrokeCircle };
export { boBxArrowOutUpRightStrokeCircle as boxiconsBxArrowOutUpRightStrokeCircle };
