// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxAlignLeft = {
	"name": "bx-align-left",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M3 7H15V9H3z\"/><path d=\"M3 3H21V5H3z\"/><path d=\"M3 11H21V13H3z\"/><path d=\"M3 15H15V17H3z\"/><path d=\"M3 19H21V21H3z\"/>"
} as const satisfies IconData;

export default boBxAlignLeft;
export { boBxAlignLeft };
export { boBxAlignLeft as boxiconsBxAlignLeft };
