// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxBriefcaseAlt2 = {
	"name": "bx-briefcase-alt-2",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M20 6h-3V4c0-1.1-.9-2-2-2H9c-1.1 0-2 .9-2 2v2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2M9 4h6v2H9zM8 8h12v3.07l-.83.39a16.78 16.78 0 0 1-14.34 0L4 11.07V8zM4 20v-6.72c2.54 1.19 5.27 1.79 8 1.79s5.46-.6 8-1.79V20z\"/>"
} as const satisfies IconData;

export default boBxBriefcaseAlt2;
export { boBxBriefcaseAlt2 };
export { boBxBriefcaseAlt2 as boxiconsBxBriefcaseAlt2 };
