// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxBookmarks = {
	"name": "bx-bookmarks",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M18 6h-8c-1.1 0-2 .9-2 2v13c0 .36.19.69.5.87s.69.17 1 0l4.49-2.66 4.49 2.66c.16.09.33.14.51.14s.34-.04.5-.13c.31-.18.5-.51.5-.87v-13c0-1.1-.9-2-2-2Zm0 8v5.25l-3.49-2.07a.98.98 0 0 0-1.02 0L10 19.25V8h8z\"/><path d=\"M16 2H6c-1.1 0-2 .9-2 2v14h2V4h10z\"/>"
} as const satisfies IconData;

export default boBxBookmarks;
export { boBxBookmarks };
export { boBxBookmarks as boxiconsBxBookmarks };
