// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxBackwardSlash = {
	"name": "bx-backward-slash",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M15.09 21.41 16 21 16.91 20.59 12.91 11.59 8.91 2.59 8 3 7.09 3.41 11.09 12.41 15.09 21.41z\"/>"
} as const satisfies IconData;

export default boBxBackwardSlash;
export { boBxBackwardSlash };
export { boBxBackwardSlash as boxiconsBxBackwardSlash };
