// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxBold = {
	"name": "bx-bold",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M13 4.5H7c-.83 0-1.5.67-1.5 1.5v12c0 .83.67 1.5 1.5 1.5h6.5c2.48 0 4.5-2.02 4.5-4.5 0-1.3-.56-2.46-1.44-3.28.58-.76.94-1.69.94-2.72 0-2.48-2.02-4.5-4.5-4.5m0 3c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5H8.5v-3zm.5 9h-5v-3h5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5\"/>"
} as const satisfies IconData;

export default boBxBold;
export { boBxBold };
export { boBxBold as boxiconsBxBold };
