// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxCapsule = {
	"name": "bx-capsule",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m15,5h-6c-3.86,0-7,3.14-7,7s3.14,7,7,7h6c3.86,0,7-3.14,7-7s-3.14-7-7-7Zm0,12h-6c-2.76,0-5-2.24-5-5s2.24-5,5-5h6c2.76,0,5,2.24,5,5s-2.24,5-5,5Z\"/>"
} as const satisfies IconData;

export default boBxCapsule;
export { boBxCapsule };
export { boBxCapsule as boxiconsBxCapsule };
