// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxCaretDown = {
	"name": "bx-caret-down",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M17.35 8H6.65c-.64 0-.99.76-.56 1.24l5.35 6.11c.3.34.83.34 1.13 0l5.35-6.11C18.34 8.76 18 8 17.36 8Z\"/>"
} as const satisfies IconData;

export default boBxCaretDown;
export { boBxCaretDown };
export { boBxCaretDown as boxiconsBxCaretDown };
