// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxChess = {
	"name": "bx-chess",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M21 2H3c-.55 0-1 .45-1 1v18c0 .55.45 1 1 1h18c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1m-1 6h-4v4h4v4h-4v4h-4v-4H8v4H4v-4h4v-4H4V8h4V4h4v4h4V4h4z\"/><path d=\"M8 8h4v4H8zM12 12h4v4h-4z\"/>"
} as const satisfies IconData;

export default boBxChess;
export { boBxChess };
export { boBxChess as boxiconsBxChess };
