// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxCopyMinus = {
	"name": "bx-copy-minus",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M20 2H10c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h10c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2m0 12H10V4h10z\"/><path d=\"M4 22h10c1.1 0 2-.9 2-2v-2h-2v2H4V10h2V8H4c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2M12 8h6v2h-6z\"/>"
} as const satisfies IconData;

export default boBxCopyMinus;
export { boBxCopyMinus };
export { boBxCopyMinus as boxiconsBxCopyMinus };
