// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxCaretsLeftRight = {
	"name": "bx-carets-left-right",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M10 17.35V6.65c0-.64-.76-.99-1.24-.56l-6.11 5.35c-.34.3-.34.83 0 1.13l6.11 5.35c.48.42 1.24.08 1.24-.56ZM15.24 6.09c-.48-.42-1.24-.08-1.24.56v10.69c0 .64.76.99 1.24.56l6.11-5.35c.34-.3.34-.83 0-1.13l-6.11-5.35Z\"/>"
} as const satisfies IconData;

export default boBxCaretsLeftRight;
export { boBxCaretsLeftRight };
export { boBxCaretsLeftRight as boxiconsBxCaretsLeftRight };
