// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxDice1 = {
	"name": "bx-dice-1",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M5 21h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2M5 5h14v14H5z\"/><path d=\"M12 10.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 1 0 0-3\"/>"
} as const satisfies IconData;

export default boBxDice1;
export { boBxDice1 };
export { boBxDice1 as boxiconsBxDice1 };
