// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxDisc = {
	"name": "bx-disc",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2\"/><path d=\"M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10 10-4.49 10-10S17.51 2 12 2m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8\"/><path d=\"M12 6c-3.31 0-6 2.69-6 6h2c0-2.21 1.79-4 4-4z\"/>"
} as const satisfies IconData;

export default boBxDisc;
export { boBxDisc };
export { boBxDisc as boxiconsBxDisc };
