// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxDiameter = {
	"name": "bx-diameter",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m12,2C6.49,2,2,6.49,2,12s4.49,10,10,10,10-4.49,10-10S17.51,2,12,2Zm0,18c-4.41,0-8-3.59-8-8S7.59,4,12,4s8,3.59,8,8-3.59,8-8,8Z\"/><path d=\"M13.29 9.29 9.29 13.29 8 12 8 16 12 16 10.71 14.71 14.71 10.71 16 12 16 8 12 8 13.29 9.29z\"/>"
} as const satisfies IconData;

export default boBxDiameter;
export { boBxDiameter };
export { boBxDiameter as boxiconsBxDiameter };
