// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxEyeClosed = {
	"name": "bx-eye-closed",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m21.95 12.32-1.9-.64C19.98 11.9 18.16 17 12 17s-7.98-5.1-8.05-5.32l-1.9.63s.28.8.93 1.81L.7 15.85l1.21 1.6 2.3-1.74c.58.62 1.29 1.24 2.16 1.77l-1.51 2.48L6.57 21l1.62-2.65c.83.3 1.78.5 2.82.59v3.05h2v-3.05c1.05-.08 1.99-.29 2.82-.59L17.45 21l1.71-1.04-1.51-2.48c.87-.53 1.58-1.15 2.16-1.77l2.3 1.74 1.21-1.6-2.28-1.73c.65-1.01.92-1.79.93-1.81Z\"/>"
} as const satisfies IconData;

export default boBxEyeClosed;
export { boBxEyeClosed };
export { boBxEyeClosed as boxiconsBxEyeClosed };
