// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxFoodTag = {
	"name": "bx-food-tag",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2M5 19V5h14v14z\"/><path d=\"M12 7a5 5 0 1 0 0 10 5 5 0 1 0 0-10\"/>"
} as const satisfies IconData;

export default boBxFoodTag;
export { boBxFoodTag };
export { boBxFoodTag as boxiconsBxFoodTag };
