// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxFork = {
	"name": "bx-fork",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m15,12.59l-1.09-1.09,5.29-5.29-1.41-1.41-5.29,5.29-1.09-1.09,5.29-5.29-1.41-1.41-6.59,6.59c-.57.57-.88,1.32-.88,2.12s.31,1.55.88,2.12l.38.38-6.79,6.79,1.41,1.41,6.79-6.79.38.38c.57.57,1.32.88,2.12.88s1.55-.31,2.12-.88l6.59-6.59-1.41-1.41-5.29,5.29Z\"/>"
} as const satisfies IconData;

export default boBxFork;
export { boBxFork };
export { boBxFork as boxiconsBxFork };
