// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxForwardSlashSquare = {
	"name": "bx-forward-slash-square",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M13.07 6.63 11.07 11.63 9.07 16.63 10 17 10.93 17.37 12.93 12.37 14.93 7.37 14 7 13.07 6.63z\"/><path d=\"m19,3H5c-1.1,0-2,.9-2,2v14c0,1.1.9,2,2,2h14c1.1,0,2-.9,2-2V5c0-1.1-.9-2-2-2ZM5,19V5h14v14s-14,0-14,0Z\"/>"
} as const satisfies IconData;

export default boBxForwardSlashSquare;
export { boBxForwardSlashSquare };
export { boBxForwardSlashSquare as boxiconsBxForwardSlashSquare };
