// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxHorizontalCenter = {
	"name": "bx-horizontal-center",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M5 16 9 12 5 8 5 11 2 11 2 13 5 13 5 16z\"/><path d=\"M19 11 19 8 15 12 19 16 19 13 19.62 13 22 13 22 11 19.62 11 19 11z\"/><path d=\"M11 3H13V6H11z\"/><path d=\"M11 8H13V11H11z\"/><path d=\"M11 13H13V16H11z\"/><path d=\"M11 18H13V21H11z\"/>"
} as const satisfies IconData;

export default boBxHorizontalCenter;
export { boBxHorizontalCenter };
export { boBxHorizontalCenter as boxiconsBxHorizontalCenter };
