// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxHdmi = {
	"name": "bx-hdmi",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M6 11h12v2H6z\"/><path d=\"M2 8v8c0 .55.45 1 1 1h2.59l1.71 1.71c.19.19.44.29.71.29h8c.27 0 .52-.11.71-.29L18.43 17h2.59c.55 0 1-.45 1-1V8c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1m2 1h16v6h-2c-.27 0-.52.11-.71.29L15.58 17H8.41L6.7 15.29a1 1 0 0 0-.71-.29h-2V9Z\"/>"
} as const satisfies IconData;

export default boBxHdmi;
export { boBxHdmi };
export { boBxHdmi as boxiconsBxHdmi };
