// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxHomeAlt3 = {
	"name": "bx-home-alt-3",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m21.55,8.17L12.55,2.17c-.34-.22-.77-.22-1.11,0L2.45,8.17c-.28.19-.45.5-.45.83v11c0,1.1.9,2,2,2h16c1.1,0,2-.9,2-2v-11c0-.33-.17-.65-.45-.83ZM4,20v-10.46l8-5.33,8,5.33v10.46s-16,0-16,0Z\"/><path d=\"M6 16H18V18H6z\"/>"
} as const satisfies IconData;

export default boBxHomeAlt3;
export { boBxHomeAlt3 };
export { boBxHomeAlt3 as boxiconsBxHomeAlt3 };
