// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const boBxHorizontalLeft = {
	"name": "bx-horizontal-left",
	"set": "boxicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M11 8 7 12 11 16 11 13 16 13 16 11 11 11 11 8z\"/><path d=\"M3 18H5V21H3z\"/><path d=\"M3 13H5V16H3z\"/><path d=\"M3 8H5V11H3z\"/><path d=\"M3 3H5V6H3z\"/>"
} as const satisfies IconData;

export default boBxHorizontalLeft;
export { boBxHorizontalLeft };
export { boBxHorizontalLeft as boxiconsBxHorizontalLeft };
