// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocArrowUpLeft24 = {
	"name": "arrow-up-left-24",
	"set": "octicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M5.75 15.5a.75.75 0 0 1-.75-.75v-9A.75.75 0 0 1 5.75 5h9a.75.75 0 0 1 0 1.5H7.56l10.22 10.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L6.5 7.56v7.19a.75.75 0 0 1-.75.75Z\"/>"
} as const satisfies IconData;

export default ocArrowUpLeft24;
export { ocArrowUpLeft24 };
export { ocArrowUpLeft24 as octiconsArrowUpLeft24 };
