// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocArrowUp16 = {
	"name": "arrow-up-16",
	"set": "octicons",
	"viewBox": "0 0 16 16",
	"body": "<path d=\"M3.47 7.78a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0l4.25 4.25a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018L9 4.81v7.44a.75.75 0 0 1-1.5 0V4.81L4.53 7.78a.75.75 0 0 1-1.06 0Z\"/>"
} as const satisfies IconData;

export default ocArrowUp16;
export { ocArrowUp16 };
export { ocArrowUp16 as octiconsArrowUp16 };
