// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocChevronDown12 = {
	"name": "chevron-down-12",
	"set": "octicons",
	"viewBox": "0 0 12 12",
	"body": "<path d=\"M6 8.825c-.2 0-.4-.1-.5-.2l-3.3-3.3c-.3-.3-.3-.8 0-1.1.3-.3.8-.3 1.1 0l2.7 2.7 2.7-2.7c.3-.3.8-.3 1.1 0 .3.3.3.8 0 1.1l-3.2 3.2c-.2.2-.4.3-.6.3Z\"/>"
} as const satisfies IconData;

export default ocChevronDown12;
export { ocChevronDown12 };
export { ocChevronDown12 as octiconsChevronDown12 };
