// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocDash16 = {
	"name": "dash-16",
	"set": "octicons",
	"viewBox": "0 0 16 16",
	"body": "<path d=\"M2 7.75A.75.75 0 0 1 2.75 7h10a.75.75 0 0 1 0 1.5h-10A.75.75 0 0 1 2 7.75Z\"/>"
} as const satisfies IconData;

export default ocDash16;
export { ocDash16 };
export { ocDash16 as octiconsDash16 };
