// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocDotFill24 = {
	"name": "dot-fill-24",
	"set": "octicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 18a6 6 0 1 0 0-12 6 6 0 0 0 0 12Z\"/>"
} as const satisfies IconData;

export default ocDotFill24;
export { ocDotFill24 };
export { ocDotFill24 as octiconsDotFill24 };
