// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocGitMergeQueue16 = {
	"name": "git-merge-queue-16",
	"set": "octicons",
	"viewBox": "0 0 16 16",
	"body": "<path d=\"M3.75 4.5a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5ZM3 7.75a.75.75 0 0 1 1.5 0v2.878a2.251 2.251 0 1 1-1.5 0Zm.75 5.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm5-7.75a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0Zm5.75 2.5a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-1.5 0a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z\"/>"
} as const satisfies IconData;

export default ocGitMergeQueue16;
export { ocGitMergeQueue16 };
export { ocGitMergeQueue16 as octiconsGitMergeQueue16 };
