// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocGitCommit16 = {
	"name": "git-commit-16",
	"set": "octicons",
	"viewBox": "0 0 16 16",
	"body": "<path d=\"M11.93 8.5a4.002 4.002 0 0 1-7.86 0H.75a.75.75 0 0 1 0-1.5h3.32a4.002 4.002 0 0 1 7.86 0h3.32a.75.75 0 0 1 0 1.5Zm-1.43-.75a2.5 2.5 0 1 0-5 0 2.5 2.5 0 0 0 5 0Z\"/>"
} as const satisfies IconData;

export default ocGitCommit16;
export { ocGitCommit16 };
export { ocGitCommit16 as octiconsGitCommit16 };
