// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocSearch24 = {
	"name": "search-24",
	"set": "octicons",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M10.25 2a8.25 8.25 0 0 1 6.34 13.53l5.69 5.69a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-5.69-5.69A8.25 8.25 0 1 1 10.25 2ZM3.5 10.25a6.75 6.75 0 1 0 13.5 0 6.75 6.75 0 0 0-13.5 0Z\"/>"
} as const satisfies IconData;

export default ocSearch24;
export { ocSearch24 };
export { ocSearch24 as octiconsSearch24 };
