// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ocX12 = {
	"name": "x-12",
	"set": "octicons",
	"viewBox": "0 0 12 12",
	"body": "<path d=\"M2.22 2.22a.749.749 0 0 1 1.06 0L6 4.939 8.72 2.22a.749.749 0 1 1 1.06 1.06L7.061 6 9.78 8.72a.749.749 0 1 1-1.06 1.06L6 7.061 3.28 9.78a.749.749 0 1 1-1.06-1.06L4.939 6 2.22 3.28a.749.749 0 0 1 0-1.06Z\"/>"
} as const satisfies IconData;

export default ocX12;
export { ocX12 };
export { ocX12 as octiconsX12 };
