// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phDeviceTabletCamera = {
	"name": "device-tablet-camera",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<rect x=\"32\" y=\"48\" width=\"192\" height=\"160\" rx=\"16\" transform=\"translate(256) rotate(90)\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"68\" r=\"12\"/>"
} as const satisfies IconData;

export default phDeviceTabletCamera;
export { phDeviceTabletCamera };
export { phDeviceTabletCamera as phosphorDeviceTabletCamera };
