// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phHardDrive = {
	"name": "hard-drive",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<rect x=\"24\" y=\"72\" width=\"208\" height=\"112\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"188\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phHardDrive;
export { phHardDrive };
export { phHardDrive as phosphorHardDrive };
