// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxAlignLeft = {
	"name": "align-left",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M4 19h16v2H4zm0-4h11v2H4zm0-4h16v2H4zm0-8h16v2H4zm0 4h11v2H4z\"/>"
} as const satisfies IconData;

export default bxAlignLeft;
export { bxAlignLeft };
export { bxAlignLeft as boxregularAlignLeft };
