// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxCaretDown = {
	"name": "caret-down",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m11.998 17 7-8h-14z\"/>"
} as const satisfies IconData;

export default bxCaretDown;
export { bxCaretDown };
export { bxCaretDown as boxregularCaretDown };
