// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxCheckboxSquare = {
	"name": "checkbox-square",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M9 9h6v6H9z\"/><path d=\"M19 17V7c0-1.103-.897-2-2-2H7c-1.103 0-2 .897-2 2v10c0 1.103.897 2 2 2h10c1.103 0 2-.897 2-2zM7 7h10l.002 10H7V7z\"/>"
} as const satisfies IconData;

export default bxCheckboxSquare;
export { bxCheckboxSquare };
export { bxCheckboxSquare as boxregularCheckboxSquare };
