// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxChevronsRight = {
	"name": "chevrons-right",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M10.296 7.71 14.621 12l-4.325 4.29 1.408 1.42L17.461 12l-5.757-5.71z\"/><path d=\"M6.704 6.29 5.296 7.71 9.621 12l-4.325 4.29 1.408 1.42L12.461 12z\"/>"
} as const satisfies IconData;

export default bxChevronsRight;
export { bxChevronsRight };
export { bxChevronsRight as boxregularChevronsRight };
