// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxChevronDown = {
	"name": "chevron-down",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M16.293 9.293 12 13.586 7.707 9.293l-1.414 1.414L12 16.414l5.707-5.707z\"/>"
} as const satisfies IconData;

export default bxChevronDown;
export { bxChevronDown };
export { bxChevronDown as boxregularChevronDown };
