// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxExclude = {
	"name": "exclude",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M19 8h-3V5c0-1.103-.897-2-2-2H5c-1.103 0-2 .897-2 2v9c0 1.103.897 2 2 2h3v3c0 1.103.897 2 2 2h9c1.103 0 2-.897 2-2v-9c0-1.103-.897-2-2-2zm-4 7H9V9h6v6z\"/>"
} as const satisfies IconData;

export default bxExclude;
export { bxExclude };
export { bxExclude as boxregularExclude };
