// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxLogIn = {
	"name": "log-in",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"m13 16 5-4-5-4v3H4v2h9z\"/><path d=\"M20 3h-9c-1.103 0-2 .897-2 2v4h2V5h9v14h-9v-4H9v4c0 1.103.897 2 2 2h9c1.103 0 2-.897 2-2V5c0-1.103-.897-2-2-2z\"/>"
} as const satisfies IconData;

export default bxLogIn;
export { bxLogIn };
export { bxLogIn as boxregularLogIn };
