// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxMinusBack = {
	"name": "minus-back",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M14 3H5c-1.103 0-2 .897-2 2v9c0 1.103.897 2 2 2h3v3c0 1.103.897 2 2 2h9c1.103 0 2-.897 2-2v-9c0-1.103-.897-2-2-2h-3V5c0-1.103-.897-2-2-2zM5 5h9l-.003 9H5V5z\"/>"
} as const satisfies IconData;

export default bxMinusBack;
export { bxMinusBack };
export { bxMinusBack as boxregularMinusBack };
