// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxRedo = {
	"name": "redo",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M9 18h3v-2H9c-1.654 0-3-1.346-3-3s1.346-3 3-3h6v3l5-4-5-4v3H9c-2.757 0-5 2.243-5 5s2.243 5 5 5z\"/>"
} as const satisfies IconData;

export default bxRedo;
export { bxRedo };
export { bxRedo as boxregularRedo };
