// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxReplyAll = {
	"name": "reply-all",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M20 18v-8a1 1 0 0 0-1-1h-6V6l-5 4 5 4v-3h5v7h2z\"/><path d=\"M9 12.4 6 10l3-2.4V6l-5 4 5 4z\"/>"
} as const satisfies IconData;

export default bxReplyAll;
export { bxReplyAll };
export { bxReplyAll as boxregularReplyAll };
