// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxYen = {
	"name": "yen",
	"set": "boxregular",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M17.2 3.4 12 10.333 6.8 3.4 5.2 4.6 10 11H7v2h4v2H7v2h4v4h2v-4h4v-2h-4v-2h4v-2h-3l4.8-6.4z\"/>"
} as const satisfies IconData;

export default bxYen;
export { bxYen };
export { bxYen as boxregularYen };
