// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsArrowToRight = {
	"name": "arrow-to-right",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M18 6h2v12h-2zm-8 5H4v2h6v5l6-6-6-6z\"/>"
} as const satisfies IconData;

export default bxsArrowToRight;
export { bxsArrowToRight };
export { bxsArrowToRight as boxsolidArrowToRight };
