// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsBoltCircle = {
	"name": "bolt-circle",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.514 2 12 2zm-1 16v-5H7l6-7v5h4l-6 7z\"/>"
} as const satisfies IconData;

export default bxsBoltCircle;
export { bxsBoltCircle };
export { bxsBoltCircle as boxsolidBoltCircle };
