// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsCaretLeftCircle = {
	"name": "caret-left-circle",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.514 2 12 2zm2 15-6-5 6-5v10z\"/>"
} as const satisfies IconData;

export default bxsCaretLeftCircle;
export { bxsCaretLeftCircle };
export { bxsCaretLeftCircle as boxsolidCaretLeftCircle };
