// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsCoinStack = {
	"name": "coin-stack",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 10c3.976 0 8-1.374 8-4s-4.024-4-8-4-8 1.374-8 4 4.024 4 8 4z\"/><path d=\"M4 10c0 2.626 4.024 4 8 4s8-1.374 8-4V8c0 2.626-4.024 4-8 4s-8-1.374-8-4v2z\"/><path d=\"M4 14c0 2.626 4.024 4 8 4s8-1.374 8-4v-2c0 2.626-4.024 4-8 4s-8-1.374-8-4v2z\"/><path d=\"M4 18c0 2.626 4.024 4 8 4s8-1.374 8-4v-2c0 2.626-4.024 4-8 4s-8-1.374-8-4v2z\"/>"
} as const satisfies IconData;

export default bxsCoinStack;
export { bxsCoinStack };
export { bxsCoinStack as boxsolidCoinStack };
