// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsCommentX = {
	"name": "comment-x",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M20 2H4c-1.103 0-2 .897-2 2v18l4-4h14c1.103 0 2-.897 2-2V4c0-1.103-.897-2-2-2zm-3.294 11.543-1.414 1.414-3.293-3.292-3.292 3.292-1.414-1.414 3.292-3.292-3.292-3.293 1.414-1.414 3.292 3.292 3.293-3.292 1.414 1.414-3.292 3.293 3.292 3.292z\"/>"
} as const satisfies IconData;

export default bxsCommentX;
export { bxsCommentX };
export { bxsCommentX as boxsolidCommentX };
