// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsFoodMenu = {
	"name": "food-menu",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M3 2h2v20H3zm16 0H6v20h13c1.103 0 2-.897 2-2V4c0-1.103-.897-2-2-2zm-1 10H9v-2h9v2zm0-4H9V6h9v2z\"/>"
} as const satisfies IconData;

export default bxsFoodMenu;
export { bxsFoodMenu };
export { bxsFoodMenu as boxsolidFoodMenu };
