// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsMessageSquareMinus = {
	"name": "message-square-minus",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M16 2H8C4.691 2 2 4.691 2 8v13a1 1 0 0 0 1 1h13c3.309 0 6-2.691 6-6V8c0-3.309-2.691-6-6-6zm0 11H8v-2h8v2z\"/>"
} as const satisfies IconData;

export default bxsMessageSquareMinus;
export { bxsMessageSquareMinus };
export { bxsMessageSquareMinus as boxsolidMessageSquareMinus };
