// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const bxsUpArrowAlt = {
	"name": "up-arrow-alt",
	"set": "boxsolid",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M13 18v-6h5l-6-7-6 7h5v6z\"/>"
} as const satisfies IconData;

export default bxsUpArrowAlt;
export { bxsUpArrowAlt };
export { bxsUpArrowAlt as boxsolidUpArrowAlt };
