// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const heArrowRightCircle = {
	"name": "arrow-right-circle",
	"set": "heroicons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M12.75 15L15.75 12M15.75 12L12.75 9M15.75 12L8.25 12M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default heArrowRightCircle;
export { heArrowRightCircle };
export { heArrowRightCircle as heroiconsArrowRightCircle };
