// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const heArrowUpTray = {
	"name": "arrow-up-tray",
	"set": "heroicons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M3 16.5V18.75C3 19.9926 4.00736 21 5.25 21H18.75C19.9926 21 21 19.9926 21 18.75V16.5M7.5 7.5L12 3M12 3L16.5 7.5M12 3L12 16.5\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default heArrowUpTray;
export { heArrowUpTray };
export { heArrowUpTray as heroiconsArrowUpTray };
