// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const heBarsArrowDown = {
	"name": "bars-arrow-down",
	"set": "heroicons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M3 4.5H17.25M3 9H12.75M3 13.5H12.75M17.25 9V21M17.25 21L13.5 17.25M17.25 21L21 17.25\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default heBarsArrowDown;
export { heBarsArrowDown };
export { heBarsArrowDown as heroiconsBarsArrowDown };
