// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const heBoltSlash = {
	"name": "bolt-slash",
	"set": "heroicons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M11.4123 15.6549L9.75 21.75L13.4949 17.7376M9.25736 13.5H3.75L6.40873 10.6514M8.4569 8.4569L14.25 2.25L12 10.5H20.25L15.5431 15.5431M8.4569 8.4569L3 3M8.4569 8.4569L15.5431 15.5431M15.5431 15.5431L21 21\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default heBoltSlash;
export { heBoltSlash };
export { heBoltSlash as heroiconsBoltSlash };
