// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const heHashtag = {
	"name": "hashtag",
	"set": "heroicons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M5.25 8.25H20.25M3.75 15.75H18.75M16.95 2.25L13.05 21.75M10.9503 2.25L7.05029 21.75\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>"
} as const satisfies IconData;

export default heHashtag;
export { heHashtag };
export { heHashtag as heroiconsHashtag };
