// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faGaugeSimpleHigh = {
	"name": "gauge-simple-high",
	"set": "fontawesome",
	"viewBox": "0 0 512 512",
	"body": "<path fill=\"currentColor\" d=\"M0 256a256 256 0 1 1 512 0 256 256 0 1 1 -512 0zm320 96c0-16.2-6-31.1-16-42.3l69.5-138.9c5.9-11.9 1.1-26.3-10.7-32.2s-26.3-1.1-32.2 10.7L261.1 288.2c-1.7-.1-3.4-.2-5.1-.2-35.3 0-64 28.7-64 64s28.7 64 64 64 64-28.7 64-64z\"/>"
} as const satisfies IconData;

export default faGaugeSimpleHigh;
export { faGaugeSimpleHigh };
export { faGaugeSimpleHigh as fontawesomeGaugeSimpleHigh };
