// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faArrowRedoOutline = {
	"name": "arrow-redo-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M448,256,272,88v96C103.57,184,64,304.77,64,424c48.61-62.24,91.6-96,208-96v96Z\" style=\"fill:none;stroke:currentColor;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faArrowRedoOutline;
export { faArrowRedoOutline };
export { faArrowRedoOutline as famiconsArrowRedoOutline };
