// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faBagHandleOutline = {
	"name": "bag-handle-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M80,176a16,16,0,0,0-16,16V408c0,30.24,25.76,56,56,56H392c30.24,0,56-24.51,56-54.75V192a16,16,0,0,0-16-16Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"32\"/><path d=\"M160,176V144a96,96,0,0,1,96-96h0a96,96,0,0,1,96,96v32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"32\"/><path d=\"M160,224v16a96,96,0,0,0,96,96h0a96,96,0,0,0,96-96V224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"32\"/>"
} as const satisfies IconData;

export default faBagHandleOutline;
export { faBagHandleOutline };
export { faBagHandleOutline as famiconsBagHandleOutline };
