// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faBanOutline = {
	"name": "ban-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<circle cx=\"256\" cy=\"256\" r=\"208\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"32\"/><line x1=\"108.92\" y1=\"108.92\" x2=\"403.08\" y2=\"403.08\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"32\"/>"
} as const satisfies IconData;

export default faBanOutline;
export { faBanOutline };
export { faBanOutline as famiconsBanOutline };
