// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faBarbellOutline = {
	"name": "barbell-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<line x1=\"48\" y1=\"256\" x2=\"464\" y2=\"256\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><rect x=\"384\" y=\"128\" width=\"32\" height=\"256\" rx=\"16\" ry=\"16\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><rect x=\"96\" y=\"128\" width=\"32\" height=\"256\" rx=\"16\" ry=\"16\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><rect x=\"32\" y=\"192\" width=\"16\" height=\"128\" rx=\"8\" ry=\"8\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><rect x=\"464\" y=\"192\" width=\"16\" height=\"128\" rx=\"8\" ry=\"8\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faBarbellOutline;
export { faBarbellOutline };
export { faBarbellOutline as famiconsBarbellOutline };
