// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faBookmarkSharp = {
	"name": "bookmark-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M416,480,256,357.41,96,480V32H416Z\"/>"
} as const satisfies IconData;

export default faBookmarkSharp;
export { faBookmarkSharp };
export { faBookmarkSharp as famiconsBookmarkSharp };
