// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faBowlingBall = {
	"name": "bowling-ball",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M414.39,97.61A224,224,0,1,0,97.61,414.39,224,224,0,1,0,414.39,97.61ZM288,224a24,24,0,1,1,24-24A24,24,0,0,1,288,224Zm8-72a24,24,0,1,1,24-24A24,24,0,0,1,296,152Zm64,40a24,24,0,1,1,24-24A24,24,0,0,1,360,192Z\"/>"
} as const satisfies IconData;

export default faBowlingBall;
export { faBowlingBall };
export { faBowlingBall as famiconsBowlingBall };
