// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faCaretUpSharp = {
	"name": "caret-up-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<polygon points=\"448 368 256 144 64 368 448 368\"/>"
} as const satisfies IconData;

export default faCaretUpSharp;
export { faCaretUpSharp };
export { faCaretUpSharp as famiconsCaretUpSharp };
