// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faChevronUpSharp = {
	"name": "chevron-up-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<polyline points=\"112 328 256 184 400 328\" style=\"fill:none;stroke:currentColor;stroke-linecap:square;stroke-miterlimit:10;stroke-width:48px\"/>"
} as const satisfies IconData;

export default faChevronUpSharp;
export { faChevronUpSharp };
export { faChevronUpSharp as famiconsChevronUpSharp };
