// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faClipboardSharp = {
	"name": "clipboard-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M420,48H352V28a12,12,0,0,0-12-12H172a12,12,0,0,0-12,12V48H92A12,12,0,0,0,80,60V484a12,12,0,0,0,12,12H420a12,12,0,0,0,12-12V60A12,12,0,0,0,420,48Zm-84.13,64H176.13V80H335.87Z\"/>"
} as const satisfies IconData;

export default faClipboardSharp;
export { faClipboardSharp };
export { faClipboardSharp as famiconsClipboardSharp };
