// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faContrastOutline = {
	"name": "contrast-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<circle cx=\"256\" cy=\"256\" r=\"208\" style=\"fill:none;stroke:currentColor;stroke-linejoin:round;stroke-width:32px\"/><path d=\"M256,464C141.12,464,48,370.88,48,256S141.12,48,256,48Z\"/>"
} as const satisfies IconData;

export default faContrastOutline;
export { faContrastOutline };
export { faContrastOutline as famiconsContrastOutline };
