// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faFilterOutline = {
	"name": "filter-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<line x1=\"32\" y1=\"144\" x2=\"480\" y2=\"144\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><line x1=\"112\" y1=\"256\" x2=\"400\" y2=\"256\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><line x1=\"208\" y1=\"368\" x2=\"304\" y2=\"368\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faFilterOutline;
export { faFilterOutline };
export { faFilterOutline as famiconsFilterOutline };
