// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faGlassesSharp = {
	"name": "glasses-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M496,176H16v64H37.24L49.68,352H221.55L240,241.32V240a16,16,0,0,1,32,0v1.32L290.45,352H462.32l12.44-112H496Z\"/>"
} as const satisfies IconData;

export default faGlassesSharp;
export { faGlassesSharp };
export { faGlassesSharp as famiconsGlassesSharp };
