// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faIdCardSharp = {
	"name": "id-card-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M408,16H104A24,24,0,0,0,80,40V472a24,24,0,0,0,24,24H408a24,24,0,0,0,24-24V40A24,24,0,0,0,408,16ZM346.9,312.77a43,43,0,1,1-40.71-40.71A43,43,0,0,1,346.9,312.77ZM192,64H320V96H192ZM384,448H224V423.4c0-32.72,53.27-49.21,80-49.21s80,16.49,80,49.21Z\"/>"
} as const satisfies IconData;

export default faIdCardSharp;
export { faIdCardSharp };
export { faIdCardSharp as famiconsIdCardSharp };
