// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faKeypadOutline = {
	"name": "keypad-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<circle cx=\"256\" cy=\"448\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"256\" cy=\"320\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><path d=\"M288,192a32,32,0,1,1-32-32A32,32,0,0,1,288,192Z\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"256\" cy=\"64\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"384\" cy=\"320\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"384\" cy=\"192\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"384\" cy=\"64\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"128\" cy=\"320\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"128\" cy=\"192\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/><circle cx=\"128\" cy=\"64\" r=\"32\" style=\"fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faKeypadOutline;
export { faKeypadOutline };
export { faKeypadOutline as famiconsKeypadOutline };
