// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faNavigateSharp = {
	"name": "navigate-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<polygon points=\"480 32 32 240 272 240 272 480 480 32\"/>"
} as const satisfies IconData;

export default faNavigateSharp;
export { faNavigateSharp };
export { faNavigateSharp as famiconsNavigateSharp };
