// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faPauseOutline = {
	"name": "pause-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<rect x=\"176\" y=\"96\" width=\"16\" height=\"320\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><rect x=\"320\" y=\"96\" width=\"16\" height=\"320\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faPauseOutline;
export { faPauseOutline };
export { faPauseOutline as famiconsPauseOutline };
