// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faReorderFourOutline = {
	"name": "reorder-four-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<line x1=\"96\" y1=\"304\" x2=\"416\" y2=\"304\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><line x1=\"96\" y1=\"208\" x2=\"416\" y2=\"208\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><line x1=\"96\" y1=\"112\" x2=\"416\" y2=\"112\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><line x1=\"96\" y1=\"400\" x2=\"416\" y2=\"400\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faReorderFourOutline;
export { faReorderFourOutline };
export { faReorderFourOutline as famiconsReorderFourOutline };
