// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faRibbonOutline = {
	"name": "ribbon-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<circle cx=\"256\" cy=\"160\" r=\"128\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><path d=\"M143.65,227.82,48,400l86.86-.42a16,16,0,0,1,13.82,7.8L192,480l88.33-194.32\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><path d=\"M366.54,224,464,400l-86.86-.42a16,16,0,0,0-13.82,7.8L320,480,256,339.2\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/><circle cx=\"256\" cy=\"160\" r=\"64\" style=\"fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faRibbonOutline;
export { faRibbonOutline };
export { faRibbonOutline as famiconsRibbonOutline };
