// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faStop = {
	"name": "stop",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M392,432H120a40,40,0,0,1-40-40V120a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V392A40,40,0,0,1,392,432Z\"/>"
} as const satisfies IconData;

export default faStop;
export { faStop };
export { faStop as famiconsStop };
