// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faTvSharp = {
	"name": "tv-sharp",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<path d=\"M488,384H24a8,8,0,0,1-8-8V88a8,8,0,0,1,8-8H488a8,8,0,0,1,8,8V376A8,8,0,0,1,488,384Z\"/><rect x=\"112\" y=\"400\" width=\"288\" height=\"32\" rx=\"4\" ry=\"4\"/>"
} as const satisfies IconData;

export default faTvSharp;
export { faTvSharp };
export { faTvSharp as famiconsTvSharp };
