// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const faWatchOutline = {
	"name": "watch-outline",
	"set": "famicons",
	"viewBox": "0 0 512 512",
	"body": "<rect x=\"112\" y=\"112\" width=\"288\" height=\"288\" rx=\"64\" ry=\"64\" style=\"fill:none;stroke:currentColor;stroke-linejoin:round;stroke-width:32px\"/><path d=\"M176,112V40a8,8,0,0,1,8-8H328a8,8,0,0,1,8,8v72\" style=\"fill:none;stroke:currentColor;stroke-linejoin:round;stroke-width:32px\"/><path d=\"M336,400v72a8,8,0,0,1-8,8H184a8,8,0,0,1-8-8V400\" style=\"fill:none;stroke:currentColor;stroke-linejoin:round;stroke-width:32px\"/>"
} as const satisfies IconData;

export default faWatchOutline;
export { faWatchOutline };
export { faWatchOutline as famiconsWatchOutline };
