// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refArrowUpSFill = {
	"name": "arrow-up-s-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M12 8L18 14H6L12 8Z\"/></g>"
} as const satisfies IconData;

export default refArrowUpSFill;
export { refArrowUpSFill };
export { refArrowUpSFill as remixfillArrowUpSFill };
