// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refBarChartGroupedFill = {
	"name": "bar-chart-grouped-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M2 12H4V21H2V12ZM5 14H7V21H5V14ZM16 8H18V21H16V8ZM19 10H21V21H19V10ZM9 2H11V21H9V2ZM12 4H14V21H12V4Z\"/></g>"
} as const satisfies IconData;

export default refBarChartGroupedFill;
export { refBarChartGroupedFill };
export { refBarChartGroupedFill as remixfillBarChartGroupedFill };
