// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refChat2Fill = {
	"name": "chat-2-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M14.45 19L12 22.5L9.55 19H3C2.44772 19 2 18.5523 2 18V4C2 3.44772 2.44772 3 3 3H21C21.5523 3 22 3.44772 22 4V18C22 18.5523 21.5523 19 21 19H14.45Z\"/></g>"
} as const satisfies IconData;

export default refChat2Fill;
export { refChat2Fill };
export { refChat2Fill as remixfillChat2Fill };
