// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refCornerUpRightFill = {
	"name": "corner-up-right-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M4.99989 10.0001L4.99976 19L6.99976 19L6.99986 12.0001L14.5859 12V17.4142L21.0001 11L14.5859 4.58578L14.5859 10L4.99989 10.0001Z\"/></g>"
} as const satisfies IconData;

export default refCornerUpRightFill;
export { refCornerUpRightFill };
export { refCornerUpRightFill as remixfillCornerUpRightFill };
