// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refFilter2Fill = {
	"name": "filter-2-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M10 14L4 5V3H20V5L14 14V20L10 22V14Z\"/></g>"
} as const satisfies IconData;

export default refFilter2Fill;
export { refFilter2Fill };
export { refFilter2Fill as remixfillFilter2Fill };
