// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refHonourFill = {
	"name": "honour-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M21 4V18.7215C21 18.9193 20.8833 19.0986 20.7024 19.1787L12 23.0313L3.29759 19.1787C3.11667 19.0986 3 18.9193 3 18.7215V4H1V2H23V4H21ZM8 12V14H16V12H8ZM8 8V10H16V8H8Z\"/></g>"
} as const satisfies IconData;

export default refHonourFill;
export { refHonourFill };
export { refHonourFill as remixfillHonourFill };
