// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const refSubtractFill = {
	"name": "subtract-fill",
	"set": "remixfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M19 11H5V13H19V11Z\"/></g>"
} as const satisfies IconData;

export default refSubtractFill;
export { refSubtractFill };
export { refSubtractFill as remixfillSubtractFill };
