// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luBadgeSwissFranc = {
	"name": "badge-swiss-franc",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" />\n  <path d=\"M11 17V8h4\" />\n  <path d=\"M11 12h3\" />\n  <path d=\"M9 16h4\" /></g>"
} as const satisfies IconData;

export default luBadgeSwissFranc;
export { luBadgeSwissFranc };
export { luBadgeSwissFranc as lucideBadgeSwissFranc };
