// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luChartBar = {
	"name": "chart-bar",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <path d=\"M7 16h8\" />\n  <path d=\"M7 11h12\" />\n  <path d=\"M7 6h3\" /></g>"
} as const satisfies IconData;

export default luChartBar;
export { luChartBar };
export { luChartBar as lucideChartBar };
