// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luChartNetwork = {
	"name": "chart-network",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m13.11 7.664 1.78 2.672\" />\n  <path d=\"m14.162 12.788-3.324 1.424\" />\n  <path d=\"m20 4-6.06 1.515\" />\n  <path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <circle cx=\"12\" cy=\"6\" r=\"2\" />\n  <circle cx=\"16\" cy=\"12\" r=\"2\" />\n  <circle cx=\"9\" cy=\"15\" r=\"2\" /></g>"
} as const satisfies IconData;

export default luChartNetwork;
export { luChartNetwork };
export { luChartNetwork as lucideChartNetwork };
