// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luCircleArrowOutUpRight = {
	"name": "circle-arrow-out-up-right",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 12A10 10 0 1 1 12 2\" />\n  <path d=\"M22 2 12 12\" />\n  <path d=\"M16 2h6v6\" /></g>"
} as const satisfies IconData;

export default luCircleArrowOutUpRight;
export { luCircleArrowOutUpRight };
export { luCircleArrowOutUpRight as lucideCircleArrowOutUpRight };
