// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luCircleEqual = {
	"name": "circle-equal",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M7 10h10\" />\n  <path d=\"M7 14h10\" /></g>"
} as const satisfies IconData;

export default luCircleEqual;
export { luCircleEqual };
export { luCircleEqual as lucideCircleEqual };
