// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luCloudAlert = {
	"name": "cloud-alert",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 12v4\" />\n  <path d=\"M12 20h.01\" />\n  <path d=\"M8.128 16.949A7 7 0 1 1 15.71 8h1.79a1 1 0 0 1 0 9h-1.642\" /></g>"
} as const satisfies IconData;

export default luCloudAlert;
export { luCloudAlert };
export { luCloudAlert as lucideCloudAlert };
