// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luColumns3Cog = {
	"name": "columns-3-cog",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.5 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v5.5\" />\n  <path d=\"m14.3 19.6 1-.4\" />\n  <path d=\"M15 3v7.5\" />\n  <path d=\"m15.2 16.9-.9-.3\" />\n  <path d=\"m16.6 21.7.3-.9\" />\n  <path d=\"m16.8 15.3-.4-1\" />\n  <path d=\"m19.1 15.2.3-.9\" />\n  <path d=\"m19.6 21.7-.4-1\" />\n  <path d=\"m20.7 16.8 1-.4\" />\n  <path d=\"m21.7 19.4-.9-.3\" />\n  <path d=\"M9 3v18\" />\n  <circle cx=\"18\" cy=\"18\" r=\"3\" /></g>"
} as const satisfies IconData;

export default luColumns3Cog;
export { luColumns3Cog };
export { luColumns3Cog as lucideColumns3Cog };
