// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luCopyPlus = {
	"name": "copy-plus",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"15\" x2=\"15\" y1=\"12\" y2=\"18\" />\n  <line x1=\"12\" x2=\"18\" y1=\"15\" y2=\"15\" />\n  <rect width=\"14\" height=\"14\" x=\"8\" y=\"8\" rx=\"2\" ry=\"2\" />\n  <path d=\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\" /></g>"
} as const satisfies IconData;

export default luCopyPlus;
export { luCopyPlus };
export { luCopyPlus as lucideCopyPlus };
