// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luDatabaseArrowUp = {
	"name": "database-arrow-up",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 22v-6\" />\n  <path d=\"M21 12.536V5\" />\n  <path d=\"m22 19-3-3-3 3\" />\n  <path d=\"M3 12A9 3 0 0 0 14.457 14.886\" />\n  <path d=\"M3 5V19A9 3 0 0 0 13.318 21.968\" />\n  <ellipse cx=\"12\" cy=\"5\" rx=\"9\" ry=\"3\" /></g>"
} as const satisfies IconData;

export default luDatabaseArrowUp;
export { luDatabaseArrowUp };
export { luDatabaseArrowUp as lucideDatabaseArrowUp };
