// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luDices = {
	"name": "dices",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"12\" height=\"12\" x=\"2\" y=\"10\" rx=\"2\" ry=\"2\" />\n  <path d=\"m17.92 14 3.5-3.5a2.24 2.24 0 0 0 0-3l-5-4.92a2.24 2.24 0 0 0-3 0L10 6\" />\n  <path d=\"M6 18h.01\" />\n  <path d=\"M10 14h.01\" />\n  <path d=\"M15 6h.01\" />\n  <path d=\"M18 9h.01\" /></g>"
} as const satisfies IconData;

export default luDices;
export { luDices };
export { luDices as lucideDices };
