// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luForklift = {
	"name": "forklift",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 12H5a2 2 0 0 0-2 2v5\" />\n  <path d=\"M15 19h7\" />\n  <path d=\"M16 19V2\" />\n  <path d=\"M6 12V7a2 2 0 0 1 2-2h2.172a2 2 0 0 1 1.414.586l3.828 3.828A2 2 0 0 1 16 10.828\" />\n  <path d=\"M7 19h4\" />\n  <circle cx=\"13\" cy=\"19\" r=\"2\" />\n  <circle cx=\"5\" cy=\"19\" r=\"2\" /></g>"
} as const satisfies IconData;

export default luForklift;
export { luForklift };
export { luForklift as lucideForklift };
