// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luGitPullRequestClosed = {
	"name": "git-pull-request-closed",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"6\" cy=\"6\" r=\"3\" />\n  <path d=\"M6 9v12\" />\n  <path d=\"m21 3-6 6\" />\n  <path d=\"m21 9-6-6\" />\n  <path d=\"M18 11.5V15\" />\n  <circle cx=\"18\" cy=\"18\" r=\"3\" /></g>"
} as const satisfies IconData;

export default luGitPullRequestClosed;
export { luGitPullRequestClosed };
export { luGitPullRequestClosed as lucideGitPullRequestClosed };
