// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luJoystick = {
	"name": "joystick",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 17a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-2Z\" />\n  <path d=\"M6 15v-2\" />\n  <path d=\"M12 15V9\" />\n  <circle cx=\"12\" cy=\"6\" r=\"3\" /></g>"
} as const satisfies IconData;

export default luJoystick;
export { luJoystick };
export { luJoystick as lucideJoystick };
