// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luLaptopMinimal = {
	"name": "laptop-minimal",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"12\" x=\"3\" y=\"4\" rx=\"2\" ry=\"2\" />\n  <line x1=\"2\" x2=\"22\" y1=\"20\" y2=\"20\" /></g>"
} as const satisfies IconData;

export default luLaptopMinimal;
export { luLaptopMinimal };
export { luLaptopMinimal as lucideLaptopMinimal };
