// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luLasso = {
	"name": "lasso",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.704 14.467a10 8 0 1 1 3.115 2.375\" />\n  <path d=\"M7 22a5 5 0 0 1-2-3.994\" />\n  <circle cx=\"5\" cy=\"16\" r=\"2\" /></g>"
} as const satisfies IconData;

export default luLasso;
export { luLasso };
export { luLasso as lucideLasso };
