// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luLaugh = {
	"name": "laugh",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M18 13a6 6 0 0 1-6 5 6 6 0 0 1-6-5h12Z\" />\n  <line x1=\"9\" x2=\"9.01\" y1=\"9\" y2=\"9\" />\n  <line x1=\"15\" x2=\"15.01\" y1=\"9\" y2=\"9\" /></g>"
} as const satisfies IconData;

export default luLaugh;
export { luLaugh };
export { luLaugh as lucideLaugh };
