// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luLink2Off = {
	"name": "link-2-off",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 17H7A5 5 0 0 1 7 7\" />\n  <path d=\"M15 7h2a5 5 0 0 1 4 8\" />\n  <line x1=\"8\" x2=\"12\" y1=\"12\" y2=\"12\" />\n  <line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" /></g>"
} as const satisfies IconData;

export default luLink2Off;
export { luLink2Off };
export { luLink2Off as lucideLink2Off };
