// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luListCheck = {
	"name": "list-check",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 5H3\" />\n  <path d=\"M16 12H3\" />\n  <path d=\"M11 19H3\" />\n  <path d=\"m15 18 2 2 4-4\" /></g>"
} as const satisfies IconData;

export default luListCheck;
export { luListCheck };
export { luListCheck as lucideListCheck };
