// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luMessageCircleX = {
	"name": "message-circle-x",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719\" />\n  <path d=\"m15 9-6 6\" />\n  <path d=\"m9 9 6 6\" /></g>"
} as const satisfies IconData;

export default luMessageCircleX;
export { luMessageCircleX };
export { luMessageCircleX as lucideMessageCircleX };
