// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luMessageSquareReply = {
	"name": "message-square-reply",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z\" />\n  <path d=\"m10 8-3 3 3 3\" />\n  <path d=\"M17 14v-1a2 2 0 0 0-2-2H7\" /></g>"
} as const satisfies IconData;

export default luMessageSquareReply;
export { luMessageSquareReply };
export { luMessageSquareReply as lucideMessageSquareReply };
