// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luMoveRight = {
	"name": "move-right",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 8L22 12L18 16\" />\n  <path d=\"M2 12H22\" /></g>"
} as const satisfies IconData;

export default luMoveRight;
export { luMoveRight };
export { luMoveRight as lucideMoveRight };
