// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luNavigationOff = {
	"name": "navigation-off",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8.43 8.43 3 11l8 2 2 8 2.57-5.43\" />\n  <path d=\"M17.39 11.73 22 2l-9.73 4.61\" />\n  <line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" /></g>"
} as const satisfies IconData;

export default luNavigationOff;
export { luNavigationOff };
export { luNavigationOff as lucideNavigationOff };
