// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luPanelBottomDashed = {
	"name": "panel-bottom-dashed",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M14 15h1\" />\n  <path d=\"M19 15h2\" />\n  <path d=\"M3 15h2\" />\n  <path d=\"M9 15h1\" /></g>"
} as const satisfies IconData;

export default luPanelBottomDashed;
export { luPanelBottomDashed };
export { luPanelBottomDashed as lucidePanelBottomDashed };
