// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luRat = {
	"name": "rat",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 22H4a2 2 0 0 1 0-4h12\" />\n  <path d=\"M13.236 18a3 3 0 0 0-2.2-5\" />\n  <path d=\"M16 9h.01\" />\n  <path d=\"M16.82 3.94a3 3 0 1 1 3.237 4.868l1.815 2.587a1.5 1.5 0 0 1-1.5 2.1l-2.872-.453a3 3 0 0 0-3.5 3\" />\n  <path d=\"M17 4.988a3 3 0 1 0-5.2 2.052A7 7 0 0 0 4 14.015 4 4 0 0 0 8 18\" /></g>"
} as const satisfies IconData;

export default luRat;
export { luRat };
export { luRat as lucideRat };
