// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luRotate3d = {
	"name": "rotate-3d",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m15.194 13.707 3.814 1.86-1.86 3.814\" />\n  <path d=\"M16.47214 7.52786 A 5 10 0 1 0 13 21.79796\" />\n  <path d=\"M21.79796 11 A 10 5 0 1 0 19 15.57071\" /></g>"
} as const satisfies IconData;

export default luRotate3d;
export { luRotate3d };
export { luRotate3d as lucideRotate3d };
