// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luScooter = {
	"name": "scooter",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 4h-3.5l2 11.05\" />\n  <path d=\"M6.95 17h5.142c.523 0 .95-.406 1.063-.916a6.5 6.5 0 0 1 5.345-5.009\" />\n  <circle cx=\"19.5\" cy=\"17.5\" r=\"2.5\" />\n  <circle cx=\"4.5\" cy=\"17.5\" r=\"2.5\" /></g>"
} as const satisfies IconData;

export default luScooter;
export { luScooter };
export { luScooter as lucideScooter };
