// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luSquareCenterlineDashedHorizontal = {
	"name": "square-centerline-dashed-horizontal",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 3H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h3\" />\n  <path d=\"M16 3h3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-3\" />\n  <path d=\"M12 20v2\" />\n  <path d=\"M12 14v2\" />\n  <path d=\"M12 8v2\" />\n  <path d=\"M12 2v2\" /></g>"
} as const satisfies IconData;

export default luSquareCenterlineDashedHorizontal;
export { luSquareCenterlineDashedHorizontal };
export { luSquareCenterlineDashedHorizontal as lucideSquareCenterlineDashedHorizontal };
