// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luSquareArrowUpLeft = {
	"name": "square-arrow-up-left",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 15 9 9\" />\n  <path d=\"M9 15V9h6\" />\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" /></g>"
} as const satisfies IconData;

export default luSquareArrowUpLeft;
export { luSquareArrowUpLeft };
export { luSquareArrowUpLeft as lucideSquareArrowUpLeft };
