// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luTally5 = {
	"name": "tally-5",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 4v16\" />\n  <path d=\"M9 4v16\" />\n  <path d=\"M14 4v16\" />\n  <path d=\"M19 4v16\" />\n  <path d=\"M22 6 2 18\" /></g>"
} as const satisfies IconData;

export default luTally5;
export { luTally5 };
export { luTally5 as lucideTally5 };
