// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luUserCog = {
	"name": "user-cog",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 15H6a4 4 0 0 0-4 4v2\" />\n  <path d=\"m14.305 16.53.923-.382\" />\n  <path d=\"m15.228 13.852-.923-.383\" />\n  <path d=\"m16.852 12.228-.383-.923\" />\n  <path d=\"m16.852 17.772-.383.924\" />\n  <path d=\"m19.148 12.228.383-.923\" />\n  <path d=\"m19.53 18.696-.382-.924\" />\n  <path d=\"m20.772 13.852.924-.383\" />\n  <path d=\"m20.772 16.148.924.383\" />\n  <circle cx=\"18\" cy=\"15\" r=\"3\" />\n  <circle cx=\"9\" cy=\"7\" r=\"4\" /></g>"
} as const satisfies IconData;

export default luUserCog;
export { luUserCog };
export { luUserCog as lucideUserCog };
