// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const luUserKey = {
	"name": "user-key",
	"set": "lucide",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 11v6\" />\n  <path d=\"M20 13h2\" />\n  <path d=\"M3 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 2.072.578\" />\n  <circle cx=\"10\" cy=\"7\" r=\"4\" />\n  <circle cx=\"20\" cy=\"19\" r=\"2\" /></g>"
} as const satisfies IconData;

export default luUserKey;
export { luUserKey };
export { luUserKey as lucideUserKey };
