// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siAwesomewm = {
	"name": "awesomewm",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M0 24V8.25h16.5V7.5H0V0h24v24h-7.5v-8.25h-9v.75h8.25V24z\"/>"
} as const satisfies IconData;

export default siAwesomewm;
export { siAwesomewm };
export { siAwesomewm as simpleAwesomewm };
