// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siBetfair = {
	"name": "betfair",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M20.218 3.14h-7.083v3.6H9.352l7.359 8.582L24 6.67h-3.782zM0 17.26h3.782v3.6h7.083v-3.6h3.783l-7.29-8.583z\"/>"
} as const satisfies IconData;

export default siBetfair;
export { siBetfair };
export { siBetfair as simpleBetfair };
