// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siClickhouse = {
	"name": "clickhouse",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M21.333 10H24v4h-2.667ZM16 1.335h2.667v21.33H16Zm-5.333 0h2.666v21.33h-2.666ZM0 22.665V1.335h2.667v21.33zm5.333-21.33H8v21.33H5.333Z\"/>"
} as const satisfies IconData;

export default siClickhouse;
export { siClickhouse };
export { siClickhouse as simpleClickhouse };
