// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siDeepcool = {
	"name": "deepcool",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 12v3.046H3.046V6h6V0H12v9.046H6.092V12H12Zm8.954 3.046V18h-5.908v6H12v-8.954h8.954Z\"/>"
} as const satisfies IconData;

export default siDeepcool;
export { siDeepcool };
export { siDeepcool as simpleDeepcool };
