// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siDeutschebank = {
	"name": "deutschebank",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M3.375 3.375v17.25h17.25V3.375H3.375zM0 0h24v24H0V0zm5.25 18.225 9.15-12.45h4.35L9.6 18.225H5.25z\"/>"
} as const satisfies IconData;

export default siDeutschebank;
export { siDeutschebank };
export { siDeutschebank as simpleDeutschebank };
