// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siFaceit = {
	"name": "faceit",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M23.999 2.705a.167.167 0 00-.312-.1 1141.27 1141.27 0 00-6.053 9.375H.218c-.221 0-.301.282-.11.352 7.227 2.73 17.667 6.836 23.5 9.134.15.06.39-.08.39-.18z\"/>"
} as const satisfies IconData;

export default siFaceit;
export { siFaceit };
export { siFaceit as simpleFaceit };
