// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siHyper = {
	"name": "hyper",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M13.565 17.91H24v1.964H13.565zm-3.201-5.09l-9.187 8.003 2.86-7.004L0 11.179l9.187-8.002-3.11 7.451z\"/>"
} as const satisfies IconData;

export default siHyper;
export { siHyper };
export { siHyper as simpleHyper };
