// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siLibreoffice = {
	"name": "libreoffice",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M16.365 0a.597.597 0 00-.555.352.582.582 0 00.128.635l4.985 4.996a.605.605 0 00.635.133.59.59 0 00.363-.53V.577A.605.605 0 0021.335 0zM2.661 0a.59.59 0 00-.582.59v22.82a.59.59 0 00.582.59h18.67a.59.59 0 00.59-.59V8.716a.59.59 0 00-.17-.42L13.674.182a.59.59 0 00-.42-.181zm.59 1.184h9.754l7.733 7.77v13.863H3.251z\"/>"
} as const satisfies IconData;

export default siLibreoffice;
export { siLibreoffice };
export { siLibreoffice as simpleLibreoffice };
