// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siModx = {
	"name": "modx",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M19.145 9.49l4.47-7.19H12.118l-1.24 2.023zM2.92 0v11.497l2.48 1.55 13.435-3.1zm18.16 24V12.503l-1.984-1.263-5.168 8.267zM5.165 14.053l-4.78 7.648h11.497L18.6 10.953Z\"/>"
} as const satisfies IconData;

export default siModx;
export { siModx };
export { siModx as simpleModx };
