// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siNaver = {
	"name": "naver",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M16.273 12.845 7.376 0H0v24h7.726V11.156L16.624 24H24V0h-7.727v12.845Z\"/>"
} as const satisfies IconData;

export default siNaver;
export { siNaver };
export { siNaver as simpleNaver };
