// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siNetdata = {
	"name": "netdata",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M14.764 21.827H9.922L0 2.173h14.084c5.476.01 9.913 4.565 9.916 10.183-.009 5.235-4.14 9.47-9.238 9.47z\"/>"
} as const satisfies IconData;

export default siNetdata;
export { siNetdata };
export { siNetdata as simpleNetdata };
