// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siPandora = {
	"name": "pandora",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M1.882 0v24H8.32a1.085 1.085 0 001.085-1.085v-4.61h1.612c7.88 0 11.103-4.442 11.103-9.636C22.119 2.257 17.247 0 12.662 0H1.882Z\"/>"
} as const satisfies IconData;

export default siPandora;
export { siPandora };
export { siPandora as simplePandora };
