// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siPeertube = {
	"name": "peertube",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 6.545v10.91L20.727 12M3.273 12v12L12 17.455M3.273 0v12L12 6.545\"/>"
} as const satisfies IconData;

export default siPeertube;
export { siPeertube };
export { siPeertube as simplePeertube };
