// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siRadar = {
	"name": "radar",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M12 0L2.197 23.975 12 19.952 21.803 24z\"/>"
} as const satisfies IconData;

export default siRadar;
export { siRadar };
export { siRadar as simpleRadar };
