// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siRiseup = {
	"name": "riseup",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M10.5 24l-1.485-9.007-8.961-1.738L8.16 9.06 7.045 0l6.495 6.414 8.271-3.861-4.093 8.16 6.228 6.673-9.024-1.372z\"/>"
} as const satisfies IconData;

export default siRiseup;
export { siRiseup };
export { siRiseup as simpleRiseup };
