// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siUpptime = {
	"name": "upptime",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M11.86 15.68c1.926 0 3.489 1.526 3.489 3.406 0 1.88-1.563 3.407-3.488 3.407-1.926 0-3.489-1.526-3.489-3.407 0-1.88 1.563-3.407 3.489-3.407ZM24 14.884 12 1.507 0 14.885l3.158 3.52L12 8.548l8.842 9.857L24 14.885Z\"/>"
} as const satisfies IconData;

export default siUpptime;
export { siUpptime };
export { siUpptime as simpleUpptime };
