// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const siWindows11 = {
	"name": "windows11",
	"set": "simple",
	"viewBox": "0 0 24 24",
	"body": "<path d=\"M0,0H11.377V11.372H0ZM12.623,0H24V11.372H12.623ZM0,12.623H11.377V24H0Zm12.623,0H24V24H12.623\"/>"
} as const satisfies IconData;

export default siWindows11;
export { siWindows11 };
export { siWindows11 as simpleWindows11 };
