// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbfLayoutGrid = {
	"name": "layout-grid",
	"set": "tablerfill",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"currentColor\"><path d=\"M9 3a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z\" />\n  <path d=\"M19 3a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z\" />\n  <path d=\"M9 13a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z\" />\n  <path d=\"M19 13a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2z\" /></g>"
} as const satisfies IconData;

export default tbfLayoutGrid;
export { tbfLayoutGrid };
export { tbfLayoutGrid as tablerfillLayoutGrid };
