// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAbacusOff = {
	"name": "abacus-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 5v16\" />\n  <path d=\"M19 21v-2m0 -4v-12\" />\n  <path d=\"M5 7h2m4 0h8\" />\n  <path d=\"M5 15h10\" />\n  <path d=\"M8 13v4\" />\n  <path d=\"M11 13v4\" />\n  <path d=\"M16 16v1\" />\n  <path d=\"M14 5v4\" />\n  <path d=\"M11 5v2\" />\n  <path d=\"M8 8v1\" />\n  <path d=\"M3 21h18\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbAbacusOff;
export { tbAbacusOff };
export { tbAbacusOff as tablerAbacusOff };
