// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAccessPoint = {
	"name": "access-point",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 12l0 .01\" />\n  <path d=\"M14.828 9.172a4 4 0 0 1 0 5.656\" />\n  <path d=\"M17.657 6.343a8 8 0 0 1 0 11.314\" />\n  <path d=\"M9.168 14.828a4 4 0 0 1 0 -5.656\" />\n  <path d=\"M6.337 17.657a8 8 0 0 1 0 -11.314\" /></g>"
} as const satisfies IconData;

export default tbAccessPoint;
export { tbAccessPoint };
export { tbAccessPoint as tablerAccessPoint };
