// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAiAgent = {
	"name": "ai-agent",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11 14a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M6 14a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M16 14a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M11 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M13.5 9.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M8.5 9.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M13.5 18.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M8.5 18.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M3.5 18.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M18.5 18.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /></g>"
} as const satisfies IconData;

export default tbAiAgent;
export { tbAiAgent };
export { tbAiAgent as tablerAiAgent };
