// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAlignBoxBottomRight = {
	"name": "align-box-bottom-right",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14\" />\n  <path d=\"M11 15v2\" />\n  <path d=\"M14 11v6\" />\n  <path d=\"M17 13v4\" /></g>"
} as const satisfies IconData;

export default tbAlignBoxBottomRight;
export { tbAlignBoxBottomRight };
export { tbAlignBoxBottomRight as tablerAlignBoxBottomRight };
