// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAnchor = {
	"name": "anchor",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 9v12m-8 -8a8 8 0 0 0 16 0m1 0h-2m-14 0h-2\" />\n  <path d=\"M9 6a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /></g>"
} as const satisfies IconData;

export default tbAnchor;
export { tbAnchor };
export { tbAnchor as tablerAnchor };
