// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAntennaBars4 = {
	"name": "antenna-bars-4",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 18l0 -3\" />\n  <path d=\"M10 18l0 -6\" />\n  <path d=\"M14 18l0 -9\" />\n  <path d=\"M18 18l0 .01\" /></g>"
} as const satisfies IconData;

export default tbAntennaBars4;
export { tbAntennaBars4 };
export { tbAntennaBars4 as tablerAntennaBars4 };
