// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowsMinimize = {
	"name": "arrows-minimize",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 9l4 0l0 -4\" />\n  <path d=\"M3 3l6 6\" />\n  <path d=\"M5 15l4 0l0 4\" />\n  <path d=\"M3 21l6 -6\" />\n  <path d=\"M19 9l-4 0l0 -4\" />\n  <path d=\"M15 9l6 -6\" />\n  <path d=\"M19 15l-4 0l0 4\" />\n  <path d=\"M15 15l6 6\" /></g>"
} as const satisfies IconData;

export default tbArrowsMinimize;
export { tbArrowsMinimize };
export { tbArrowsMinimize as tablerArrowsMinimize };
