// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowBigLeftLines = {
	"name": "arrow-big-left-lines",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 15v3.586a1 1 0 0 1 -1.707 .707l-6.586 -6.586a1 1 0 0 1 0 -1.414l6.586 -6.586a1 1 0 0 1 1.707 .707v3.586h3v6h-3\" />\n  <path d=\"M21 15v-6\" />\n  <path d=\"M18 15v-6\" /></g>"
} as const satisfies IconData;

export default tbArrowBigLeftLines;
export { tbArrowBigLeftLines };
export { tbArrowBigLeftLines as tablerArrowBigLeftLines };
