// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowElbowLeft = {
	"name": "arrow-elbow-left",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 14v-6h6\" />\n  <path d=\"M3 8l9 9l9 -9\" /></g>"
} as const satisfies IconData;

export default tbArrowElbowLeft;
export { tbArrowElbowLeft };
export { tbArrowElbowLeft as tablerArrowElbowLeft };
