// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowsUp = {
	"name": "arrows-up",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 3l0 18\" />\n  <path d=\"M4 6l3 -3l3 3\" />\n  <path d=\"M20 6l-3 -3l-3 3\" />\n  <path d=\"M7 3l0 18\" /></g>"
} as const satisfies IconData;

export default tbArrowsUp;
export { tbArrowsUp };
export { tbArrowsUp as tablerArrowsUp };
