// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowUpFromArc = {
	"name": "arrow-up-from-arc",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 9v12\" />\n  <path d=\"M8 17l4 4l4 -4\" />\n  <path d=\"M21 12a9 9 0 0 0 -18 0\" /></g>"
} as const satisfies IconData;

export default tbArrowUpFromArc;
export { tbArrowUpFromArc };
export { tbArrowUpFromArc as tablerArrowUpFromArc };
