// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowBarToLeftDashed = {
	"name": "arrow-bar-to-left-dashed",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 12l10 0\" />\n  <path d=\"M10 12l4 -4\" />\n  <path d=\"M10 12l4 4\" />\n  <path d=\"M4 20l0 -3m0 -13l0 3m0 3.5l0 3\" /></g>"
} as const satisfies IconData;

export default tbArrowBarToLeftDashed;
export { tbArrowBarToLeftDashed };
export { tbArrowBarToLeftDashed as tablerArrowBarToLeftDashed };
