// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowDownRhombus = {
	"name": "arrow-down-rhombus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 8v13\" />\n  <path d=\"M15 18l-3 3l-3 -3\" />\n  <path d=\"M14.5 5.5l-2.5 -2.5l-2.5 2.5l2.5 2.5l2.5 -2.5\" /></g>"
} as const satisfies IconData;

export default tbArrowDownRhombus;
export { tbArrowDownRhombus };
export { tbArrowDownRhombus as tablerArrowDownRhombus };
