// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArrowBigRight = {
	"name": "arrow-big-right",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 9h8v-3.586a1 1 0 0 1 1.707 -.707l6.586 6.586a1 1 0 0 1 0 1.414l-6.586 6.586a1 1 0 0 1 -1.707 -.707v-3.586h-8a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1\" /></g>"
} as const satisfies IconData;

export default tbArrowBigRight;
export { tbArrowBigRight };
export { tbArrowBigRight as tablerArrowBigRight };
