// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbArticleOff = {
	"name": "article-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 4h11a2 2 0 0 1 2 2v11m-1.172 2.821a1.993 1.993 0 0 1 -.828 .179h-14a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 1.156 -1.814\" />\n  <path d=\"M7 8h1m4 0h5\" />\n  <path d=\"M7 12h5m4 0h1\" />\n  <path d=\"M7 16h9\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbArticleOff;
export { tbArticleOff };
export { tbArticleOff as tablerArticleOff };
