// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbAtom2 = {
	"name": "atom-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M12 21l0 .01\" />\n  <path d=\"M3 9l0 .01\" />\n  <path d=\"M21 9l0 .01\" />\n  <path d=\"M8 20.1a9 9 0 0 1 -5 -7.1\" />\n  <path d=\"M16 20.1a9 9 0 0 0 5 -7.1\" />\n  <path d=\"M6.2 5a9 9 0 0 1 11.4 0\" /></g>"
} as const satisfies IconData;

export default tbAtom2;
export { tbAtom2 };
export { tbAtom2 as tablerAtom2 };
