// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBabyCarriage = {
	"name": "baby-carriage",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M16 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M2 5h2.5l1.632 4.897a6 6 0 0 0 5.693 4.103h2.675a5.5 5.5 0 0 0 0 -11h-.5v6\" />\n  <path d=\"M6 9h14\" />\n  <path d=\"M9 17l1 -3\" />\n  <path d=\"M16 14l1 3\" /></g>"
} as const satisfies IconData;

export default tbBabyCarriage;
export { tbBabyCarriage };
export { tbBabyCarriage as tablerBabyCarriage };
