// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBadgeAdOff = {
	"name": "badge-ad-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 5h10a2 2 0 0 1 2 2v10m-2 2h-14a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2\" />\n  <path d=\"M14 14v1h1m2 -2v-2a2 2 0 0 0 -2 -2h-1v1\" />\n  <path d=\"M7 15v-4.5a1.5 1.5 0 0 1 2.077 -1.385m.788 .762c.087 .19 .135 .4 .135 .623v4.5\" />\n  <path d=\"M7 13h3\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbBadgeAdOff;
export { tbBadgeAdOff };
export { tbBadgeAdOff as tablerBadgeAdOff };
