// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBallFootballOff = {
	"name": "ball-football-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.041 16.046a9 9 0 0 0 -12.084 -12.09m-2.323 1.683a9 9 0 0 0 12.726 12.73\" />\n  <path d=\"M12 7l4.755 3.455l-.566 1.743l-.98 3.014l-.209 .788h-6l-1.755 -5.545l1.86 -1.351l2.313 -1.681l.582 -.423\" />\n  <path d=\"M12 7v-4\" />\n  <path d=\"M15 16l2.5 3\" />\n  <path d=\"M16.755 10.455l3.745 -1.455\" />\n  <path d=\"M9.061 16.045l-2.561 2.955\" />\n  <path d=\"M7.245 10.455l-3.745 -1.455\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbBallFootballOff;
export { tbBallFootballOff };
export { tbBallFootballOff as tablerBallFootballOff };
