// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBallTennis = {
	"name": "ball-tennis",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />\n  <path d=\"M6 5.3a9 9 0 0 1 0 13.4\" />\n  <path d=\"M18 5.3a9 9 0 0 0 0 13.4\" /></g>"
} as const satisfies IconData;

export default tbBallTennis;
export { tbBallTennis };
export { tbBallTennis as tablerBallTennis };
