// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBandage = {
	"name": "bandage",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 12l0 .01\" />\n  <path d=\"M10 12l0 .01\" />\n  <path d=\"M12 10l0 .01\" />\n  <path d=\"M12 14l0 .01\" />\n  <path d=\"M4.5 12.5l8 -8a4.94 4.94 0 0 1 7 7l-8 8a4.94 4.94 0 0 1 -7 -7\" /></g>"
} as const satisfies IconData;

export default tbBandage;
export { tbBandage };
export { tbBandage as tablerBandage };
