// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBasketDown = {
	"name": "basket-down",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 10l-2 -6\" />\n  <path d=\"M7 10l2 -6\" />\n  <path d=\"M12 20h-4.756a3 3 0 0 1 -2.965 -2.544l-1.255 -7.152a2 2 0 0 1 1.977 -2.304h13.999a2 2 0 0 1 1.977 2.304l-.349 1.989\" />\n  <path d=\"M10 14a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" />\n  <path d=\"M19 16v6\" />\n  <path d=\"M22 19l-3 3l-3 -3\" /></g>"
} as const satisfies IconData;

export default tbBasketDown;
export { tbBasketDown };
export { tbBasketDown as tablerBasketDown };
