// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBath = {
	"name": "bath",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 12h16a1 1 0 0 1 1 1v3a4 4 0 0 1 -4 4h-10a4 4 0 0 1 -4 -4v-3a1 1 0 0 1 1 -1\" />\n  <path d=\"M6 12v-7a2 2 0 0 1 2 -2h3v2.25\" />\n  <path d=\"M4 21l1 -1.5\" />\n  <path d=\"M20 21l-1 -1.5\" /></g>"
} as const satisfies IconData;

export default tbBath;
export { tbBath };
export { tbBath as tablerBath };
