// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBatteryVerticalCharging2 = {
	"name": "battery-vertical-charging-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7 18v-11c0 -1.105 .895 -2 2 -2h.5c.276 0 .5 -.224 .5 -.5s.224 -.5 .5 -.5h3c.276 0 .5 .224 .5 .5s.224 .5 .5 .5h.5c1.105 0 2 .895 2 2v1m-10 10c0 1.105 .895 2 2 2h1\" />\n  <path d=\"M12 14h6v2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2l0 -2\" />\n  <path d=\"M15 21v-3\" />\n  <path d=\"M13 14v-2.5\" />\n  <path d=\"M17 14v-2.5\" /></g>"
} as const satisfies IconData;

export default tbBatteryVerticalCharging2;
export { tbBatteryVerticalCharging2 };
export { tbBatteryVerticalCharging2 as tablerBatteryVerticalCharging2 };
