// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBellPause = {
	"name": "bell-pause",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 17h-9a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6a2 2 0 1 1 4 0a7 7 0 0 1 4 6v2\" />\n  <path d=\"M9 17v1a3 3 0 0 0 4.022 2.821\" />\n  <path d=\"M17 17v5\" />\n  <path d=\"M21 17v5\" /></g>"
} as const satisfies IconData;

export default tbBellPause;
export { tbBellPause };
export { tbBellPause as tablerBellPause };
