// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBoxModel = {
	"name": "box-model",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 8h8v8h-8l0 -8\" />\n  <path d=\"M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12\" />\n  <path d=\"M16 16l3.3 3.3\" />\n  <path d=\"M16 8l3.3 -3.3\" />\n  <path d=\"M8 8l-3.3 -3.3\" />\n  <path d=\"M8 16l-3.3 3.3\" /></g>"
} as const satisfies IconData;

export default tbBoxModel;
export { tbBoxModel };
export { tbBoxModel as tablerBoxModel };
