// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBracketsAngle = {
	"name": "brackets-angle",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 4l-5 8l5 8\" />\n  <path d=\"M16 4l5 8l-5 8\" /></g>"
} as const satisfies IconData;

export default tbBracketsAngle;
export { tbBracketsAngle };
export { tbBracketsAngle as tablerBracketsAngle };
