// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBracketsAngleOff = {
	"name": "brackets-angle-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 4h.01\" />\n  <path d=\"M6.453 6.474l-3.453 5.526l5 8\" />\n  <path d=\"M16 4l5 8l-1.917 3.067\" />\n  <path d=\"M17.535 17.544l-1.535 2.456\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbBracketsAngleOff;
export { tbBracketsAngleOff };
export { tbBracketsAngleOff as tablerBracketsAngleOff };
