// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandCampaignmonitor = {
	"name": "brand-campaignmonitor",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 18l9 -6.462l-9 -5.538v12h18v-12l-9 5.538\" /></g>"
} as const satisfies IconData;

export default tbBrandCampaignmonitor;
export { tbBrandCampaignmonitor };
export { tbBrandCampaignmonitor as tablerBrandCampaignmonitor };
