// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandReason = {
	"name": "brand-reason",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14\" />\n  <path d=\"M18 18h-3v-6h3\" />\n  <path d=\"M18 15h-3\" />\n  <path d=\"M8 18v-6h2.5a1.5 1.5 0 0 1 0 3h-2.5\" />\n  <path d=\"M12 18l-2 -3\" /></g>"
} as const satisfies IconData;

export default tbBrandReason;
export { tbBrandReason };
export { tbBrandReason as tablerBrandReason };
