// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandCss3 = {
	"name": "brand-css3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 4l-2 14.5l-6 2l-6 -2l-2 -14.5l16 0\" />\n  <path d=\"M8.5 8h7l-4.5 4h4l-.5 3.5l-2.5 .75l-2.5 -.75l-.1 -.5\" /></g>"
} as const satisfies IconData;

export default tbBrandCss3;
export { tbBrandCss3 };
export { tbBrandCss3 as tablerBrandCss3 };
