// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandLeetcode = {
	"name": "brand-leetcode",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 13h7.5\" />\n  <path d=\"M9.424 7.268l4.999 -4.999\" />\n  <path d=\"M16.633 16.644l-2.402 2.415a3.189 3.189 0 0 1 -4.524 0l-3.77 -3.787a3.223 3.223 0 0 1 0 -4.544l3.77 -3.787a3.189 3.189 0 0 1 4.524 0l2.302 2.313\" /></g>"
} as const satisfies IconData;

export default tbBrandLeetcode;
export { tbBrandLeetcode };
export { tbBrandLeetcode as tablerBrandLeetcode };
