// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandPicsart = {
	"name": "brand-picsart",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 9a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" />\n  <path d=\"M9 9a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M5 9v11a2 2 0 1 0 4 0v-4.5\" /></g>"
} as const satisfies IconData;

export default tbBrandPicsart;
export { tbBrandPicsart };
export { tbBrandPicsart as tablerBrandPicsart };
