// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandOpenvpn = {
	"name": "brand-openvpn",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15.618 20.243l-2.193 -5.602a3 3 0 1 0 -2.849 0l-2.193 5.603\" />\n  <path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /></g>"
} as const satisfies IconData;

export default tbBrandOpenvpn;
export { tbBrandOpenvpn };
export { tbBrandOpenvpn as tablerBrandOpenvpn };
