// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandCoreos = {
	"name": "brand-coreos",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12a9 9 0 1 1 -18 0a9 9 0 0 1 18 0\" />\n  <path d=\"M12 3c-3.263 3.212 -3 7.654 -3 12c4.59 .244 8.814 -.282 12 -3\" />\n  <path d=\"M9.5 9a4.494 4.494 0 0 1 5.5 5.5\" /></g>"
} as const satisfies IconData;

export default tbBrandCoreos;
export { tbBrandCoreos };
export { tbBrandCoreos as tablerBrandCoreos };
