// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrandDigg = {
	"name": "brand-digg",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 15h-3v-4h3\" />\n  <path d=\"M15 15h-3v-4h3\" />\n  <path d=\"M9 15v-4\" />\n  <path d=\"M15 11v7h-3\" />\n  <path d=\"M6 7v8\" />\n  <path d=\"M21 15h-3v-4h3\" />\n  <path d=\"M21 11v7h-3\" /></g>"
} as const satisfies IconData;

export default tbBrandDigg;
export { tbBrandDigg };
export { tbBrandDigg as tablerBrandDigg };
