// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBrightnessUp = {
	"name": "brightness-up",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M12 5l0 -2\" />\n  <path d=\"M17 7l1.4 -1.4\" />\n  <path d=\"M19 12l2 0\" />\n  <path d=\"M17 17l1.4 1.4\" />\n  <path d=\"M12 19l0 2\" />\n  <path d=\"M7 17l-1.4 1.4\" />\n  <path d=\"M6 12l-2 0\" />\n  <path d=\"M7 7l-1.4 -1.4\" /></g>"
} as const satisfies IconData;

export default tbBrightnessUp;
export { tbBrightnessUp };
export { tbBrightnessUp as tablerBrightnessUp };
