// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBuildingFactory2 = {
	"name": "building-factory-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 21h18\" />\n  <path d=\"M5 21v-12l5 4v-4l5 4h4\" />\n  <path d=\"M19 21v-8l-1.436 -9.574a.5 .5 0 0 0 -.495 -.426h-1.145a.5 .5 0 0 0 -.494 .418l-1.43 8.582\" />\n  <path d=\"M9 17h1\" />\n  <path d=\"M14 17h1\" /></g>"
} as const satisfies IconData;

export default tbBuildingFactory2;
export { tbBuildingFactory2 };
export { tbBuildingFactory2 as tablerBuildingFactory2 };
