// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbBuildingMonument = {
	"name": "building-monument",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 18l2 -13l2 -2l2 2l2 13\" />\n  <path d=\"M5 21v-3h14v3\" />\n  <path d=\"M3 21l18 0\" /></g>"
} as const satisfies IconData;

export default tbBuildingMonument;
export { tbBuildingMonument };
export { tbBuildingMonument as tablerBuildingMonument };
