// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCactus = {
	"name": "cactus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 9v1a3 3 0 0 0 3 3h1\" />\n  <path d=\"M18 8v5a3 3 0 0 1 -3 3h-1\" />\n  <path d=\"M10 21v-16a2 2 0 1 1 4 0v16\" />\n  <path d=\"M7 21h10\" /></g>"
} as const satisfies IconData;

export default tbCactus;
export { tbCactus };
export { tbCactus as tablerCactus };
