// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCalendarClock = {
	"name": "calendar-clock",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.5 21h-4.5a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v3\" />\n  <path d=\"M16 3v4\" />\n  <path d=\"M8 3v4\" />\n  <path d=\"M4 11h10\" />\n  <path d=\"M14 18a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\" />\n  <path d=\"M18 16.5v1.5l.5 .5\" /></g>"
} as const satisfies IconData;

export default tbCalendarClock;
export { tbCalendarClock };
export { tbCalendarClock as tablerCalendarClock };
