// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCalendarRepeat = {
	"name": "calendar-repeat",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.5 21h-6.5a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v3\" />\n  <path d=\"M16 3v4\" />\n  <path d=\"M8 3v4\" />\n  <path d=\"M4 11h12\" />\n  <path d=\"M20 14l2 2h-3\" />\n  <path d=\"M20 18l2 -2\" />\n  <path d=\"M19 16a3 3 0 1 0 2 5.236\" /></g>"
} as const satisfies IconData;

export default tbCalendarRepeat;
export { tbCalendarRepeat };
export { tbCalendarRepeat as tablerCalendarRepeat };
