// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCapProjecting = {
	"name": "cap-projecting",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 6h-13a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h13\" />\n  <path d=\"M13 12a2 2 0 1 1 -4 0a2 2 0 0 1 4 0\" />\n  <path d=\"M13 12h7\" /></g>"
} as const satisfies IconData;

export default tbCapProjecting;
export { tbCapProjecting };
export { tbCapProjecting as tablerCapProjecting };
