// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCarOffRoad = {
	"name": "car-off-road",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 17h6\" />\n  <path d=\"M9 17a2 2 0 1 1 -4 0a2 2 0 0 1 4 0\" />\n  <path d=\"M19 17a2 2 0 1 1 -4 0a2 2 0 0 1 4 0\" />\n  <path d=\"M17 10l-2 -3\" />\n  <path d=\"M19 17h2v-5a2 2 0 0 0 -2 -2h-5v2h-2.586a1 1 0 0 1 -.707 -.293l-1.121 -1.121a2 2 0 0 0 -1.414 -.586h-4.172a1 1 0 0 0 -1 1v6h2\" /></g>"
} as const satisfies IconData;

export default tbCarOffRoad;
export { tbCarOffRoad };
export { tbCarOffRoad as tablerCarOffRoad };
