// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCarSuspension = {
	"name": "car-suspension",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 22a3 3 0 1 1 0 -6a3 3 0 0 1 0 6\" />\n  <path d=\"M12 16v-12\" />\n  <path d=\"M13 2h-2v2h2v-2\" />\n  <path d=\"M9 11l6 -1\" />\n  <path d=\"M9 14l6 -1\" />\n  <path d=\"M9 8l6 -1\" /></g>"
} as const satisfies IconData;

export default tbCarSuspension;
export { tbCarSuspension };
export { tbCarSuspension as tablerCarSuspension };
