// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCarouselHorizontal = {
	"name": "carousel-horizontal",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7 6a1 1 0 0 1 1 -1h8a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-8a1 1 0 0 1 -1 -1l0 -12\" />\n  <path d=\"M22 17h-1a1 1 0 0 1 -1 -1v-8a1 1 0 0 1 1 -1h1\" />\n  <path d=\"M2 17h1a1 1 0 0 0 1 -1v-8a1 1 0 0 0 -1 -1h-1\" /></g>"
} as const satisfies IconData;

export default tbCarouselHorizontal;
export { tbCarouselHorizontal };
export { tbCarouselHorizontal as tablerCarouselHorizontal };
