// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCastOff = {
	"name": "cast-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 19h.01\" />\n  <path d=\"M7 19a4 4 0 0 0 -4 -4\" />\n  <path d=\"M11 19a8 8 0 0 0 -8 -8\" />\n  <path d=\"M15 19h3a3 3 0 0 0 .875 -.13m2 -2a3 3 0 0 0 .128 -.868v-8a3 3 0 0 0 -3 -3h-9m-3.865 .136a3 3 0 0 0 -1.935 1.864\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbCastOff;
export { tbCastOff };
export { tbCastOff as tablerCastOff };
