// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCellSignal3 = {
	"name": "cell-signal-3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 20h-15.269a.731 .731 0 0 1 -.517 -1.249l14.537 -14.537a.731 .731 0 0 1 1.249 .517v15.269\" />\n  <path d=\"M12 20v-9\" /></g>"
} as const satisfies IconData;

export default tbCellSignal3;
export { tbCellSignal3 };
export { tbCellSignal3 as tablerCellSignal3 };
