// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbChairDirector = {
	"name": "chair-director",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 21l12 -9\" />\n  <path d=\"M6 12l12 9\" />\n  <path d=\"M5 12h14\" />\n  <path d=\"M6 3v9\" />\n  <path d=\"M18 3v9\" />\n  <path d=\"M6 8h12\" />\n  <path d=\"M6 5h12\" /></g>"
} as const satisfies IconData;

export default tbChairDirector;
export { tbChairDirector };
export { tbChairDirector as tablerChairDirector };
