// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbChartDots = {
	"name": "chart-dots",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v18h18\" />\n  <path d=\"M7 9a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M17 7a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M12 15a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M10.16 10.62l2.34 2.88\" />\n  <path d=\"M15.088 13.328l2.837 -4.586\" /></g>"
} as const satisfies IconData;

export default tbChartDots;
export { tbChartDots };
export { tbChartDots as tablerChartDots };
