// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbChartDonut3 = {
	"name": "chart-donut-3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3v5m4 4h5\" />\n  <path d=\"M8.929 14.582l-3.429 2.918\" />\n  <path d=\"M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\" />\n  <path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /></g>"
} as const satisfies IconData;

export default tbChartDonut3;
export { tbChartDonut3 };
export { tbChartDonut3 as tablerChartDonut3 };
