// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbChristmasTree = {
	"name": "christmas-tree",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3l4 4l-2 1l4 4l-3 1l4 4h-14l4 -4l-3 -1l4 -4l-2 -1l4 -4\" />\n  <path d=\"M14 17v3a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-3\" /></g>"
} as const satisfies IconData;

export default tbChristmasTree;
export { tbChristmasTree };
export { tbChristmasTree as tablerChristmasTree };
