// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCircuitCapacitorPolarized = {
	"name": "circuit-capacitor-polarized",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 12h-8\" />\n  <path d=\"M2 12h8\" />\n  <path d=\"M10 7v10\" />\n  <path d=\"M14 7v10\" />\n  <path d=\"M17 5h4\" />\n  <path d=\"M19 3v4\" /></g>"
} as const satisfies IconData;

export default tbCircuitCapacitorPolarized;
export { tbCircuitCapacitorPolarized };
export { tbCircuitCapacitorPolarized as tablerCircuitCapacitorPolarized };
