// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCircleDottedLetterQ = {
	"name": "circle-dotted-letter-q",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 8a2 2 0 0 1 2 2v4a2 2 0 1 1 -4 0v-4a2 2 0 0 1 2 -2\" />\n  <path d=\"M13 15l1 1\" />\n  <path d=\"M7.5 4.21v.01\" />\n  <path d=\"M4.21 7.5v.01\" />\n  <path d=\"M3 12v.01\" />\n  <path d=\"M4.21 16.5v.01\" />\n  <path d=\"M7.5 19.79v.01\" />\n  <path d=\"M12 21v.01\" />\n  <path d=\"M16.5 19.79v.01\" />\n  <path d=\"M19.79 16.5v.01\" />\n  <path d=\"M21 12v.01\" />\n  <path d=\"M19.79 7.5v.01\" />\n  <path d=\"M16.5 4.21v.01\" />\n  <path d=\"M12 3v.01\" /></g>"
} as const satisfies IconData;

export default tbCircleDottedLetterQ;
export { tbCircleDottedLetterQ };
export { tbCircleDottedLetterQ as tablerCircleDottedLetterQ };
