// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCircleLetterA = {
	"name": "circle-letter-a",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />\n  <path d=\"M10 16v-6a2 2 0 1 1 4 0v6\" />\n  <path d=\"M10 13h4\" /></g>"
} as const satisfies IconData;

export default tbCircleLetterA;
export { tbCircleLetterA };
export { tbCircleLetterA as tablerCircleLetterA };
