// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCircuitBattery = {
	"name": "circuit-battery",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 12h4\" />\n  <path d=\"M18 12h4\" />\n  <path d=\"M18 5v14\" />\n  <path d=\"M14 9v6\" />\n  <path d=\"M10 5v14\" />\n  <path d=\"M6 9v6\" /></g>"
} as const satisfies IconData;

export default tbCircuitBattery;
export { tbCircuitBattery };
export { tbCircuitBattery as tablerCircuitBattery };
