// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbClock24 = {
	"name": "clock-24",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 0 0 5.998 8.485m12.002 -8.485a9 9 0 1 0 -18 0\" />\n  <path d=\"M12 7v5\" />\n  <path d=\"M12 15h2a1 1 0 0 1 1 1v1a1 1 0 0 1 -1 1h-1a1 1 0 0 0 -1 1v1a1 1 0 0 0 1 1h2\" />\n  <path d=\"M18 15v2a1 1 0 0 0 1 1h1\" />\n  <path d=\"M21 15v6\" /></g>"
} as const satisfies IconData;

export default tbClock24;
export { tbClock24 };
export { tbClock24 as tablerClock24 };
