// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbConePlus = {
	"name": "cone-plus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18.03 12.022l-5.16 -9.515a1 1 0 0 0 -1.74 0l-8.13 14.99v.5c0 1.66 4.03 3.003 9 3.003c.17 0 .34 -.002 .508 -.005\" />\n  <path d=\"M16 19h6\" />\n  <path d=\"M19 16v6\" /></g>"
} as const satisfies IconData;

export default tbConePlus;
export { tbConePlus };
export { tbConePlus as tablerConePlus };
