// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbConnection = {
	"name": "connection",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 6.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0\" />\n  <path d=\"M4 17.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0\" />\n  <path d=\"M8.5 15.5l7 -7\" /></g>"
} as const satisfies IconData;

export default tbConnection;
export { tbConnection };
export { tbConnection as tablerConnection };
