// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCornerUpRight = {
	"name": "corner-up-right",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 18v-6a3 3 0 0 1 3 -3h10l-4 -4m0 8l4 -4\" /></g>"
} as const satisfies IconData;

export default tbCornerUpRight;
export { tbCornerUpRight };
export { tbCornerUpRight as tablerCornerUpRight };
