// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCornerLeftUp = {
	"name": "corner-left-up",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 18h-6a3 3 0 0 1 -3 -3v-10l-4 4m8 0l-4 -4\" /></g>"
} as const satisfies IconData;

export default tbCornerLeftUp;
export { tbCornerLeftUp };
export { tbCornerLeftUp as tablerCornerLeftUp };
