// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCreditCardPay = {
	"name": "credit-card-pay",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 19h-6a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v4.5\" />\n  <path d=\"M3 10h18\" />\n  <path d=\"M16 19h6\" />\n  <path d=\"M19 16l3 3l-3 3\" />\n  <path d=\"M7.005 15h.005\" />\n  <path d=\"M11 15h2\" /></g>"
} as const satisfies IconData;

export default tbCreditCardPay;
export { tbCreditCardPay };
export { tbCreditCardPay as tablerCreditCardPay };
