// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCross = {
	"name": "cross",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 21h4v-9h5v-4h-5v-5h-4v5h-5v4h5l0 9\" /></g>"
} as const satisfies IconData;

export default tbCross;
export { tbCross };
export { tbCross as tablerCross };
