// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCube3dSphere = {
	"name": "cube-3d-sphere",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 17.6l-2 -1.1v-2.5\" />\n  <path d=\"M4 10v-2.5l2 -1.1\" />\n  <path d=\"M10 4.1l2 -1.1l2 1.1\" />\n  <path d=\"M18 6.4l2 1.1v2.5\" />\n  <path d=\"M20 14v2.5l-2 1.12\" />\n  <path d=\"M14 19.9l-2 1.1l-2 -1.1\" />\n  <path d=\"M12 12l2 -1.1\" />\n  <path d=\"M18 8.6l2 -1.1\" />\n  <path d=\"M12 12l0 2.5\" />\n  <path d=\"M12 18.5l0 2.5\" />\n  <path d=\"M12 12l-2 -1.12\" />\n  <path d=\"M6 8.6l-2 -1.1\" /></g>"
} as const satisfies IconData;

export default tbCube3dSphere;
export { tbCube3dSphere };
export { tbCube3dSphere as tablerCube3dSphere };
