// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCubeUnfolded = {
	"name": "cube-unfolded",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 15h10v5h5v-5h5v-5h-10v-5h-5v5h-5l0 5\" />\n  <path d=\"M7 15v-5h5v5h5v-5\" /></g>"
} as const satisfies IconData;

export default tbCubeUnfolded;
export { tbCubeUnfolded };
export { tbCubeUnfolded as tablerCubeUnfolded };
