// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCurrencyNano = {
	"name": "currency-nano",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7 20l10 -16\" />\n  <path d=\"M7 12h10\" />\n  <path d=\"M7 16h10\" />\n  <path d=\"M17 20l-10 -16\" /></g>"
} as const satisfies IconData;

export default tbCurrencyNano;
export { tbCurrencyNano };
export { tbCurrencyNano as tablerCurrencyNano };
