// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCurrentLocation = {
	"name": "current-location",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M4 12a8 8 0 1 0 16 0a8 8 0 1 0 -16 0\" />\n  <path d=\"M12 2l0 2\" />\n  <path d=\"M12 20l0 2\" />\n  <path d=\"M20 12l2 0\" />\n  <path d=\"M2 12l2 0\" /></g>"
} as const satisfies IconData;

export default tbCurrentLocation;
export { tbCurrentLocation };
export { tbCurrentLocation as tablerCurrentLocation };
