// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCurrencyHryvnia = {
	"name": "currency-hryvnia",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 7a2.64 2.64 0 0 1 2.562 -2h3.376a2.64 2.64 0 0 1 2.562 2a2.57 2.57 0 0 1 -1.344 2.922l-5.876 2.938a3.338 3.338 0 0 0 -1.78 3.64a3.11 3.11 0 0 0 3.05 2.5h2.888a2.64 2.64 0 0 0 2.562 -2\" />\n  <path d=\"M6 10h12\" />\n  <path d=\"M6 14h12\" /></g>"
} as const satisfies IconData;

export default tbCurrencyHryvnia;
export { tbCurrencyHryvnia };
export { tbCurrencyHryvnia as tablerCurrencyHryvnia };
