// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCursorOff = {
	"name": "cursor-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 4a3 3 0 0 1 3 3v1m0 9a3 3 0 0 1 -3 3\" />\n  <path d=\"M15 4a3 3 0 0 0 -3 3v1m0 4v5a3 3 0 0 0 3 3\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbCursorOff;
export { tbCursorOff };
export { tbCursorOff as tablerCursorOff };
