// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCut = {
	"name": "cut",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M14 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M9.15 14.85l8.85 -10.85\" />\n  <path d=\"M6 4l8.85 10.85\" /></g>"
} as const satisfies IconData;

export default tbCut;
export { tbCut };
export { tbCut as tablerCut };
