// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbCylinderPlus = {
	"name": "cylinder-plus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 6a7 3 0 1 0 14 0a7 3 0 1 0 -14 0\" />\n  <path d=\"M5 6v12c0 1.657 3.134 3 7 3c.173 0 .345 -.003 .515 -.008m6.485 -8.992v-6\" />\n  <path d=\"M16 19h6\" />\n  <path d=\"M19 16v6\" /></g>"
} as const satisfies IconData;

export default tbCylinderPlus;
export { tbCylinderPlus };
export { tbCylinderPlus as tablerCylinderPlus };
