// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDatabasePlus = {
	"name": "database-plus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6c0 1.657 3.582 3 8 3s8 -1.343 8 -3s-3.582 -3 -8 -3s-8 1.343 -8 3\" />\n  <path d=\"M4 6v6c0 1.657 3.582 3 8 3c1.075 0 2.1 -.08 3.037 -.224\" />\n  <path d=\"M20 12v-6\" />\n  <path d=\"M4 12v6c0 1.657 3.582 3 8 3c.166 0 .331 -.002 .495 -.006\" />\n  <path d=\"M16 19h6\" />\n  <path d=\"M19 16v6\" /></g>"
} as const satisfies IconData;

export default tbDatabasePlus;
export { tbDatabasePlus };
export { tbDatabasePlus as tablerDatabasePlus };
