// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDatabaseShare = {
	"name": "database-share",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6c0 1.657 3.582 3 8 3s8 -1.343 8 -3s-3.582 -3 -8 -3s-8 1.343 -8 3\" />\n  <path d=\"M4 6v6c0 1.657 3.582 3 8 3c.361 0 .716 -.009 1.065 -.026\" />\n  <path d=\"M20 13v-7\" />\n  <path d=\"M4 12v6c0 1.657 3.582 3 8 3\" />\n  <path d=\"M16 22l5 -5\" />\n  <path d=\"M21 21.5v-4.5h-4.5\" /></g>"
} as const satisfies IconData;

export default tbDatabaseShare;
export { tbDatabaseShare };
export { tbDatabaseShare as tablerDatabaseShare };
