// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDatabaseX = {
	"name": "database-x",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6c0 1.657 3.582 3 8 3s8 -1.343 8 -3s-3.582 -3 -8 -3s-8 1.343 -8 3\" />\n  <path d=\"M4 6v6c0 1.657 3.582 3 8 3c.537 0 1.062 -.02 1.57 -.058\" />\n  <path d=\"M20 13.5v-7.5\" />\n  <path d=\"M4 12v6c0 1.657 3.582 3 8 3c.384 0 .762 -.01 1.132 -.03\" />\n  <path d=\"M22 22l-5 -5\" />\n  <path d=\"M17 22l5 -5\" /></g>"
} as const satisfies IconData;

export default tbDatabaseX;
export { tbDatabaseX };
export { tbDatabaseX as tablerDatabaseX };
