// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceComputerCamera2 = {
	"name": "device-computer-camera-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 14h-10a4 4 0 0 1 -4 -4a4 4 0 0 1 4 -4h10a4 4 0 0 1 4 4a4 4 0 0 1 -4 4\" />\n  <path d=\"M15 14h-6v4h6v-4\" />\n  <path d=\"M17 18h-10\" />\n  <path d=\"M12 10.02v.01\" /></g>"
} as const satisfies IconData;

export default tbDeviceComputerCamera2;
export { tbDeviceComputerCamera2 };
export { tbDeviceComputerCamera2 as tablerDeviceComputerCamera2 };
