// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceTabletQuestion = {
	"name": "device-tablet-question",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 21h-9a1 1 0 0 1 -1 -1v-16a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v7\" />\n  <path d=\"M19 22v.01\" />\n  <path d=\"M19 19a2.003 2.003 0 0 0 .914 -3.782a1.98 1.98 0 0 0 -2.414 .483\" />\n  <path d=\"M11 17a1 1 0 1 0 2 0a1 1 0 0 0 -2 0\" /></g>"
} as const satisfies IconData;

export default tbDeviceTabletQuestion;
export { tbDeviceTabletQuestion };
export { tbDeviceTabletQuestion as tablerDeviceTabletQuestion };
