// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceMobilePause = {
	"name": "device-mobile-pause",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 21h-5a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8\" />\n  <path d=\"M17 17v5\" />\n  <path d=\"M21 17v5\" />\n  <path d=\"M11 4h2\" />\n  <path d=\"M12 17v.01\" /></g>"
} as const satisfies IconData;

export default tbDeviceMobilePause;
export { tbDeviceMobilePause };
export { tbDeviceMobilePause as tablerDeviceMobilePause };
