// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceMobileMinus = {
	"name": "device-mobile-minus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.5 21h-4.5a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v10\" />\n  <path d=\"M11 4h2\" />\n  <path d=\"M12 17v.01\" />\n  <path d=\"M16 19h6\" /></g>"
} as const satisfies IconData;

export default tbDeviceMobileMinus;
export { tbDeviceMobileMinus };
export { tbDeviceMobileMinus as tablerDeviceMobileMinus };
