// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceAirpodsCase = {
	"name": "device-airpods-case",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 10h-18\" />\n  <path d=\"M3 8a4 4 0 0 1 4 -4h10a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-10a4 4 0 0 1 -4 -4l0 -8\" />\n  <path d=\"M7 10v1.5a1.5 1.5 0 0 0 1.5 1.5h7a1.5 1.5 0 0 0 1.5 -1.5v-1.5\" /></g>"
} as const satisfies IconData;

export default tbDeviceAirpodsCase;
export { tbDeviceAirpodsCase };
export { tbDeviceAirpodsCase as tablerDeviceAirpodsCase };
