// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceImacShare = {
	"name": "device-imac-share",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.5 17h-8.5a1 1 0 0 1 -1 -1v-12a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v9\" />\n  <path d=\"M3 13h18\" />\n  <path d=\"M8 21h4\" />\n  <path d=\"M10 17l-.5 4\" />\n  <path d=\"M16 22l5 -5\" />\n  <path d=\"M21 21.5v-4.5h-4.5\" /></g>"
} as const satisfies IconData;

export default tbDeviceImacShare;
export { tbDeviceImacShare };
export { tbDeviceImacShare as tablerDeviceImacShare };
