// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDevicesPc = {
	"name": "devices-pc",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 5h6v14h-6l0 -14\" />\n  <path d=\"M12 9h10v7h-10l0 -7\" />\n  <path d=\"M14 19h6\" />\n  <path d=\"M17 16v3\" />\n  <path d=\"M6 13v.01\" />\n  <path d=\"M6 16v.01\" /></g>"
} as const satisfies IconData;

export default tbDevicesPc;
export { tbDevicesPc };
export { tbDevicesPc as tablerDevicesPc };
