// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDevicesPause = {
	"name": "devices-pause",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 19v-10a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1v4\" />\n  <path d=\"M18 8v-3a1 1 0 0 0 -1 -1h-13a1 1 0 0 0 -1 1v12a1 1 0 0 0 1 1h9\" />\n  <path d=\"M17 17v5\" />\n  <path d=\"M21 17v5\" />\n  <path d=\"M16 9h2\" /></g>"
} as const satisfies IconData;

export default tbDevicesPause;
export { tbDevicesPause };
export { tbDevicesPause as tablerDevicesPause };
