// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDevicesPcOff = {
	"name": "devices-pc-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 9v10h-6v-14h2\" />\n  <path d=\"M13 9h9v7h-2m-4 0h-4v-4\" />\n  <path d=\"M14 19h5\" />\n  <path d=\"M17 17v2\" />\n  <path d=\"M6 13v.01\" />\n  <path d=\"M6 16v.01\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbDevicesPcOff;
export { tbDevicesPcOff };
export { tbDevicesPcOff as tablerDevicesPcOff };
