// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDeviceDesktopAnalytics = {
	"name": "device-desktop-analytics",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 5a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1l0 -10\" />\n  <path d=\"M7 20h10\" />\n  <path d=\"M9 16v4\" />\n  <path d=\"M15 16v4\" />\n  <path d=\"M9 12v-4\" />\n  <path d=\"M12 12v-1\" />\n  <path d=\"M15 12v-2\" />\n  <path d=\"M12 12v-1\" /></g>"
} as const satisfies IconData;

export default tbDeviceDesktopAnalytics;
export { tbDeviceDesktopAnalytics };
export { tbDeviceDesktopAnalytics as tablerDeviceDesktopAnalytics };
