// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDragDrop2 = {
	"name": "drag-drop-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 10a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -8\" />\n  <path d=\"M4 4l0 .01\" />\n  <path d=\"M8 4l0 .01\" />\n  <path d=\"M12 4l0 .01\" />\n  <path d=\"M16 4l0 .01\" />\n  <path d=\"M4 8l0 .01\" />\n  <path d=\"M4 12l0 .01\" />\n  <path d=\"M4 16l0 .01\" /></g>"
} as const satisfies IconData;

export default tbDragDrop2;
export { tbDragDrop2 };
export { tbDragDrop2 as tablerDragDrop2 };
