// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbDualScreen = {
	"name": "dual-screen",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 4l8 3v15l-8 -3l0 -15\" />\n  <path d=\"M13 19h6v-15h-14\" /></g>"
} as const satisfies IconData;

export default tbDualScreen;
export { tbDualScreen };
export { tbDualScreen as tablerDualScreen };
