// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbEyeExclamation = {
	"name": "eye-exclamation",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" />\n  <path d=\"M15.03 17.478a8.797 8.797 0 0 1 -3.03 .522c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6a20.48 20.48 0 0 1 -.258 .419\" />\n  <path d=\"M19 16v3\" />\n  <path d=\"M19 22v.01\" /></g>"
} as const satisfies IconData;

export default tbEyeExclamation;
export { tbEyeExclamation };
export { tbEyeExclamation as tablerEyeExclamation };
