// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbEyeTable = {
	"name": "eye-table",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 18h-.011\" />\n  <path d=\"M12 18h-.011\" />\n  <path d=\"M16 18h-.011\" />\n  <path d=\"M4 3h16\" />\n  <path d=\"M5 3v17a1 1 0 0 0 1 1h12a1 1 0 0 0 1 -1v-17\" />\n  <path d=\"M14 7h-4\" />\n  <path d=\"M9 15h1\" />\n  <path d=\"M14 15h1\" />\n  <path d=\"M12 11v-4\" /></g>"
} as const satisfies IconData;

export default tbEyeTable;
export { tbEyeTable };
export { tbEyeTable as tablerEyeTable };
