// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFaceMaskOff = {
	"name": "face-mask-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 14.5h-.222c-1.535 0 -2.778 -1.12 -2.778 -2.5s1.243 -2.5 2.778 -2.5h.222\" />\n  <path d=\"M19 14.5h.222c1.534 0 2.778 -1.12 2.778 -2.5s-1.244 -2.5 -2.778 -2.5h-.222\" />\n  <path d=\"M9 10h1m4 0h1\" />\n  <path d=\"M9 14h5\" />\n  <path d=\"M19 15v-6.49a2 2 0 0 0 -1.45 -1.923l-5 -1.429a2 2 0 0 0 -1.1 0l-1.788 .511m-3.118 .891l-.094 .027a2 2 0 0 0 -1.45 1.922v6.982a2 2 0 0 0 1.45 1.923l5 1.429a2 2 0 0 0 1.1 0l4.899 -1.4\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbFaceMaskOff;
export { tbFaceMaskOff };
export { tbFaceMaskOff as tablerFaceMaskOff };
