// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFileTypePdf = {
	"name": "file-type-pdf",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 3v4a1 1 0 0 0 1 1h4\" />\n  <path d=\"M5 12v-7a2 2 0 0 1 2 -2h7l5 5v4\" />\n  <path d=\"M5 18h1.5a1.5 1.5 0 0 0 0 -3h-1.5v6\" />\n  <path d=\"M17 18h2\" />\n  <path d=\"M20 15h-3v6\" />\n  <path d=\"M11 15v6h1a2 2 0 0 0 2 -2v-2a2 2 0 0 0 -2 -2h-1\" /></g>"
} as const satisfies IconData;

export default tbFileTypePdf;
export { tbFileTypePdf };
export { tbFileTypePdf as tablerFileTypePdf };
