// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFileIsr = {
	"name": "file-isr",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 3v4a1 1 0 0 0 1 1h4\" />\n  <path d=\"M15 3v4a1 1 0 0 0 1 1h4\" />\n  <path d=\"M6 8v-3a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-7\" />\n  <path d=\"M3 15l3 -3l3 3\" /></g>"
} as const satisfies IconData;

export default tbFileIsr;
export { tbFileIsr };
export { tbFileIsr as tablerFileIsr };
