// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFilterCheck = {
	"name": "filter-check",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11.18 20.274l-2.18 .726v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v3\" />\n  <path d=\"M15 19l2 2l4 -4\" /></g>"
} as const satisfies IconData;

export default tbFilterCheck;
export { tbFilterCheck };
export { tbFilterCheck as tablerFilterCheck };
