// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFilter2Share = {
	"name": "filter-2-share",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6h16\" />\n  <path d=\"M6 12h12\" />\n  <path d=\"M9 18h3.5\" />\n  <path d=\"M16 22l5 -5\" />\n  <path d=\"M21 17v4.5\" />\n  <path d=\"M21 17h-4.5\" /></g>"
} as const satisfies IconData;

export default tbFilter2Share;
export { tbFilter2Share };
export { tbFilter2Share as tablerFilter2Share };
