// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbFrameOff = {
	"name": "frame-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 7h3m4 0h9\" />\n  <path d=\"M4 17h13\" />\n  <path d=\"M7 7v13\" />\n  <path d=\"M17 4v9m0 4v3\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbFrameOff;
export { tbFrameOff };
export { tbFrameOff as tablerFrameOff };
