// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbGeometry = {
	"name": "geometry",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7 21l4 -12m2 0l1.48 4.439m.949 2.847l1.571 4.714\" />\n  <path d=\"M10 7a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M4 12c1.526 2.955 4.588 5 8 5c3.41 0 6.473 -2.048 8 -5\" />\n  <path d=\"M12 5v-2\" /></g>"
} as const satisfies IconData;

export default tbGeometry;
export { tbGeometry };
export { tbGeometry as tablerGeometry };
