// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbGizmo = {
	"name": "gizmo",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 19l-8 -5.5l-8 5.5\" />\n  <path d=\"M12 4v9.5\" />\n  <path d=\"M11 4a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M3 19a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M19 19a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /></g>"
} as const satisfies IconData;

export default tbGizmo;
export { tbGizmo };
export { tbGizmo as tablerGizmo };
