// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbH1 = {
	"name": "h-1",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 18v-8l-2 2\" />\n  <path d=\"M4 6v12\" />\n  <path d=\"M12 6v12\" />\n  <path d=\"M11 18h2\" />\n  <path d=\"M3 18h2\" />\n  <path d=\"M4 12h8\" />\n  <path d=\"M3 6h2\" />\n  <path d=\"M11 6h2\" /></g>"
} as const satisfies IconData;

export default tbH1;
export { tbH1 };
export { tbH1 as tablerH1 };
