// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHeartPlus = {
	"name": "heart-plus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 20l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.96 6.053\" />\n  <path d=\"M16 19h6\" />\n  <path d=\"M19 16v6\" /></g>"
} as const satisfies IconData;

export default tbHeartPlus;
export { tbHeartPlus };
export { tbHeartPlus as tablerHeartPlus };
