// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHomeRibbon = {
	"name": "home-ribbon",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 15h5v7l-2.5 -1.5l-2.5 1.5l0 -7\" />\n  <path d=\"M20 11l-8 -8l-9 9h2v7a2 2 0 0 0 2 2h5\" />\n  <path d=\"M9 21v-6a2 2 0 0 1 2 -2h1.5\" /></g>"
} as const satisfies IconData;

export default tbHomeRibbon;
export { tbHomeRibbon };
export { tbHomeRibbon as tablerHomeRibbon };
