// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHttpTrace = {
	"name": "http-trace",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 8h4\" />\n  <path d=\"M5 8v8\" />\n  <path d=\"M10 12h2a2 2 0 1 0 0 -4h-2v8\" />\n  <path d=\"M14 16l-3 -4\" />\n  <path d=\"M17 16v-6a2 2 0 1 1 4 0v6\" />\n  <path d=\"M17 13h4\" /></g>"
} as const satisfies IconData;

export default tbHttpTrace;
export { tbHttpTrace };
export { tbHttpTrace as tablerHttpTrace };
