// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHttpPutOff = {
	"name": "http-put-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12h2a2 2 0 1 0 0 -4h-2v8\" />\n  <path d=\"M17 8h4\" />\n  <path d=\"M19 8v8\" />\n  <path d=\"M10 10v4a2 2 0 1 0 4 0m0 -4v-2\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbHttpPutOff;
export { tbHttpPutOff };
export { tbHttpPutOff as tablerHttpPutOff };
