// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHttpPut = {
	"name": "http-put",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12h2a2 2 0 1 0 0 -4h-2v8\" />\n  <path d=\"M17 8h4\" />\n  <path d=\"M19 8v8\" />\n  <path d=\"M10 8v6a2 2 0 1 0 4 0v-6\" /></g>"
} as const satisfies IconData;

export default tbHttpPut;
export { tbHttpPut };
export { tbHttpPut as tablerHttpPut };
