// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbHttpHeadOff = {
	"name": "http-head-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 16v-8\" />\n  <path d=\"M7 8v8\" />\n  <path d=\"M3 12h4\" />\n  <path d=\"M14 8h-2m-2 2v6h4\" />\n  <path d=\"M10 12h2\" />\n  <path d=\"M17 13v-3a2 2 0 1 1 4 0v6\" />\n  <path d=\"M17 13h4\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbHttpHeadOff;
export { tbHttpHeadOff };
export { tbHttpHeadOff as tablerHttpHeadOff };
