// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbIndentIncrease = {
	"name": "indent-increase",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 6l-11 0\" />\n  <path d=\"M20 12l-7 0\" />\n  <path d=\"M20 18l-11 0\" />\n  <path d=\"M4 8l4 4l-4 4\" /></g>"
} as const satisfies IconData;

export default tbIndentIncrease;
export { tbIndentIncrease };
export { tbIndentIncrease as tablerIndentIncrease };
