// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbInnerShadowBottomLeft = {
	"name": "inner-shadow-bottom-left",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />\n  <path d=\"M6 12a6 6 0 0 0 6 6\" /></g>"
} as const satisfies IconData;

export default tbInnerShadowBottomLeft;
export { tbInnerShadowBottomLeft };
export { tbInnerShadowBottomLeft as tablerInnerShadowBottomLeft };
