// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbJetpack = {
	"name": "jetpack",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 6a3 3 0 1 0 -6 0v7h6v-7\" />\n  <path d=\"M14 13h6v-7a3 3 0 0 0 -6 0v7\" />\n  <path d=\"M5 16c0 2.333 .667 4 2 5c1.333 -1 2 -2.667 2 -5\" />\n  <path d=\"M15 16c0 2.333 .667 4 2 5c1.333 -1 2 -2.667 2 -5\" />\n  <path d=\"M10 8h4\" />\n  <path d=\"M10 11h4\" /></g>"
} as const satisfies IconData;

export default tbJetpack;
export { tbJetpack };
export { tbJetpack as tablerJetpack };
