// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLayoutAlignLeft = {
	"name": "layout-align-left",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 4l0 16\" />\n  <path d=\"M8 11a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -2\" /></g>"
} as const satisfies IconData;

export default tbLayoutAlignLeft;
export { tbLayoutAlignLeft };
export { tbLayoutAlignLeft as tablerLayoutAlignLeft };
