// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLemon = {
	"name": "lemon",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17.536 3.393c3.905 3.906 3.905 10.237 0 14.143c-3.906 3.905 -10.237 3.905 -14.143 0l14.143 -14.143\" />\n  <path d=\"M5.868 15.06a6.5 6.5 0 0 0 9.193 -9.192\" />\n  <path d=\"M10.464 10.464l4.597 4.597\" />\n  <path d=\"M10.464 10.464v6.364\" />\n  <path d=\"M10.464 10.464h6.364\" /></g>"
} as const satisfies IconData;

export default tbLemon;
export { tbLemon };
export { tbLemon as tablerLemon };
