// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLetterFSmall = {
	"name": "letter-f-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 12h3\" />\n  <path d=\"M14 8h-4v8\" /></g>"
} as const satisfies IconData;

export default tbLetterFSmall;
export { tbLetterFSmall };
export { tbLetterFSmall as tablerLetterFSmall };
