// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLetterISmall = {
	"name": "letter-i-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 8v8\" /></g>"
} as const satisfies IconData;

export default tbLetterISmall;
export { tbLetterISmall };
export { tbLetterISmall as tablerLetterISmall };
