// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLicenseOff = {
	"name": "license-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 21h-9a3 3 0 0 1 -3 -3v-1h10v2a2 2 0 1 0 4 0v-2m0 -4v-8a2 2 0 1 1 2 2h-2m2 -4h-11a3 3 0 0 0 -.864 .126m-2.014 2.025a3 3 0 0 0 -.122 .849v11\" />\n  <path d=\"M11 7h2\" />\n  <path d=\"M9 11h2\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbLicenseOff;
export { tbLicenseOff };
export { tbLicenseOff as tablerLicenseOff };
