// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLicense = {
	"name": "license",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 21h-9a3 3 0 0 1 -3 -3v-1h10v2a2 2 0 0 0 4 0v-14a2 2 0 1 1 2 2h-2m2 -4h-11a3 3 0 0 0 -3 3v11\" />\n  <path d=\"M9 7l4 0\" />\n  <path d=\"M9 11l4 0\" /></g>"
} as const satisfies IconData;

export default tbLicense;
export { tbLicense };
export { tbLicense as tablerLicense };
