// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbLogicNand = {
	"name": "logic-nand",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 12h-3\" />\n  <path d=\"M2 9h3\" />\n  <path d=\"M2 15h3\" />\n  <path d=\"M7 5c6 0 8 3.5 8 7s-2 7 -8 7h-2v-14h2\" />\n  <path d=\"M15 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /></g>"
} as const satisfies IconData;

export default tbLogicNand;
export { tbLogicNand };
export { tbLogicNand as tablerLogicNand };
