// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMailOff = {
	"name": "mail-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 5h10a2 2 0 0 1 2 2v10m-2 2h-14a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2\" />\n  <path d=\"M3 7l9 6l.565 -.377m2.435 -1.623l6 -4\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbMailOff;
export { tbMailOff };
export { tbMailOff as tablerMailOff };
