// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMapExclamation = {
	"name": "map-exclamation",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 20l-6 -3l-6 3v-13l6 -3l6 3l6 -3v8.5\" />\n  <path d=\"M9 4v13\" />\n  <path d=\"M15 7v13\" />\n  <path d=\"M19 16v3\" />\n  <path d=\"M19 22v.01\" /></g>"
} as const satisfies IconData;

export default tbMapExclamation;
export { tbMapExclamation };
export { tbMapExclamation as tablerMapExclamation };
