// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMapOff = {
	"name": "map-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8.32 4.34l.68 -.34l6 3l6 -3v13m-2.67 1.335l-3.33 1.665l-6 -3l-6 3v-13l2.665 -1.333\" />\n  <path d=\"M9 4v1m0 4v8\" />\n  <path d=\"M15 7v4m0 4v5\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbMapOff;
export { tbMapOff };
export { tbMapOff as tablerMapOff };
