// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMapBolt = {
	"name": "map-bolt",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 19l-4 -2l-6 3v-13l6 -3l6 3l6 -3v8.5\" />\n  <path d=\"M9 4v13\" />\n  <path d=\"M15 7v7.5\" />\n  <path d=\"M19 16l-2 3h4l-2 3\" /></g>"
} as const satisfies IconData;

export default tbMapBolt;
export { tbMapBolt };
export { tbMapBolt as tablerMapBolt };
