// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMathOff = {
	"name": "math-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 19l2.5 -2.5\" />\n  <path d=\"M18.5 14.5l1.5 -1.5\" />\n  <path d=\"M3 3l18 18\" />\n  <path d=\"M19 5h-7l-.646 2.262\" />\n  <path d=\"M10.448 10.431l-2.448 8.569l-3 -6h-2\" /></g>"
} as const satisfies IconData;

export default tbMathOff;
export { tbMathOff };
export { tbMathOff as tablerMathOff };
