// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMessageOff = {
	"name": "message-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 9h1m4 0h3\" />\n  <path d=\"M8 13h5\" />\n  <path d=\"M8 4h10a3 3 0 0 1 3 3v8c0 .577 -.163 1.116 -.445 1.573m-2.555 1.427h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8c0 -1.085 .576 -2.036 1.439 -2.562\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbMessageOff;
export { tbMessageOff };
export { tbMessageOff as tablerMessageOff };
