// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMessage2Minus = {
	"name": "message-2-minus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 9h8\" />\n  <path d=\"M8 13h6\" />\n  <path d=\"M12 21l-3 -3h-3a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v8\" />\n  <path d=\"M16 19h6\" /></g>"
} as const satisfies IconData;

export default tbMessage2Minus;
export { tbMessage2Minus };
export { tbMessage2Minus as tablerMessage2Minus };
