// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMilk = {
	"name": "milk",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 6h8v-2a1 1 0 0 0 -1 -1h-6a1 1 0 0 0 -1 1v2\" />\n  <path d=\"M16 6l1.094 1.759a6 6 0 0 1 .906 3.17v8.071a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-8.071a6 6 0 0 1 .906 -3.17l1.094 -1.759\" />\n  <path d=\"M10 16a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M10 10h4\" /></g>"
} as const satisfies IconData;

export default tbMilk;
export { tbMilk };
export { tbMilk as tablerMilk };
