// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMinimize = {
	"name": "minimize",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 19v-2a2 2 0 0 1 2 -2h2\" />\n  <path d=\"M15 5v2a2 2 0 0 0 2 2h2\" />\n  <path d=\"M5 15h2a2 2 0 0 1 2 2v2\" />\n  <path d=\"M5 9h2a2 2 0 0 0 2 -2v-2\" /></g>"
} as const satisfies IconData;

export default tbMinimize;
export { tbMinimize };
export { tbMinimize as tablerMinimize };
