// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMoodLookDown = {
	"name": "mood-look-down",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0\" />\n  <path d=\"M9 13h.01\" />\n  <path d=\"M15 13h.01\" />\n  <path d=\"M11 17h2\" /></g>"
} as const satisfies IconData;

export default tbMoodLookDown;
export { tbMoodLookDown };
export { tbMoodLookDown as tablerMoodLookDown };
