// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMoodSick = {
	"name": "mood-sick",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 21a9 9 0 1 1 0 -18a9 9 0 0 1 0 18\" />\n  <path d=\"M9 10h-.01\" />\n  <path d=\"M15 10h-.01\" />\n  <path d=\"M8 16l1 -1l1.5 1l1.5 -1l1.5 1l1.5 -1l1 1\" /></g>"
} as const satisfies IconData;

export default tbMoodSick;
export { tbMoodSick };
export { tbMoodSick as tablerMoodSick };
