// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMoodSadSquint = {
	"name": "mood-sad-squint",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />\n  <path d=\"M14.5 16.05a3.5 3.5 0 0 0 -5 0\" />\n  <path d=\"M8.5 11.5l1.5 -1.5l-1.5 -1.5\" />\n  <path d=\"M15.5 11.5l-1.5 -1.5l1.5 -1.5\" /></g>"
} as const satisfies IconData;

export default tbMoodSadSquint;
export { tbMoodSadSquint };
export { tbMoodSadSquint as tablerMoodSadSquint };
