// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbMusicShare = {
	"name": "music-share",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 17a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" />\n  <path d=\"M9 17v-13h10v9\" />\n  <path d=\"M9 8h10\" />\n  <path d=\"M16 22l5 -5\" />\n  <path d=\"M21 21.5v-4.5h-4.5\" /></g>"
} as const satisfies IconData;

export default tbMusicShare;
export { tbMusicShare };
export { tbMusicShare as tablerMusicShare };
