// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNavigationDiscount = {
	"name": "navigation-discount",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16.43 12.603l-4.43 -9.603l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.272 .431\" />\n  <path d=\"M16 21l5 -5\" />\n  <path d=\"M21 21v.01\" />\n  <path d=\"M16 16v.01\" /></g>"
} as const satisfies IconData;

export default tbNavigationDiscount;
export { tbNavigationDiscount };
export { tbNavigationDiscount as tablerNavigationDiscount };
