// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber10Small = {
	"name": "number-10-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 8h1v8\" />\n  <path d=\"M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0\" /></g>"
} as const satisfies IconData;

export default tbNumber10Small;
export { tbNumber10Small };
export { tbNumber10Small as tablerNumber10Small };
