// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber15Small = {
	"name": "number-15-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 8h1v8\" />\n  <path d=\"M13 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4\" /></g>"
} as const satisfies IconData;

export default tbNumber15Small;
export { tbNumber15Small };
export { tbNumber15Small as tablerNumber15Small };
