// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber49Small = {
	"name": "number-49-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3\" />\n  <path d=\"M6 8v3a1 1 0 0 0 1 1h3\" />\n  <path d=\"M10 8v8\" /></g>"
} as const satisfies IconData;

export default tbNumber49Small;
export { tbNumber49Small };
export { tbNumber49Small as tablerNumber49Small };
