// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber4 = {
	"name": "number-4",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 20v-15l-8 11h10\" /></g>"
} as const satisfies IconData;

export default tbNumber4;
export { tbNumber4 };
export { tbNumber4 as tablerNumber4 };
