// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber57Small = {
	"name": "number-57-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 8h4l-2 8\" />\n  <path d=\"M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4\" /></g>"
} as const satisfies IconData;

export default tbNumber57Small;
export { tbNumber57Small };
export { tbNumber57Small as tablerNumber57Small };
