// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNumber50Small = {
	"name": "number-50-small",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0\" />\n  <path d=\"M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4\" /></g>"
} as const satisfies IconData;

export default tbNumber50Small;
export { tbNumber50Small };
export { tbNumber50Small as tablerNumber50Small };
