// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbNurse = {
	"name": "nurse",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 5c2.941 0 6.685 1.537 9 3l-2 11h-14l-2 -11c2.394 -1.513 6.168 -3.005 9 -3\" />\n  <path d=\"M10 12h4\" />\n  <path d=\"M12 10v4\" /></g>"
} as const satisfies IconData;

export default tbNurse;
export { tbNurse };
export { tbNurse as tablerNurse };
