// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbOmega = {
	"name": "omega",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19h5v-1a7.35 7.35 0 1 1 6 0v1h5\" /></g>"
} as const satisfies IconData;

export default tbOmega;
export { tbOmega };
export { tbOmega as tablerOmega };
