// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPasswordUser = {
	"name": "password-user",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 17v4\" />\n  <path d=\"M10 20l4 -2\" />\n  <path d=\"M10 18l4 2\" />\n  <path d=\"M5 17v4\" />\n  <path d=\"M3 20l4 -2\" />\n  <path d=\"M3 18l4 2\" />\n  <path d=\"M19 17v4\" />\n  <path d=\"M17 20l4 -2\" />\n  <path d=\"M17 18l4 2\" />\n  <path d=\"M9 6a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" />\n  <path d=\"M7 14a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2\" /></g>"
} as const satisfies IconData;

export default tbPasswordUser;
export { tbPasswordUser };
export { tbPasswordUser as tablerPasswordUser };
