// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPencilBolt = {
	"name": "pencil-bolt",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4\" />\n  <path d=\"M13.5 6.5l4 4\" />\n  <path d=\"M19 16l-2 3h4l-2 3\" /></g>"
} as const satisfies IconData;

export default tbPencilBolt;
export { tbPencilBolt };
export { tbPencilBolt as tablerPencilBolt };
