// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPercentage66 = {
	"name": "percentage-66",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3a9 9 0 1 1 -7.795 13.498l7.795 -4.498v-9\" fill=\"currentColor\" stroke=\"none\" />\n  <path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0\" /></g>"
} as const satisfies IconData;

export default tbPercentage66;
export { tbPercentage66 };
export { tbPercentage66 as tablerPercentage66 };
