// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPhotoCode = {
	"name": "photo-code",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 8h.01\" />\n  <path d=\"M11.5 21h-5.5a3 3 0 0 1 -3 -3v-12a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v7\" />\n  <path d=\"M3 16l5 -5c.928 -.893 2.072 -.893 3 0l3 3\" />\n  <path d=\"M14 14l1 -1c.928 -.893 2.072 -.893 3 0\" />\n  <path d=\"M20 21l2 -2l-2 -2\" />\n  <path d=\"M17 17l-2 2l2 2\" /></g>"
} as const satisfies IconData;

export default tbPhotoCode;
export { tbPhotoCode };
export { tbPhotoCode as tablerPhotoCode };
