// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPhotoSensor3 = {
	"name": "photo-sensor-3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 4h1a2 2 0 0 1 2 2v1\" />\n  <path d=\"M20 17v1a2 2 0 0 1 -2 2h-1\" />\n  <path d=\"M7 20h-1a2 2 0 0 1 -2 -2v-1\" />\n  <path d=\"M4 7v-1a2 2 0 0 1 2 -2h1\" />\n  <path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M12 18v2\" />\n  <path d=\"M4 12h2\" />\n  <path d=\"M12 4v2\" />\n  <path d=\"M20 12h-2\" /></g>"
} as const satisfies IconData;

export default tbPhotoSensor3;
export { tbPhotoSensor3 };
export { tbPhotoSensor3 as tablerPhotoSensor3 };
