// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPilcrowLeft = {
	"name": "pilcrow-left",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11 9h-2a3 3 0 1 1 0 -6h7\" />\n  <path d=\"M11 3v11\" />\n  <path d=\"M15 3v11\" />\n  <path d=\"M3 18h18\" />\n  <path d=\"M6 15l-3 3l3 3\" /></g>"
} as const satisfies IconData;

export default tbPilcrowLeft;
export { tbPilcrowLeft };
export { tbPilcrowLeft as tablerPilcrowLeft };
