// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPray = {
	"name": "pray",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M7 20h8l-4 -4v-7l4 3l2 -2\" /></g>"
} as const satisfies IconData;

export default tbPray;
export { tbPray };
export { tbPray as tablerPray };
