// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbPresentationAnalytics = {
	"name": "presentation-analytics",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 12v-4\" />\n  <path d=\"M15 12v-2\" />\n  <path d=\"M12 12v-1\" />\n  <path d=\"M3 4h18\" />\n  <path d=\"M4 4v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-10\" />\n  <path d=\"M12 16v4\" />\n  <path d=\"M9 20h6\" /></g>"
} as const satisfies IconData;

export default tbPresentationAnalytics;
export { tbPresentationAnalytics };
export { tbPresentationAnalytics as tablerPresentationAnalytics };
