// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbReceiptRupee = {
	"name": "receipt-rupee",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2\" />\n  <path d=\"M15 7h-6h1a3 3 0 0 1 0 6h-1l3 3\" />\n  <path d=\"M9 10h6\" /></g>"
} as const satisfies IconData;

export default tbReceiptRupee;
export { tbReceiptRupee };
export { tbReceiptRupee as tablerReceiptRupee };
