// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbRewindForward20 = {
	"name": "rewind-forward-20",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5.007 16.478a6 6 0 0 1 3.993 -10.478h11\" />\n  <path d=\"M15 15.5v3a1.5 1.5 0 0 0 3 0v-3a1.5 1.5 0 0 0 -3 0\" />\n  <path d=\"M17 9l3 -3l-3 -3\" />\n  <path d=\"M9 14h2a1 1 0 0 1 1 1v1a1 1 0 0 1 -1 1h-1a1 1 0 0 0 -1 1v1a1 1 0 0 0 1 1h2\" /></g>"
} as const satisfies IconData;

export default tbRewindForward20;
export { tbRewindForward20 };
export { tbRewindForward20 as tablerRewindForward20 };
