// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbRoad = {
	"name": "road",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19l4 -14\" />\n  <path d=\"M16 5l4 14\" />\n  <path d=\"M12 8v-2\" />\n  <path d=\"M12 13v-2\" />\n  <path d=\"M12 18v-2\" /></g>"
} as const satisfies IconData;

export default tbRoad;
export { tbRoad };
export { tbRoad as tablerRoad };
