// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbRouteSquare2 = {
	"name": "route-square-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 5a2 2 0 0 0 -2 2v10a2 2 0 0 1 -2 2\" />\n  <path d=\"M3 17h4v4h-4l0 -4\" />\n  <path d=\"M17 3h4v4h-4l0 -4\" /></g>"
} as const satisfies IconData;

export default tbRouteSquare2;
export { tbRouteSquare2 };
export { tbRouteSquare2 as tablerRouteSquare2 };
