// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbRouterOff = {
	"name": "router-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 13h2a2 2 0 0 1 2 2v2m-.588 3.417c-.362 .36 -.861 .583 -1.412 .583h-14a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2h8\" />\n  <path d=\"M17 17v.01\" />\n  <path d=\"M13 17v.01\" />\n  <path d=\"M12.226 8.2a4 4 0 0 1 6.024 .55\" />\n  <path d=\"M9.445 5.407a8 8 0 0 1 12.055 1.093\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbRouterOff;
export { tbRouterOff };
export { tbRouterOff as tablerRouterOff };
