// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbShape = {
	"name": "shape",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M17 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M3 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M17 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M5 7l0 10\" />\n  <path d=\"M7 5l10 0\" />\n  <path d=\"M7 19l10 0\" />\n  <path d=\"M19 7l0 10\" /></g>"
} as const satisfies IconData;

export default tbShape;
export { tbShape };
export { tbShape as tablerShape };
