// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbShoppingCartPin = {
	"name": "shopping-cart-pin",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" />\n  <path d=\"M12 17h-6v-14h-2\" />\n  <path d=\"M6 5l14 1l-.716 5.011m-5.284 1.989h-8\" />\n  <path d=\"M21.121 20.121a3 3 0 1 0 -4.242 0c.418 .419 1.125 1.045 2.121 1.879c1.051 -.89 1.759 -1.516 2.121 -1.879\" />\n  <path d=\"M19 18v.01\" /></g>"
} as const satisfies IconData;

export default tbShoppingCartPin;
export { tbShoppingCartPin };
export { tbShoppingCartPin as tablerShoppingCartPin };
