// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbShoppingBagCheck = {
	"name": "shopping-bag-check",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11.5 21h-2.926a3 3 0 0 1 -2.965 -2.544l-1.255 -8.152a2 2 0 0 1 1.977 -2.304h11.339a2 2 0 0 1 1.977 2.304l-.5 3.248\" />\n  <path d=\"M9 11v-5a3 3 0 0 1 6 0v5\" />\n  <path d=\"M15 19l2 2l4 -4\" /></g>"
} as const satisfies IconData;

export default tbShoppingBagCheck;
export { tbShoppingBagCheck };
export { tbShoppingBagCheck as tablerShoppingBagCheck };
