// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbShoppingCartUp = {
	"name": "shopping-cart-up",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" />\n  <path d=\"M12.5 17h-6.5v-14h-2\" />\n  <path d=\"M6 5l14 1l-.854 5.977m-2.646 1.023h-10.5\" />\n  <path d=\"M19 22v-6\" />\n  <path d=\"M22 19l-3 -3l-3 3\" /></g>"
} as const satisfies IconData;

export default tbShoppingCartUp;
export { tbShoppingCartUp };
export { tbShoppingCartUp as tablerShoppingCartUp };
