// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbShovel = {
	"name": "shovel",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 4l3 3\" />\n  <path d=\"M18.5 5.5l-8 8\" />\n  <path d=\"M8.276 11.284l4.44 4.44a.968 .968 0 0 1 0 1.369l-2.704 2.704a4.108 4.108 0 0 1 -5.809 -5.81l2.704 -2.703a.968 .968 0 0 1 1.37 0l-.001 0\" /></g>"
} as const satisfies IconData;

export default tbShovel;
export { tbShovel };
export { tbShovel as tablerShovel };
