// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSlashes = {
	"name": "slashes",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 5l-10 14\" />\n  <path d=\"M20 5l-10 14\" /></g>"
} as const satisfies IconData;

export default tbSlashes;
export { tbSlashes };
export { tbSlashes as tablerSlashes };
