// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSocial = {
	"name": "social",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M3 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M17 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M9 14a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />\n  <path d=\"M12 7l0 4\" />\n  <path d=\"M6.7 17.8l2.8 -2\" />\n  <path d=\"M17.3 17.8l-2.8 -2\" /></g>"
} as const satisfies IconData;

export default tbSocial;
export { tbSocial };
export { tbSocial as tablerSocial };
