// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSortDescendingShapes = {
	"name": "sort-descending-shapes",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 15l3 3l3 -3\" />\n  <path d=\"M7 6v12\" />\n  <path d=\"M14 15a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-4\" />\n  <path d=\"M17 4l-3.5 6h7l-3.5 -6\" /></g>"
} as const satisfies IconData;

export default tbSortDescendingShapes;
export { tbSortDescendingShapes };
export { tbSortDescendingShapes as tablerSortDescendingShapes };
