// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSpace = {
	"name": "space",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 10v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1 -1v-3\" /></g>"
} as const satisfies IconData;

export default tbSpace;
export { tbSpace };
export { tbSpace as tablerSpace };
