// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSquareChevronLeft = {
	"name": "square-chevron-left",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 15l-3 -3l3 -3\" />\n  <path d=\"M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14\" /></g>"
} as const satisfies IconData;

export default tbSquareChevronLeft;
export { tbSquareChevronLeft };
export { tbSquareChevronLeft as tablerSquareChevronLeft };
