// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSunElectricity = {
	"name": "sun-electricity",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 12a4 4 0 0 0 4 4m0 -8a4 4 0 0 0 -4 4\" />\n  <path d=\"M3 12h1\" />\n  <path d=\"M12 3v1\" />\n  <path d=\"M12 20v1\" />\n  <path d=\"M5.6 5.6l.7 .7\" />\n  <path d=\"M6.3 17.7l-.7 .7\" />\n  <path d=\"M20 7l-3 5h4l-3 5\" /></g>"
} as const satisfies IconData;

export default tbSunElectricity;
export { tbSunElectricity };
export { tbSunElectricity as tablerSunElectricity };
