// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbSwitch3 = {
	"name": "switch-3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 17h2.397a5 5 0 0 0 4.096 -2.133l.177 -.253m3.66 -5.227l.177 -.254a5 5 0 0 1 4.096 -2.133h3.397\" />\n  <path d=\"M18 4l3 3l-3 3\" />\n  <path d=\"M3 7h2.397a5 5 0 0 1 4.096 2.133l4.014 5.734a5 5 0 0 0 4.096 2.133h3.397\" />\n  <path d=\"M18 20l3 -3l-3 -3\" /></g>"
} as const satisfies IconData;

export default tbSwitch3;
export { tbSwitch3 };
export { tbSwitch3 as tablerSwitch3 };
