// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTagsOff = {
	"name": "tags-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16.296 12.296l-5.71 -5.71\" />\n  <path d=\"M6 6h-1a2 2 0 0 0 -2 2v4.172a2 2 0 0 0 .586 1.414l5.71 5.71a2.41 2.41 0 0 0 3.408 0l3.278 -3.278\" />\n  <path d=\"M18 19l.496 -.496\" />\n  <path d=\"M20.384 16.367a4.822 4.822 0 0 0 -.792 -5.775l-4.592 -4.592\" />\n  <path d=\"M7 10h-.01\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbTagsOff;
export { tbTagsOff };
export { tbTagsOff as tablerTagsOff };
