// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTexture = {
	"name": "texture",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 3l-3 3\" />\n  <path d=\"M21 18l-3 3\" />\n  <path d=\"M11 3l-8 8\" />\n  <path d=\"M16 3l-13 13\" />\n  <path d=\"M21 3l-18 18\" />\n  <path d=\"M21 8l-13 13\" />\n  <path d=\"M21 13l-8 8\" /></g>"
} as const satisfies IconData;

export default tbTexture;
export { tbTexture };
export { tbTexture as tablerTexture };
