// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTextPlus = {
	"name": "text-plus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 10h-14\" />\n  <path d=\"M5 6h14\" />\n  <path d=\"M14 14h-9\" />\n  <path d=\"M5 18h6\" />\n  <path d=\"M18 15v6\" />\n  <path d=\"M15 18h6\" /></g>"
} as const satisfies IconData;

export default tbTextPlus;
export { tbTextPlus };
export { tbTextPlus as tablerTextPlus };
