// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTextOutline = {
	"name": "text-outline",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 8v-1a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v1\" />\n  <path d=\"M3 16v1a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-1\" />\n  <path d=\"M21.01 12h.01\" />\n  <path d=\"M3.01 12h.01\" />\n  <path d=\"M10 15v-4a2 2 0 1 1 4 0v4\" />\n  <path d=\"M10 13h4\" /></g>"
} as const satisfies IconData;

export default tbTextOutline;
export { tbTextOutline };
export { tbTextOutline as tablerTextOutline };
