// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbToolsKitchen2Off = {
	"name": "tools-kitchen-2-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14.386 10.409c.53 -2.28 1.766 -4.692 4.614 -7.409v12m-4 0h-1c0 -.313 0 -.627 0 -.941\" />\n  <path d=\"M19 19v2h-1v-3\" />\n  <path d=\"M8 8v13\" />\n  <path d=\"M5 5v2a3 3 0 0 0 4.546 2.572m1.454 -2.572v-3\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbToolsKitchen2Off;
export { tbToolsKitchen2Off };
export { tbToolsKitchen2Off as tablerToolsKitchen2Off };
