// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTopologyStarRing2 = {
	"name": "topology-star-ring-2",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 20a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M14 4a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M6 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M22 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M14 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M6 12h4\" />\n  <path d=\"M14 12h4\" />\n  <path d=\"M12 6v4\" />\n  <path d=\"M12 14v4\" />\n  <path d=\"M5.5 10.5l5 -5\" />\n  <path d=\"M13.5 5.5l5 5\" />\n  <path d=\"M18.5 13.5l-5 5\" />\n  <path d=\"M10.5 18.5l-5 -5\" /></g>"
} as const satisfies IconData;

export default tbTopologyStarRing2;
export { tbTopologyStarRing2 };
export { tbTopologyStarRing2 as tablerTopologyStarRing2 };
