// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTopologyBus = {
	"name": "topology-bus",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 10a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M6 10a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M22 10a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M2 16h20\" />\n  <path d=\"M4 12v4\" />\n  <path d=\"M12 12v4\" />\n  <path d=\"M20 12v4\" /></g>"
} as const satisfies IconData;

export default tbTopologyBus;
export { tbTopologyBus };
export { tbTopologyBus as tablerTopologyBus };
