// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTopologyStar = {
	"name": "topology-star",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M20 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M8 6a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M20 18a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M14 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M7.5 7.5l3 3\" />\n  <path d=\"M7.5 16.5l3 -3\" />\n  <path d=\"M13.5 13.5l3 3\" />\n  <path d=\"M16.5 7.5l-3 3\" /></g>"
} as const satisfies IconData;

export default tbTopologyStar;
export { tbTopologyStar };
export { tbTopologyStar as tablerTopologyStar };
