// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTopologyStar3 = {
	"name": "topology-star-3",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 19a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M18 5a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M10 5a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M6 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M18 19a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M14 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M22 12a2 2 0 1 0 -4 0a2 2 0 0 0 4 0\" />\n  <path d=\"M6 12h4\" />\n  <path d=\"M14 12h4\" />\n  <path d=\"M15 7l-2 3\" />\n  <path d=\"M9 7l2 3\" />\n  <path d=\"M11 14l-2 3\" />\n  <path d=\"M13 14l2 3\" /></g>"
} as const satisfies IconData;

export default tbTopologyStar3;
export { tbTopologyStar3 };
export { tbTopologyStar3 as tablerTopologyStar3 };
