// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTransactionPound = {
	"name": "transaction-pound",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 14a2 2 0 1 0 -4 0v4a2 2 0 0 1 -2 2h6\" />\n  <path d=\"M15 17h4\" />\n  <path d=\"M3 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M15 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />\n  <path d=\"M7 5h8\" />\n  <path d=\"M7 5v8a3 3 0 0 0 3 3h1\" /></g>"
} as const satisfies IconData;

export default tbTransactionPound;
export { tbTransactionPound };
export { tbTransactionPound as tablerTransactionPound };
