// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTransferVertical = {
	"name": "transfer-vertical",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 4v16l-6 -5.5\" />\n  <path d=\"M14 20v-16l6 5.5\" /></g>"
} as const satisfies IconData;

export default tbTransferVertical;
export { tbTransferVertical };
export { tbTransferVertical as tablerTransferVertical };
