// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbTransitionRight = {
	"name": "transition-right",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 3a3 3 0 0 1 3 3v12a3 3 0 0 1 -3 3\" />\n  <path d=\"M3 18v-12a3 3 0 1 1 6 0v12a3 3 0 0 1 -6 0\" />\n  <path d=\"M9 12h8\" />\n  <path d=\"M14 15l3 -3l-3 -3\" /></g>"
} as const satisfies IconData;

export default tbTransitionRight;
export { tbTransitionRight };
export { tbTransitionRight as tablerTransitionRight };
