// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbUmbrella = {
	"name": "umbrella",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 12a8 8 0 0 1 16 0l-16 0\" />\n  <path d=\"M12 12v6a2 2 0 0 0 4 0\" /></g>"
} as const satisfies IconData;

export default tbUmbrella;
export { tbUmbrella };
export { tbUmbrella as tablerUmbrella };
