// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbUniverse = {
	"name": "universe",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7.027 11.477a5 5 0 1 0 5.496 -4.45a4.951 4.951 0 0 0 -3.088 .681\" />\n  <path d=\"M5.636 5.636a9 9 0 1 0 3.555 -2.188\" />\n  <path d=\"M17 5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />\n  <path d=\"M8 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /></g>"
} as const satisfies IconData;

export default tbUniverse;
export { tbUniverse };
export { tbUniverse as tablerUniverse };
