// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbVacuumCleaner = {
	"name": "vacuum-cleaner",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12a9 9 0 1 1 -18 0a9 9 0 0 1 18 0\" />\n  <path d=\"M14 9a2 2 0 1 1 -4 0a2 2 0 0 1 4 0\" />\n  <path d=\"M12 16h.01\" /></g>"
} as const satisfies IconData;

export default tbVacuumCleaner;
export { tbVacuumCleaner };
export { tbVacuumCleaner as tablerVacuumCleaner };
