// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbViewportTall = {
	"name": "viewport-tall",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 10v-7l3 3\" />\n  <path d=\"M9 6l3 -3\" />\n  <path d=\"M12 14v7l3 -3\" />\n  <path d=\"M9 18l3 3\" />\n  <path d=\"M18 3h1a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-1\" />\n  <path d=\"M6 3h-1a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h1\" /></g>"
} as const satisfies IconData;

export default tbViewportTall;
export { tbViewportTall };
export { tbViewportTall as tablerViewportTall };
