// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbVocabulary = {
	"name": "vocabulary",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 19h-6a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1h6a2 2 0 0 1 2 2a2 2 0 0 1 2 -2h6a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-6a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2\" />\n  <path d=\"M12 5v16\" />\n  <path d=\"M7 7h1\" />\n  <path d=\"M7 11h1\" />\n  <path d=\"M16 7h1\" />\n  <path d=\"M16 11h1\" />\n  <path d=\"M16 15h1\" /></g>"
} as const satisfies IconData;

export default tbVocabulary;
export { tbVocabulary };
export { tbVocabulary as tablerVocabulary };
