// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbWall = {
	"name": "wall",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12\" />\n  <path d=\"M4 8h16\" />\n  <path d=\"M20 12h-16\" />\n  <path d=\"M4 16h16\" />\n  <path d=\"M9 4v4\" />\n  <path d=\"M14 8v4\" />\n  <path d=\"M8 12v4\" />\n  <path d=\"M16 12v4\" />\n  <path d=\"M11 16v4\" /></g>"
} as const satisfies IconData;

export default tbWall;
export { tbWall };
export { tbWall as tablerWall };
