// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbWashDryDip = {
	"name": "wash-dry-dip",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 6a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v12a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-12\" />\n  <path d=\"M12 7v10\" />\n  <path d=\"M16 7v10\" />\n  <path d=\"M8 7v10\" /></g>"
} as const satisfies IconData;

export default tbWashDryDip;
export { tbWashDryDip };
export { tbWashDryDip as tablerWashDryDip };
