// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbWindOff = {
	"name": "wind-off",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 8h3m4 0h1.5a2.5 2.5 0 1 0 -2.34 -3.24\" />\n  <path d=\"M3 12h9\" />\n  <path d=\"M16 12h2.5a2.5 2.5 0 0 1 1.801 4.282\" />\n  <path d=\"M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24\" />\n  <path d=\"M3 3l18 18\" /></g>"
} as const satisfies IconData;

export default tbWindOff;
export { tbWindOff };
export { tbWindOff as tablerWindOff };
