// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbWorldUpload = {
	"name": "world-upload",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12a9 9 0 1 0 -9 9\" />\n  <path d=\"M3.6 9h16.8\" />\n  <path d=\"M3.6 15h8.4\" />\n  <path d=\"M11.578 3a17 17 0 0 0 0 18\" />\n  <path d=\"M12.5 3c1.719 2.755 2.5 5.876 2.5 9\" />\n  <path d=\"M18 21v-7m3 3l-3 -3l-3 3\" /></g>"
} as const satisfies IconData;

export default tbWorldUpload;
export { tbWorldUpload };
export { tbWorldUpload as tablerWorldUpload };
