// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbWorldUp = {
	"name": "world-up",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.985 12.52a9 9 0 1 0 -8.451 8.463\" />\n  <path d=\"M3.6 9h16.8\" />\n  <path d=\"M3.6 15h10.9\" />\n  <path d=\"M11.5 3a17 17 0 0 0 0 18\" />\n  <path d=\"M12.5 3a16.996 16.996 0 0 1 2.391 11.512\" />\n  <path d=\"M19 22v-6\" />\n  <path d=\"M22 19l-3 -3l-3 3\" /></g>"
} as const satisfies IconData;

export default tbWorldUp;
export { tbWorldUp };
export { tbWorldUp as tablerWorldUp };
