// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbZoomReplace = {
	"name": "zoom-replace",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 21l-6 -6\" />\n  <path d=\"M3.291 8a7 7 0 0 1 5.077 -4.806a7.021 7.021 0 0 1 8.242 4.403\" />\n  <path d=\"M17 4v4h-4\" />\n  <path d=\"M16.705 12a7 7 0 0 1 -5.074 4.798a7.021 7.021 0 0 1 -8.241 -4.403\" />\n  <path d=\"M3 16v-4h4\" /></g>"
} as const satisfies IconData;

export default tbZoomReplace;
export { tbZoomReplace };
export { tbZoomReplace as tablerZoomReplace };
