// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const tbZoomQuestion = {
	"name": "zoom-question",
	"set": "tabler",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" />\n  <path d=\"M21 21l-6 -6\" />\n  <path d=\"M10 13l0 .01\" />\n  <path d=\"M10 10a1.5 1.5 0 1 0 -1.14 -2.474\" /></g>"
} as const satisfies IconData;

export default tbZoomQuestion;
export { tbZoomQuestion };
export { tbZoomQuestion as tablerZoomQuestion };
