// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggAlignLeft = {
	"name": "align-left",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M8 13H14V17H8V13Z\" fill=\"currentColor\" fill-opacity=\"0.5\" />\n  <path d=\"M6 6H4V18H6V6Z\" fill=\"currentColor\" />\n  <path d=\"M20 7H8V11H20V7Z\" fill=\"currentColor\" /></g>"
} as const satisfies IconData;

export default ggAlignLeft;
export { ggAlignLeft };
export { ggAlignLeft as cssggAlignLeft };
