// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggArrangeBack = {
	"name": "arrange-back",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M3 3H11V7H17V13H21V21H13V17H7V11H3V3ZM15 13H13V15H9V11H11V9H15V13Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggArrangeBack;
export { ggArrangeBack };
export { ggArrangeBack as cssggArrangeBack };
