// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggArrowLongDown = {
	"name": "arrow-long-down",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M13.0125 19.162L14.8246 17.3398L16.2427 18.7501L12.012 23.0046L7.75726 18.7739L9.16751 17.3557L11.0126 19.1905L10.998 0.997021L12.998 0.995422L13.0125 19.162Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggArrowLongDown;
export { ggArrowLongDown };
export { ggArrowLongDown as cssggArrowLongDown };
