// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggArrowLongLeft = {
	"name": "arrow-long-left",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M1.02698 11.9929L5.26242 16.2426L6.67902 14.8308L4.85766 13.0033L22.9731 13.0012L22.9728 11.0012L4.85309 11.0033L6.6886 9.17398L5.27677 7.75739L1.02698 11.9929Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggArrowLongLeft;
export { ggArrowLongLeft };
export { ggArrowLongLeft as cssggArrowLongLeft };
