// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggArrowsExpandLeftAlt = {
	"name": "arrows-expand-left-alt",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M10.1005 2.10052V4.10052H5.51471L11.293 9.87878L9.87875 11.293L4.10046 5.51471L4.10046 10.1005H2.10046L2.10046 2.10052H10.1005Z\"\n    fill=\"currentColor\"\n  />\n  <path\n    d=\"M21.8995 13.8995H19.8995V18.4853L14.1212 12.707L12.707 14.1213L18.4853 19.8995H13.8995V21.8995H21.8995V13.8995Z\"\n    fill=\"currentColor\"\n  />\n  <path\n    d=\"M16.2426 9.1716L14.8284 7.75739L7.7573 14.8285L9.17151 16.2427L16.2426 9.1716Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggArrowsExpandLeftAlt;
export { ggArrowsExpandLeftAlt };
export { ggArrowsExpandLeftAlt as cssggArrowsExpandLeftAlt };
