// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggBorderStyleDotted = {
	"name": "border-style-dotted",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M3 11H1V13H3V11Z\" fill=\"currentColor\" />\n  <path d=\"M7 11H5V13H7V11Z\" fill=\"currentColor\" />\n  <path d=\"M9 11H11V13H9V11Z\" fill=\"currentColor\" />\n  <path d=\"M15 11H13V13H15V11Z\" fill=\"currentColor\" />\n  <path d=\"M17 11H19V13H17V11Z\" fill=\"currentColor\" />\n  <path d=\"M23 11H21V13H23V11Z\" fill=\"currentColor\" /></g>"
} as const satisfies IconData;

export default ggBorderStyleDotted;
export { ggBorderStyleDotted };
export { ggBorderStyleDotted as cssggBorderStyleDotted };
