// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggChevronDownO = {
	"name": "chevron-down-o",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M7.75745 10.5858L9.17166 9.17154L12.0001 12L14.8285 9.17157L16.2427 10.5858L12.0001 14.8284L7.75745 10.5858Z\"\n    fill=\"currentColor\"\n  />\n  <path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggChevronDownO;
export { ggChevronDownO };
export { ggChevronDownO as cssggChevronDownO };
