// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggDisplaySpacing = {
	"name": "display-spacing",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M3 21V3H5V21H3Z\" fill=\"currentColor\" />\n  <path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M7 3H17V21H7V3ZM9 5V19H15V5H9Z\"\n    fill=\"currentColor\"\n  />\n  <path d=\"M19 3V21H21V3H19Z\" fill=\"currentColor\" /></g>"
} as const satisfies IconData;

export default ggDisplaySpacing;
export { ggDisplaySpacing };
export { ggDisplaySpacing as cssggDisplaySpacing };
