// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggExtensionAdd = {
	"name": "extension-add",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M16 4H18V6H20V8H18V10H16V8H14V6H16V4Z\" fill=\"currentColor\" />\n  <path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M12 12V6H4V20H18V12H12ZM6 8H10V12H6V8ZM10 14V18H6V14H10ZM16 14V18H12V14H16Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggExtensionAdd;
export { ggExtensionAdd };
export { ggExtensionAdd as cssggExtensionAdd };
