// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggFlagAlt = {
	"name": "flag-alt",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M12.4388 7L14.8387 4H7V10H14.8387L12.4388 7ZM19 12H7V22H5V2H19L15 7L19 12Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggFlagAlt;
export { ggFlagAlt };
export { ggFlagAlt as cssggFlagAlt };
