// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggIfDesign = {
	"name": "if-design",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M10 5H14V19H10V5Z\" fill=\"currentColor\" />\n  <path d=\"M5 19V10H9V19H5Z\" fill=\"currentColor\" />\n  <path\n    d=\"M7 5C5.89543 5 5 5.89543 5 7C5 8.10457 5.89543 9 7 9C8.10457 9 9 8.10457 9 7C9 5.89543 8.10457 5 7 5Z\"\n    fill=\"currentColor\"\n  />\n  <path d=\"M15 5H19V9H15V5Z\" fill=\"currentColor\" />\n  <path d=\"M19 10H15V14H19V10Z\" fill=\"currentColor\" /></g>"
} as const satisfies IconData;

export default ggIfDesign;
export { ggIfDesign };
export { ggIfDesign as cssggIfDesign };
