// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggPushChevronUp = {
	"name": "push-chevron-up",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M5 16.929L6.41421 18.3432L12.0711 12.6863L17.7279 18.3432L19.1421 16.929L12.0711 9.85789L5 16.929Z\"\n    fill=\"currentColor\"\n  />\n  <path d=\"M19 8H5V6H19V8Z\" fill=\"currentColor\" /></g>"
} as const satisfies IconData;

export default ggPushChevronUp;
export { ggPushChevronUp };
export { ggPushChevronUp as cssggPushChevronUp };
