// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggPushChevronRightO = {
	"name": "push-chevron-right-o",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path d=\"M14 8H16V16H14V8Z\" fill=\"currentColor\" />\n  <path\n    d=\"M8.70261 16.2427L7.2884 14.8285L10.1168 12L7.28842 9.17164L8.70264 7.75743L12.9453 12.0001L8.70261 16.2427Z\"\n    fill=\"currentColor\"\n  />\n  <path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12ZM21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21C16.9706 21 21 16.9706 21 12Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggPushChevronRightO;
export { ggPushChevronRightO };
export { ggPushChevronRightO as cssggPushChevronRightO };
