// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggShapeTriangle = {
	"name": "shape-triangle",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M11.6603 5L3 20H20.3205L11.6603 5ZM11.6603 11L8.19615 17H15.1244L11.6603 11Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggShapeTriangle;
export { ggShapeTriangle };
export { ggShapeTriangle as cssggShapeTriangle };
