// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggTrendingDown = {
	"name": "trending-down",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    d=\"M1.85104 8.10628L0.436829 9.52049L7.5079 16.5916L13.8719 10.2276L18.1145 14.4702L16.3721 16.2126L23.0642 18.0058L21.2711 11.3136L19.5287 13.056L13.8719 7.39917L7.5079 13.7631L1.85104 8.10628Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggTrendingDown;
export { ggTrendingDown };
export { ggTrendingDown as cssggTrendingDown };
