// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const ggViewSplit = {
	"name": "view-split",
	"set": "cssgg",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\"><path\n    fill-rule=\"evenodd\"\n    clip-rule=\"evenodd\"\n    d=\"M2 8C2 6.34315 3.34315 5 5 5H19C20.6569 5 22 6.34315 22 8V16C22 17.6569 20.6569 19 19 19H5C3.34315 19 2 17.6569 2 16V8ZM13 7H19C19.5523 7 20 7.44771 20 8V16C20 16.5523 19.5523 17 19 17H13V7ZM11 7H5C4.44772 7 4 7.44772 4 8V16C4 16.5523 4.44772 17 5 17H11V7Z\"\n    fill=\"currentColor\"\n  /></g>"
} as const satisfies IconData;

export default ggViewSplit;
export { ggViewSplit };
export { ggViewSplit as cssggViewSplit };
