// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const feBook = {
	"name": "book",
	"set": "feathericons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"/><path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"/></g>"
} as const satisfies IconData;

export default feBook;
export { feBook };
export { feBook as feathericonsBook };
