// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const feCode = {
	"name": "code",
	"set": "feathericons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"16 18 22 12 16 6\"/><polyline points=\"8 6 2 12 8 18\"/></g>"
} as const satisfies IconData;

export default feCode;
export { feCode };
export { feCode as feathericonsCode };
