// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const feCornerDownLeft = {
	"name": "corner-down-left",
	"set": "feathericons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"9 10 4 15 9 20\"/><path d=\"M20 4v7a4 4 0 0 1-4 4H4\"/></g>"
} as const satisfies IconData;

export default feCornerDownLeft;
export { feCornerDownLeft };
export { feCornerDownLeft as feathericonsCornerDownLeft };
