// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const feItalic = {
	"name": "italic",
	"set": "feathericons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"19\" y1=\"4\" x2=\"10\" y2=\"4\"/><line x1=\"14\" y1=\"20\" x2=\"5\" y2=\"20\"/><line x1=\"15\" y1=\"4\" x2=\"9\" y2=\"20\"/></g>"
} as const satisfies IconData;

export default feItalic;
export { feItalic };
export { feItalic as feathericonsItalic };
