// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const fePause = {
	"name": "pause",
	"set": "feathericons",
	"viewBox": "0 0 24 24",
	"body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"6\" y=\"4\" width=\"4\" height=\"16\"/><rect x=\"14\" y=\"4\" width=\"4\" height=\"16\"/></g>"
} as const satisfies IconData;

export default fePause;
export { fePause };
export { fePause as feathericonsPause };
