// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaArrowsLongDiagonal = {
	"name": "arrows-long-diagonal",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.g6s5_g {\n  d: path('M21 3h-8M3 21v-8M21 3v8M3 21h8');\n}\n\n.sh6w8v {\n  d: path('M12 12l-8.5 8.5M12 12l8.5 -8.5');\n}\n\n@media not (prefers-reduced-motion) {\n  .g6s5_g {\n    stroke-dasharray: 10;\n    stroke-dashoffset: 10;\n    animation: 0.2s linear 0.5s forwards so-to-0;\n  }\n\n  .sh6w8v {\n    stroke-dasharray: 16;\n    animation: 0.5s linear forwards so-from-16;\n  }\n}\n\n@keyframes so-from-16 {\n  0% {\n    stroke-dashoffset: 16;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c sh6w8v\"/><path class=\"a0m25c g6s5_g\"/>"
} as const satisfies IconData;

export default maaArrowsLongDiagonal;
export { maaArrowsLongDiagonal };
export { maaArrowsLongDiagonal as materialanimArrowsLongDiagonal };
