// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaBeer = {
	"name": "beer",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.c5xdmn {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.j3vs1j {\n  fill: #000;\n  d: path('M18 3l-2 18h-9l-2 -18h-5v21h24v-20Z');\n}\n\n.uplt5e {\n  d: path('M5 7.67h1c0.6 -0.37 1.22 -0.67 2 -0.67c2 0 3 2 5 2c1.64 0 2.6 -1.34 4 -1.83h1');\n  stroke: #fff;\n}\n\n.yx0aom {\n  d: path('M18 3l-2 18h-9l-2 -18Z');\n  stroke: currentColor;\n}\n\n@media not (prefers-reduced-motion) {\n  .uplt5e {\n    stroke-dasharray: 18;\n    stroke-dashoffset: 18;\n    animation: 0.3s linear 0.6s forwards so-to-0;\n  }\n\n  .yx0aom {\n    stroke-dasharray: 62;\n    animation: 0.6s linear forwards so-from-62;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n\n@keyframes so-from-62 {\n  0% {\n    stroke-dashoffset: 62;\n  }\n}\n</style><defs><mask id=\"SVGyAV2gb7f\"><path class=\"c5xdmn uplt5e\"/><path class=\"j3vs1j\"/></mask></defs><path mask=\"url(#SVGyAV2gb7f)\" class=\"botfzx\"/><path class=\"c5xdmn yx0aom\"/>"
} as const satisfies IconData;

export default maaBeer;
export { maaBeer };
export { maaBeer as materialanimBeer };
