// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaCancel = {
	"name": "cancel",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.irazgx {\n  d: path('M5.64 5.64c3.51 -3.51 9.21 -3.51 12.73 0c3.51 3.51 3.51 9.21 0 12.73c-3.51 3.51 -9.21 3.51 -12.73 0c-3.51 -3.51 -3.51 -9.21 -0 -12.73Z');\n}\n\n.tzadpz {\n  d: path('M6 6l12 12');\n}\n\n@media not (prefers-reduced-motion) {\n  .irazgx {\n    stroke-dasharray: 60;\n    animation: 0.6s linear forwards so-from-60;\n  }\n\n  .tzadpz {\n    stroke-dasharray: 20;\n    stroke-dashoffset: 20;\n    animation: 0.3s linear 0.6s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-60 {\n  0% {\n    stroke-dashoffset: 60;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c irazgx\"/><path class=\"a0m25c tzadpz\"/>"
} as const satisfies IconData;

export default maaCancel;
export { maaCancel };
export { maaCancel as materialanimCancel };
