// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaCarLight = {
	"name": "car-light",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.g_1xrq {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n}\n\n.ka8tpa {\n  d: path('M11 18h-6');\n}\n\n.m8fuxk {\n  d: path('M11 6h-6');\n}\n\n.qw8aly {\n  fill: #000;\n  stroke-width: 4px;\n  stroke: #000;\n}\n\n.u50o9y {\n  d: path('M11 10h-6');\n}\n\n.v3q0ew {\n  stroke: currentColor;\n}\n\n.yl47yi {\n  d: path('M11 14h-6');\n}\n\n.yuzzkf {\n  stroke-width: 2px;\n  fill: none;\n}\n\n.z_b1hb {\n  d: path('M21 12c0 -3.31 -3.5 -6.25 -8.25 -6.25c-0.5 0 -1.75 2.75 -1.75 6.25c0 3.5 1.25 6.25 1.75 6.25c4.75 0 8.25 -2.94 8.25 -6.25Z');\n}\n\n.zxndow {\n  stroke: #fff;\n}\n\n@media not (prefers-reduced-motion) {\n  .ka8tpa {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 1.2s forwards so-to-0;\n  }\n\n  .m8fuxk {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 0.6s forwards so-to-0;\n  }\n\n  .u50o9y {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 0.8s forwards so-to-0;\n  }\n\n  .v3q0ew {\n    stroke-dasharray: 40;\n    animation: 0.5s linear forwards so-from-40;\n  }\n\n  .yl47yi {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 1s forwards so-to-0;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n\n@keyframes so-from-40 {\n  0% {\n    stroke-dashoffset: 40;\n  }\n}\n</style><defs><mask id=\"SVGejBnuc0T\"><path class=\"g_1xrq m8fuxk yuzzkf zxndow\"/><path class=\"g_1xrq u50o9y yuzzkf zxndow\"/><path class=\"g_1xrq yl47yi yuzzkf zxndow\"/><path class=\"g_1xrq ka8tpa yuzzkf zxndow\"/><path class=\"g_1xrq qw8aly z_b1hb\"/></mask></defs><path mask=\"url(#SVGejBnuc0T)\" class=\"botfzx\"/><path class=\"g_1xrq v3q0ew yuzzkf z_b1hb\"/>"
} as const satisfies IconData;

export default maaCarLight;
export { maaCarLight };
export { maaCarLight as materialanimCarLight };
