// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaCellphoneOff = {
	"name": "cellphone-off",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.c5xdmn {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.gd_4-q {\n  d: path('M-1 13h26');\n  stroke: currentColor;\n}\n\n.gwd63i {\n  d: path('M12 2h5c0.55 0 1 0.45 1 1v18c0 0.55 -0.45 1 -1 1h-10c-0.55 0 -1 -0.45 -1 -1v-18c0 -0.55 0.45 -1 1 -1Z');\n  stroke: #fff;\n}\n\n.oxx-om {\n  d: path('M-1 11h26');\n  stroke: #000;\n}\n\n.tbv09e {\n  transform: rotate(45deg);\n  transform-origin: 12px 12px;\n}\n\n.uedp7a {\n  d: path('M6 2h12v3h-12ZM6 22h12v-3h-12Z');\n  fill: #fff;\n}\n\n@media not (prefers-reduced-motion) {\n  .gwd63i {\n    stroke-dasharray: 66;\n    animation: 0.6s linear forwards so-from-66;\n  }\n\n  .tbv09e {\n    stroke-dasharray: 28;\n    stroke-dashoffset: 28;\n    animation: 0.4s linear 0.9s forwards so-to-0;\n  }\n\n  .uedp7a {\n    animation: 0s forwards d-3crpcp, 0.2s linear 0.6s forwards d-70g21a;\n  }\n}\n\n@keyframes so-from-66 {\n  0% {\n    stroke-dashoffset: 66;\n  }\n}\n\n@keyframes d-3crpcp {\n  100% {\n    d: path('M6 2h12v0h-12ZM6 22h12v0h-12Z');\n  }\n}\n\n@keyframes d-70g21a {\n  100% {\n    d: path('M6 2h12v3h-12ZM6 22h12v-3h-12Z');\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><defs><mask id=\"SVGvu2hhbjN\"><path class=\"c5xdmn gwd63i\"/><path class=\"uedp7a\"/><path class=\"c5xdmn oxx-om tbv09e\"/></mask></defs><path mask=\"url(#SVGvu2hhbjN)\" class=\"botfzx\"/><path class=\"c5xdmn gd_4-q tbv09e\"/>"
} as const satisfies IconData;

export default maaCellphoneOff;
export { maaCellphoneOff };
export { maaCellphoneOff as materialanimCellphoneOff };
