// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaChevronDownSquare = {
	"name": "chevron-down-square",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.bp3adc {\n  d: path('M12 14l-3 -3M12 14l3 -3');\n}\n\n.f5s6pk {\n  d: path('M20 12v7c0 0.55 -0.45 1 -1 1h-14c-0.55 0 -1 -0.44 -1 -1v-14c0 -0.55 0.45 -1 1 -1h14c0.55 0 1 0.45 1 1Z');\n}\n\n@media not (prefers-reduced-motion) {\n  .bp3adc {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.4s linear 0.7s forwards so-to-0;\n  }\n\n  .f5s6pk {\n    stroke-dasharray: 66;\n    animation: 0.6s linear forwards so-from-66;\n  }\n}\n\n@keyframes so-from-66 {\n  0% {\n    stroke-dashoffset: 66;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c f5s6pk\"/><path class=\"a0m25c bp3adc\"/>"
} as const satisfies IconData;

export default maaChevronDownSquare;
export { maaChevronDownSquare };
export { maaChevronDownSquare as materialanimChevronDownSquare };
