// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaClipboardToClipboardCheckTransition = {
	"name": "clipboard-to-clipboard-check-transition",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.b1659c {\n  d: path('M9 13l2 2l4 -4');\n}\n\n.ecu16w {\n  d: path('M14.5 3.5v3h-5v-3');\n}\n\n.qa-o7h {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  fill: none;\n}\n\n.taf2xz {\n  stroke-width: 2px;\n}\n\n.wc7n7b {\n  d: path('M12 3h7v18h-14v-18h7Z');\n}\n\n@media not (prefers-reduced-motion) {\n  .b1659c {\n    stroke-dasharray: 12;\n    animation: 0.2s linear forwards so-from-12;\n  }\n}\n\n@keyframes so-from-12 {\n  0% {\n    stroke-dashoffset: 12;\n  }\n}\n</style><path class=\"qa-o7h taf2xz wc7n7b\"/><path class=\"ecu16w qa-o7h\"/><path class=\"b1659c qa-o7h taf2xz\"/>"
} as const satisfies IconData;

export default maaClipboardToClipboardCheckTransition;
export { maaClipboardToClipboardCheckTransition };
export { maaClipboardToClipboardCheckTransition as materialanimClipboardToClipboardCheckTransition };
