// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaClose = {
	"name": "close",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.eo47_w {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  d: path('M12 12l7 7M12 12l-7 -7M12 12l-7 7M12 12l7 -7');\n  fill: none;\n}\n\n@media not (prefers-reduced-motion) {\n  .eo47_w {\n    stroke-dasharray: 12;\n    animation: 0.4s linear forwards so-from-12;\n  }\n}\n\n@keyframes so-from-12 {\n  0% {\n    stroke-dashoffset: 12;\n  }\n}\n</style><path class=\"eo47_w\"/>"
} as const satisfies IconData;

export default maaClose;
export { maaClose };
export { maaClose as materialanimClose };
