// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaCoffee = {
	"name": "coffee",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.nh6wfl {\n  d: path('M17 4v9c0 1.66 -1.34 3 -3 3h-6c-1.66 0 -3 -1.34 -3 -3v-9Z');\n}\n\n.rakmch {\n  d: path('M11 20h8M11 20h-8');\n}\n\n.ywbs5z {\n  d: path('M17 4h3c0.55 0 1 0.45 1 1v3c0 0.55 -0.45 1 -1 1h-3');\n}\n\n@media not (prefers-reduced-motion) {\n  .nh6wfl {\n    stroke-dasharray: 48;\n    stroke-dashoffset: 48;\n    animation: 0.6s linear 0.4s forwards so-to-0;\n  }\n\n  .rakmch {\n    stroke-dasharray: 10;\n    animation: 0.4s linear forwards so-from-10;\n  }\n\n  .ywbs5z {\n    stroke-dasharray: 16;\n    stroke-dashoffset: 16;\n    animation: 0.3s linear 1s forwards so-to-0;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n\n@keyframes so-from-10 {\n  0% {\n    stroke-dashoffset: 10;\n  }\n}\n</style><path class=\"a0m25c nh6wfl\"/><path class=\"a0m25c ywbs5z\"/><path class=\"a0m25c rakmch\"/>"
} as const satisfies IconData;

export default maaCoffee;
export { maaCoffee };
export { maaCoffee as materialanimCoffee };
