// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaDownloadOutline = {
	"name": "download-outline",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.okiwoc {\n  d: path('M6 19h12');\n}\n\n.wm005g {\n  d: path('M12 4h2v6h2.5l-4.5 4.5M12 4h-2v6h-2.5l4.5 4.5');\n}\n\n@media not (prefers-reduced-motion) {\n  .okiwoc {\n    stroke-dasharray: 14;\n    stroke-dashoffset: 14;\n    animation: 0.2s linear 0.5s forwards so-to-0;\n  }\n\n  .wm005g {\n    stroke-dasharray: 20;\n    animation: 0.5s linear forwards so-from-20;\n  }\n}\n\n@keyframes so-from-20 {\n  0% {\n    stroke-dashoffset: 20;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c wm005g\"/><path class=\"a0m25c okiwoc\"/>"
} as const satisfies IconData;

export default maaDownloadOutline;
export { maaDownloadOutline };
export { maaDownloadOutline as materialanimDownloadOutline };
