// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaEdit = {
	"name": "edit",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.d-uxzh {\n  d: path('M3 21h18');\n}\n\n.ddx_6x {\n  d: path('M7 17v-4l10 -10l4 4l-10 10h-4');\n}\n\n.idmydr {\n  d: path('M14 6l4 4');\n}\n\n@media not (prefers-reduced-motion) {\n  .d-uxzh {\n    stroke-dasharray: 20;\n    animation: 0.3s linear forwards so-from-20;\n  }\n\n  .ddx_6x {\n    stroke-dasharray: 44;\n    stroke-dashoffset: 44;\n    animation: 0.5s linear 0.3s forwards so-to-0;\n  }\n\n  .idmydr {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 0.8s forwards so-to-0;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n\n@keyframes so-from-20 {\n  0% {\n    stroke-dashoffset: 20;\n  }\n}\n</style><path class=\"a0m25c ddx_6x\"/><path class=\"a0m25c d-uxzh\"/><path class=\"a0m25c idmydr\"/>"
} as const satisfies IconData;

export default maaEdit;
export { maaEdit };
export { maaEdit as materialanimEdit };
