// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaEmailOpenedMultiple = {
	"name": "email-opened-multiple",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.qfvpsi {\n  d: path('M5 8.5l9 5.5l9 -5.5');\n}\n\n.te6v-x {\n  d: path('M5 8.06c0 -0.35 0.18 -0.67 0.48 -0.85l8.52 -5.21l8.52 5.21c0.3 0.18 0.48 0.5 0.48 0.85v9.94c0 0.55 -0.45 1 -1 1h-16c-0.55 0 -1 -0.45 -1 -1v-9.94Z');\n}\n\n.z4421m {\n  d: path('M19 23h-17c-0.55 0 -1 -0.45 -1 -1v-13');\n}\n\n@media not (prefers-reduced-motion) {\n  .qfvpsi {\n    stroke-dasharray: 24;\n    stroke-dashoffset: 24;\n    animation: 0.3s linear 0.6s forwards so-to-0;\n  }\n\n  .te6v-x {\n    stroke-dasharray: 64;\n    animation: 0.6s linear forwards so-from-64;\n  }\n\n  .z4421m {\n    stroke-dasharray: 34;\n    stroke-dashoffset: 34;\n    animation: 0.3s linear 0.3s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-64 {\n  0% {\n    stroke-dashoffset: 64;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c te6v-x\"/><path class=\"a0m25c z4421m\"/><path class=\"a0m25c qfvpsi\"/>"
} as const satisfies IconData;

export default maaEmailOpenedMultiple;
export { maaEmailOpenedMultiple };
export { maaEmailOpenedMultiple as materialanimEmailOpenedMultiple };
