// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaFileOff = {
	"name": "file-off",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.fr4-ze {\n  fill: #fff;\n  d: path('M14 3.5l0 4.5l4.5 0Z');\n}\n\n.gd_4-q {\n  d: path('M-1 13h26');\n  stroke: currentColor;\n}\n\n.lvtybe {\n  transform: rotate(45deg);\n  transform-origin: 12px 12px;\n}\n\n.oxx-om {\n  d: path('M-1 11h26');\n  stroke: #000;\n}\n\n.sgi08m {\n  d: path('M13.5 3l5.5 5.5v11.5c0 0.55 -0.45 1 -1 1h-12c-0.55 0 -1 -0.45 -1 -1v-16c0 -0.55 0.45 -1 1 -1Z');\n}\n\n.t5pxry {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 2px;\n}\n\n.y4wbml {\n  fill: none;\n}\n\n.zxndow {\n  stroke: #fff;\n}\n\n@media not (prefers-reduced-motion) {\n  .fr4-ze {\n    opacity: 0;\n    animation: 0s 0.6s forwards fade-to-1, 0.2s linear 0.6s forwards d-_-jasl;\n  }\n\n  .lvtybe {\n    stroke-dasharray: 28;\n    stroke-dashoffset: 28;\n    animation: 0.4s linear 0.8s forwards so-to-0;\n  }\n\n  .sgi08m {\n    stroke-dasharray: 62;\n    animation: 0.6s linear forwards so-from-62;\n  }\n}\n\n@keyframes so-from-62 {\n  0% {\n    stroke-dashoffset: 62;\n  }\n}\n\n@keyframes fade-to-1 {\n  100% {\n    opacity: 1;\n  }\n}\n\n@keyframes d-_-jasl {\n  0% {\n    d: path('M14 3.5l2.25 2.25l2.25 2.25Z');\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><defs><mask id=\"SVGDMwQGdEe\"><path class=\"sgi08m t5pxry y4wbml zxndow\"/><path class=\"fr4-ze t5pxry zxndow\"/><path class=\"lvtybe oxx-om t5pxry y4wbml\"/></mask></defs><path mask=\"url(#SVGDMwQGdEe)\" class=\"botfzx\"/><path class=\"gd_4-q lvtybe t5pxry y4wbml\"/>"
} as const satisfies IconData;

export default maaFileOff;
export { maaFileOff };
export { maaFileOff as materialanimFileOff };
