// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaFilterAltOff = {
	"name": "filter-alt-off",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.c5xdmn {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.dw7e4l {\n  transform: rotate(45deg);\n  transform-origin: 12px 12px;\n}\n\n.fhjn7n {\n  d: path('M4 7h16');\n}\n\n.lwtq5s {\n  stroke: #000;\n  d: path('M0 11h24');\n}\n\n.otlizu {\n  d: path('M11 17h2');\n}\n\n.r5412d {\n  d: path('M0 13h24');\n  stroke: currentColor;\n}\n\n.tj796y {\n  d: path('M7 12h10');\n}\n\n.zxndow {\n  stroke: #fff;\n}\n\n@media not (prefers-reduced-motion) {\n  .dw7e4l {\n    stroke-dasharray: 26;\n    stroke-dashoffset: 26;\n    animation: 0.4s linear 0.7s forwards so-to-0;\n  }\n\n  .fhjn7n {\n    stroke-dasharray: 18;\n    animation: 0.3s linear forwards so-from-18;\n  }\n\n  .otlizu {\n    stroke-dasharray: 4;\n    stroke-dashoffset: 4;\n    animation: 0.2s linear 0.5s forwards so-to-0;\n  }\n\n  .tj796y {\n    stroke-dasharray: 12;\n    stroke-dashoffset: 12;\n    animation: 0.2s linear 0.3s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-18 {\n  0% {\n    stroke-dashoffset: 18;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><defs><mask id=\"SVGzgHVsdWf\"><path class=\"c5xdmn fhjn7n zxndow\"/><path class=\"c5xdmn tj796y zxndow\"/><path class=\"c5xdmn otlizu zxndow\"/><path class=\"c5xdmn dw7e4l lwtq5s\"/></mask></defs><path mask=\"url(#SVGzgHVsdWf)\" class=\"botfzx\"/><path class=\"c5xdmn dw7e4l r5412d\"/>"
} as const satisfies IconData;

export default maaFilterAltOff;
export { maaFilterAltOff };
export { maaFilterAltOff as materialanimFilterAltOff };
