// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaGithubLoop = {
	"name": "github-loop",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.bmu-7y {\n  d: path('M12 4c1.67 0 2.61 0.4 3 0.5c0.53 -0.43 1.94 -1.5 3.5 -1.5c0.34 1 0.29 2.22 0 3c0.75 1 1 2 1 3.5c0 2.19 -0.48 3.58 -1.5 4.5c-1.02 0.92 -2.11 1.37 -3.5 1.5c0.65 0.54 0.5 1.87 0.5 2.5c0 0.73 0 3 0 3M12 4c-1.67 0 -2.61 0.4 -3 0.5c-0.53 -0.43 -1.94 -1.5 -3.5 -1.5c-0.34 1 -0.29 2.22 0 3c-0.75 1 -1 2 -1 3.5c0 2.19 0.48 3.58 1.5 4.5c1.02 0.92 2.11 1.37 3.5 1.5c-0.65 0.54 -0.5 1.87 -0.5 2.5c0 0.73 0 3 0 3');\n}\n\n.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.duw0fy {\n  x: 8px;\n  width: 8px;\n  height: 4px;\n  fill: #000;\n  y: 7px;\n}\n\n.gzxsfm {\n  d: path('M9 19c-1.41 0 -2.84 -0.56 -3.69 -1.19c-0.84 -0.62 -1.09 -1.66 -2.31 -2.31');\n}\n\n.rharcy {\n  fill: #fff;\n  d: path('M9.5 8c0.83 0 1.5 0.45 1.5 1c0 0.55 -0.67 1 -1.5 1c-0.83 0 -1.5 -0.45 -1.5 -1c0 -0.55 0.67 -1 1.5 -1ZM14.5 8c0.83 0 1.5 0.45 1.5 1c0 0.55 -0.67 1 -1.5 1c-0.83 0 -1.5 -0.45 -1.5 -1c0 -0.55 0.67 -1 1.5 -1Z');\n}\n\n@media not (prefers-reduced-motion) {\n  .bmu-7y {\n    stroke-dasharray: 32;\n    animation: 0.6s linear forwards so-from-32;\n  }\n\n  .duw0fy {\n    animation: 9s linear infinite y-z56c7r;\n  }\n\n  .gzxsfm {\n    stroke-dasharray: 10;\n    stroke-dashoffset: 10;\n    animation: 3s linear infinite d-18l3_d, 0.2s linear 0.7s forwards so-to-0;\n  }\n}\n\n@keyframes y-z56c7r {\n  45%, 55% {\n    y: 7px;\n  }\n  46%, 54% {\n    y: 11px;\n  }\n}\n\n@keyframes so-from-32 {\n  0% {\n    stroke-dashoffset: 32;\n  }\n}\n\n@keyframes d-18l3_d {\n  50% {\n    d: path('M9 19c-1.41 0 -3 -0.5 -4 -0.5c-0.53 0 -1 0 -2 -0.5');\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><defs><mask id=\"SVGZ3PjieoC\"><path class=\"rharcy\"/><rect class=\"duw0fy\"/></mask></defs><path class=\"a0m25c bmu-7y\"/><path class=\"a0m25c gzxsfm\"/><path mask=\"url(#SVGZ3PjieoC)\" class=\"botfzx\"/>"
} as const satisfies IconData;

export default maaGithubLoop;
export { maaGithubLoop };
export { maaGithubLoop as materialanimGithubLoop };
