// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaMapMarkerAlt = {
	"name": "map-marker-alt",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.ntj7kf {\n  r: 2.5px;\n  cx: 12px;\n  cy: 9px;\n  fill: currentColor;\n}\n\n.s4x1bs {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  d: path('M12 20.5c0 0 -6 -7 -6 -11.5c0 -3.31 2.69 -6 6 -6c3.31 0 6 2.69 6 6c0 4.5 -6 11.5 -6 11.5Z');\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n@media not (prefers-reduced-motion) {\n  .ntj7kf {\n    animation: 0s forwards r-to-0px, 0.2s linear 0.4s forwards r-to-2_5px;\n  }\n\n  .s4x1bs {\n    animation: 0.4s linear forwards d-jkxijw;\n  }\n}\n\n@keyframes d-jkxijw {\n  0% {\n    d: path('M12 20.5c0 0 -1 -1.5 -1 -2.5c0 -0.5 0.5 -1 1 -1c0.5 0 1 0.5 1 1c0 1 -1 2.5 -1 2.5Z');\n  }\n  70% {\n    d: path('M12 20.5c0 0 -7 -7.5 -7 -12.5c0 -3.5 3 -7 7 -7c4 0 7 3.5 7 7c0 5 -7 12.5 -7 12.5Z');\n  }\n}\n\n@keyframes r-to-0px {\n  100% {\n    r: 0px;\n  }\n}\n\n@keyframes r-to-2_5px {\n  100% {\n    r: 2.5px;\n  }\n}\n</style><path class=\"s4x1bs\"/><circle class=\"ntj7kf\"/>"
} as const satisfies IconData;

export default maaMapMarkerAlt;
export { maaMapMarkerAlt };
export { maaMapMarkerAlt as materialanimMapMarkerAlt };
