// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaMenuFoldLeft = {
	"name": "menu-fold-left",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.k-a29e {\n  d: path('M7 9l-3 3l3 3');\n}\n\n.nov9iu {\n  d: path('M19 5h-14');\n}\n\n.qqamjf {\n  d: path('M19 12h-9');\n}\n\n.suwabu {\n  d: path('M19 19h-14');\n}\n\n@media not (prefers-reduced-motion) {\n  .k-a29e {\n    stroke-dasharray: 12;\n    stroke-dashoffset: 12;\n    animation: 0.2s linear 0.8s forwards so-to-0;\n  }\n\n  .nov9iu {\n    stroke-dasharray: 16;\n    animation: 0.3s linear forwards so-from-16;\n  }\n\n  .qqamjf {\n    stroke-dasharray: 12;\n    stroke-dashoffset: 12;\n    animation: 0.2s linear 0.3s forwards so-to-0;\n  }\n\n  .suwabu {\n    stroke-dasharray: 16;\n    stroke-dashoffset: 16;\n    animation: 0.3s linear 0.5s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-16 {\n  0% {\n    stroke-dashoffset: 16;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c nov9iu\"/><path class=\"a0m25c qqamjf\"/><path class=\"a0m25c suwabu\"/><path class=\"a0m25c k-a29e\"/>"
} as const satisfies IconData;

export default maaMenuFoldLeft;
export { maaMenuFoldLeft };
export { maaMenuFoldLeft as materialanimMenuFoldLeft };
