// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaPeertube = {
	"name": "peertube",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.g7trfy {\n  fill: #fff;\n  d: path('M4 1.34l16 10.66l-16 10.67Z');\n}\n\n.yfo60c {\n  d: path('M12 6.67v10.67l-8 -5.34Z');\n  fill: #000;\n}\n\n@media not (prefers-reduced-motion) {\n  .g7trfy {\n    animation: 0.4s linear forwards d-tbwzce;\n  }\n}\n\n@keyframes d-tbwzce {\n  0% {\n    d: path('M12 12l0 0l0 0Z');\n  }\n}\n</style><defs><mask id=\"SVGOgwoJbQI\"><path class=\"g7trfy\"/><path class=\"yfo60c\"/></mask></defs><path mask=\"url(#SVGOgwoJbQI)\" class=\"botfzx\"/>"
} as const satisfies IconData;

export default maaPeertube;
export { maaPeertube };
export { maaPeertube as materialanimPeertube };
