// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaPhoneIncoming = {
	"name": "phone-incoming",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.ain8nj {\n  d: path('M8 3c0.5 0 2.5 4.5 2.5 5c0 1 -1.5 2 -2 3c-0.5 1 0.5 2 1.5 3c0.39 0.39 2 2 3 1.5c1 -0.5 2 -2 3 -2c0.5 0 5 2 5 2.5c0 2 -1.5 3.5 -3 4c-1.5 0.5 -2.5 0.5 -4.5 0c-2 -0.5 -3.5 -1 -6 -3.5c-2.5 -2.5 -3 -4 -3.5 -6c-0.5 -2 -0.5 -3 0 -4.5c0.5 -1.5 2 -3 4 -3Z');\n}\n\n.dsugin {\n  d: path('M20 4l-4 4');\n}\n\n.g-mogd {\n  d: path('M16 8h4M16 8v-4');\n}\n\n@media not (prefers-reduced-motion) {\n  .ain8nj {\n    stroke-dasharray: 62;\n    animation: 0.6s linear forwards so-from-62;\n  }\n\n  .dsugin {\n    stroke-dasharray: 8;\n    stroke-dashoffset: 8;\n    animation: 0.2s linear 0.7s forwards so-to-0;\n  }\n\n  .g-mogd {\n    stroke-dasharray: 6;\n    stroke-dashoffset: 6;\n    animation: 0.2s linear 0.9s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-62 {\n  0% {\n    stroke-dashoffset: 62;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c ain8nj\"/><path class=\"a0m25c dsugin\"/><path class=\"a0m25c g-mogd\"/>"
} as const satisfies IconData;

export default maaPhoneIncoming;
export { maaPhoneIncoming };
export { maaPhoneIncoming as materialanimPhoneIncoming };
