// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaPlus = {
	"name": "plus",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.a0m25c {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke: currentColor;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.celmyq {\n  d: path('M5 12h14');\n}\n\n.qbipjn {\n  d: path('M12 5v14');\n}\n\n@media not (prefers-reduced-motion) {\n  .celmyq {\n    stroke-dasharray: 16;\n    animation: 0.5s linear forwards so-from-16;\n  }\n\n  .qbipjn {\n    stroke-dasharray: 16;\n    stroke-dashoffset: 16;\n    animation: 0.5s linear 0.5s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-16 {\n  0% {\n    stroke-dashoffset: 16;\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><path class=\"a0m25c celmyq\"/><path class=\"a0m25c qbipjn\"/>"
} as const satisfies IconData;

export default maaPlus;
export { maaPlus };
export { maaPlus as materialanimPlus };
