// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaSunnyOff = {
	"name": "sunny-off",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.c5xdmn {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 2px;\n  fill: none;\n}\n\n.fyi9-p {\n  d: path('M18.5 18.5l0.5 0.5M18.5 5.5l0.5 -0.5M5.5 5.5l-0.5 -0.5M5.5 18.5l-0.5 0.5');\n}\n\n.gd_4-q {\n  d: path('M-1 13h26');\n  stroke: currentColor;\n}\n\n.ml9e2l {\n  d: path('M12 21v1M21 12h1M12 3v-1M3 12h-1');\n}\n\n.mo0t0x {\n  d: path('M12 7c2.76 0 5 2.24 5 5c0 2.76 -2.24 5 -5 5c-2.76 0 -5 -2.24 -5 -5c0 -2.76 2.24 -5 5 -5Z');\n}\n\n.oxx-om {\n  d: path('M-1 11h26');\n  stroke: #000;\n}\n\n.tbv09e {\n  transform: rotate(45deg);\n  transform-origin: 12px 12px;\n}\n\n.zxndow {\n  stroke: #fff;\n}\n\n@media not (prefers-reduced-motion) {\n  .fyi9-p {\n    opacity: 0;\n    animation: 0s 0.7s forwards fade-to-1, 0.2s linear 0.7s forwards d-s9ijad;\n  }\n\n  .ml9e2l {\n    opacity: 0;\n    animation: 0s 0.5s forwards fade-to-1, 0.2s linear 0.5s forwards d-9_o5mj;\n  }\n\n  .mo0t0x {\n    stroke-dasharray: 34;\n    animation: 0.4s linear forwards so-from-34;\n  }\n\n  .tbv09e {\n    stroke-dasharray: 28;\n    stroke-dashoffset: 28;\n    animation: 0.4s linear 0.9s forwards so-to-0;\n  }\n}\n\n@keyframes so-from-34 {\n  0% {\n    stroke-dashoffset: 34;\n  }\n}\n\n@keyframes fade-to-1 {\n  100% {\n    opacity: 1;\n  }\n}\n\n@keyframes d-9_o5mj {\n  0% {\n    d: path('M12 19v1M19 12h1M12 5v-1M5 12h-1');\n  }\n}\n\n@keyframes d-s9ijad {\n  0% {\n    d: path('M17 17l0.5 0.5M17 7l0.5 -0.5M7 7l-0.5 -0.5M7 17l-0.5 0.5');\n  }\n}\n\n@keyframes so-to-0 {\n  100% {\n    stroke-dashoffset: 0;\n  }\n}\n</style><defs><mask id=\"SVG1bXqpbwE\"><path class=\"c5xdmn mo0t0x zxndow\"/><path class=\"c5xdmn ml9e2l zxndow\"/><path class=\"c5xdmn fyi9-p zxndow\"/><path class=\"c5xdmn oxx-om tbv09e\"/></mask></defs><path mask=\"url(#SVG1bXqpbwE)\" class=\"botfzx\"/><path class=\"c5xdmn gd_4-q tbv09e\"/>"
} as const satisfies IconData;

export default maaSunnyOff;
export { maaSunnyOff };
export { maaSunnyOff as materialanimSunnyOff };
