// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const maaTiktok = {
	"name": "tiktok",
	"set": "materialanim",
	"viewBox": "0 0 24 24",
	"body": "<style>.botfzx {\n  d: path('M0 0h24v24H0z');\n  fill: currentColor;\n}\n\n.hoafol {\n  d: path('M18 2.5v8');\n}\n\n.lvinjf {\n  stroke-linecap: round;\n  stroke-linejoin: round;\n  stroke-width: 4px;\n  stroke: #000;\n  fill: none;\n}\n\n.swsrfi {\n  d: path('M11 11h-1c-2.21 0 -4.5 1.79 -4.5 4c0 2.21 1.5 4.5 4.5 4.5c2.21 0 4 -2.29 4 -4.5v-12.5');\n}\n\n.v57ckn {\n  fill: #fff;\n  d: path('M16.6 5.82c-0.68 -0.78 -1.06 -1.78 -1.06 -2.82h-3.09v12.4c-0.02 0.67 -0.31 1.31 -0.79 1.77c-0.48 0.47 -1.13 0.73 -1.8 0.73c-1.42 0 -2.6 -1.16 -2.6 -2.6c0 -1.72 1.66 -3.01 3.37 -2.48v-3.16c-3.45 -0.46 -6.47 2.22 -6.47 5.64c0 3.33 2.76 5.7 5.69 5.7c3.14 0 5.69 -2.55 5.69 -5.7v-6.29c1.25 0.9 2.76 1.38 4.3 1.38v-3.09c0 0 -1.88 0.09 -3.24 -1.48Z');\n}\n\n@media not (prefers-reduced-motion) {\n  .hoafol {\n    stroke-dasharray: 10;\n    stroke-dashoffset: 20;\n    animation: 0.1s linear 0.5s forwards so-to-10;\n  }\n\n  .swsrfi {\n    stroke-dasharray: 36;\n    animation: 0.6s linear forwards so-yqhc8a;\n  }\n}\n\n@keyframes so-yqhc8a {\n  0% {\n    stroke-dashoffset: 72;\n  }\n  100% {\n    stroke-dashoffset: 36;\n  }\n}\n\n@keyframes so-to-10 {\n  100% {\n    stroke-dashoffset: 10;\n  }\n}\n</style><defs><mask id=\"SVG4hTeXcJA\"><path class=\"v57ckn\"/><path class=\"lvinjf swsrfi\"/><path class=\"hoafol lvinjf\"/></mask></defs><path mask=\"url(#SVG4hTeXcJA)\" class=\"botfzx\"/>"
} as const satisfies IconData;

export default maaTiktok;
export { maaTiktok };
export { maaTiktok as materialanimTiktok };
